#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Bot_Base

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function ABP_Bot_Base.ABP_Bot_Base_C.ExecuteUbergraph_ABP_Bot_Base
// 0x0130 (0x0130 - 0x0000)
struct ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetInstanceAssetPlayerTimeFromEndFraction_ReturnValue; // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue;         // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A[0x2];                                        // 0x000A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetInstanceAssetPlayerTimeFromEndFraction_ReturnValue_1; // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue;              // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x0013(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0016(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x0017(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_3;                 // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_4;                 // 0x001A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_2;        // 0x001B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue_1;      // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_5;                 // 0x001D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue_2;      // 0x001E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_1;    // 0x001F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsRightPeep_ReturnValue;                  // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsLeftPeep_ReturnValue;                   // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_3;        // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue_1;            // 0x0023(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_4;        // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_6;                 // 0x0025(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_7;                 // 0x0026(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_8;                 // 0x0027(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_5;        // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue_3;      // 0x002A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValidPeep_ReturnValue;                  // 0x002B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue_2;                // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_6;        // 0x002D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_9;                 // 0x002E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue_4;      // 0x002F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValidPeep_ReturnValue_1;                // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_10;                // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue_3;                // 0x0032(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_33[0x1];                                       // 0x0033(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetInstanceAssetPlayerTimeFromEndFraction_ReturnValue_2; // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue_2;            // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_1;                              // 0x003A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3B[0x1];                                       // 0x003B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetInstanceAssetPlayerTimeFromEndFraction_ReturnValue_3; // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue_3;            // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x3];                                       // 0x0041(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetRelevantAnimTimeRemaining_ReturnValue; // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_1;       // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_7;        // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_2;                              // 0x004A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_3;                              // 0x004B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue_5;      // 0x004C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4D[0x3];                                       // 0x004D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Abs_ReturnValue;                          // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_2;    // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue;      // 0x0055(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x0056(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue_4;            // 0x0057(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_2;                  // 0x0059(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5A[0x2];                                       // 0x005A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Abs_ReturnValue_1;                        // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_1;         // 0x0064(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_2;       // 0x0065(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue_5;            // 0x0066(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_3;                  // 0x0067(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_4;                  // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_3;       // 0x0069(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_2;         // 0x006A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6B[0x1];                                       // 0x006B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_1;        // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_4;       // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_5;       // 0x0071(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_11;                // 0x0072(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue_1;    // 0x0073(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_6;       // 0x0074(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_12;                // 0x0075(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_76[0x2];                                       // 0x0076(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_1; // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_7;       // 0x007C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_13;                // 0x007D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_14;                // 0x007E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_3;    // 0x007F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_4;    // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimSequence*                          CallFunc_GetStatusAdditiveAnim_ReturnValue;        // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue_6;      // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_5;    // 0x0091(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_92[0x2];                                       // 0x0092(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_SelectFloat_ReturnValue;                  // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_6;    // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_7;    // 0x0099(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_15;                // 0x009A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9B[0x1];                                       // 0x009B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_2; // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_8;        // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_8;       // 0x00A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_16;                // 0x00A2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_5;                  // 0x00A3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_17;                // 0x00A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_3;         // 0x00A5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_4;                              // 0x00A6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_5;                              // 0x00A7(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UAnimSequenceBase*                      K2Node_Select_Default;                             // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimSequenceBase*                      K2Node_Select_Default_1;                           // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsTurningInProcess_ReturnValue;           // 0x00B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_18;                // 0x00BA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue_4;                // 0x00BB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue_2;    // 0x00BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_4;         // 0x00BD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_6;                  // 0x00BE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_7;                  // 0x00BF(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsTurningInProcess_ReturnValue_1;         // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_8;                  // 0x00C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue_5;                // 0x00C2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C3[0x1];                                       // 0x00C3(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_2;        // 0x00C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_5;         // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_9;       // 0x00C9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_9;                  // 0x00CA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_10;                 // 0x00CB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_11;                 // 0x00CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_10;      // 0x00CD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_6;         // 0x00CE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CF[0x1];                                       // 0x00CF(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_3;        // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_11;      // 0x00D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_12;      // 0x00D5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_19;                // 0x00D6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_9;        // 0x00D7(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_20;                // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue_3;    // 0x00D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_13;      // 0x00DA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_21;                // 0x00DB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_10;       // 0x00DC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_22;                // 0x00DD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue_7;      // 0x00DE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_DF[0x1];                                       // 0x00DF(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimSequence*                          CallFunc_GetStatusAdditiveAnim_ReturnValue_1;      // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue_8;      // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E9[0x3];                                       // 0x00E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_SelectFloat_ReturnValue_1;                // 0x00EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue_9;      // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_11;       // 0x00F1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_23;                // 0x00F2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F3[0x1];                                       // 0x00F3(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_3; // 0x00F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue_10;     // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_14;      // 0x00F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_24;                // 0x00FA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_25;                // 0x00FB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_12;                 // 0x00FC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_12;       // 0x00FD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_26;                // 0x00FE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_7;         // 0x00FF(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_6;                              // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_7;                              // 0x0101(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_102[0x6];                                      // 0x0102(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimSequenceBase*                      K2Node_Select_Default_2;                           // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimSequenceBase*                      K2Node_Select_Default_3;                           // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Montage_IsPlaying_ReturnValue;            // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue_1;          // 0x0119(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue_2;          // 0x011A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_27;                // 0x011B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_28;                // 0x011C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsCanPlayStatusAnimMontage_ReturnValue;   // 0x011D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_29;                // 0x011E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11F[0x1];                                      // 0x011F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Conv_BoolToFloat_ReturnValue;             // 0x0120(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_13;       // 0x0124(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_125[0x3];                                      // 0x0125(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Event_DeltaTimeX;                           // 0x0128(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base) == 0x000008, "Wrong alignment on ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base");
static_assert(sizeof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base) == 0x000130, "Wrong size on ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, EntryPoint) == 0x000000, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::EntryPoint' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_GetInstanceAssetPlayerTimeFromEndFraction_ReturnValue) == 0x000004, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_GetInstanceAssetPlayerTimeFromEndFraction_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_LessEqual_FloatFloat_ReturnValue) == 0x000008, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_LessEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000009, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_GetInstanceAssetPlayerTimeFromEndFraction_ReturnValue_1) == 0x00000C, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_GetInstanceAssetPlayerTimeFromEndFraction_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Less_FloatFloat_ReturnValue) == 0x000010, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Less_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Not_PreBool_ReturnValue) == 0x000011, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue) == 0x000012, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Not_PreBool_ReturnValue_1) == 0x000013, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_1) == 0x000014, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_NotEqual_ObjectObject_ReturnValue) == 0x000015, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_NotEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000016, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x000017, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_2) == 0x000018, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_3) == 0x000019, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_4) == 0x00001A, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_EqualEqual_ByteByte_ReturnValue_2) == 0x00001B, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_EqualEqual_ByteByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_NotEqual_ObjectObject_ReturnValue_1) == 0x00001C, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_NotEqual_ObjectObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_5) == 0x00001D, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_NotEqual_ObjectObject_ReturnValue_2) == 0x00001E, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_NotEqual_ObjectObject_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_EqualEqual_ObjectObject_ReturnValue_1) == 0x00001F, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_EqualEqual_ObjectObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_IsRightPeep_ReturnValue) == 0x000020, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_IsRightPeep_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_IsLeftPeep_ReturnValue) == 0x000021, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_IsLeftPeep_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_EqualEqual_ByteByte_ReturnValue_3) == 0x000022, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_EqualEqual_ByteByte_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Less_FloatFloat_ReturnValue_1) == 0x000023, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Less_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_EqualEqual_ByteByte_ReturnValue_4) == 0x000024, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_EqualEqual_ByteByte_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_6) == 0x000025, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_7) == 0x000026, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_8) == 0x000027, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_EqualEqual_ByteByte_ReturnValue_5) == 0x000028, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_EqualEqual_ByteByte_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanOR_ReturnValue) == 0x000029, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_NotEqual_ObjectObject_ReturnValue_3) == 0x00002A, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_NotEqual_ObjectObject_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_IsValidPeep_ReturnValue) == 0x00002B, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_IsValidPeep_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Not_PreBool_ReturnValue_2) == 0x00002C, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Not_PreBool_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_EqualEqual_ByteByte_ReturnValue_6) == 0x00002D, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_EqualEqual_ByteByte_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_9) == 0x00002E, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_NotEqual_ObjectObject_ReturnValue_4) == 0x00002F, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_NotEqual_ObjectObject_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_IsValidPeep_ReturnValue_1) == 0x000030, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_IsValidPeep_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_10) == 0x000031, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Not_PreBool_ReturnValue_3) == 0x000032, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Not_PreBool_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_GetInstanceAssetPlayerTimeFromEndFraction_ReturnValue_2) == 0x000034, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_GetInstanceAssetPlayerTimeFromEndFraction_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Less_FloatFloat_ReturnValue_2) == 0x000038, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Less_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, Temp_bool_Variable) == 0x000039, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, Temp_bool_Variable_1) == 0x00003A, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_GetInstanceAssetPlayerTimeFromEndFraction_ReturnValue_3) == 0x00003C, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_GetInstanceAssetPlayerTimeFromEndFraction_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Less_FloatFloat_ReturnValue_3) == 0x000040, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Less_FloatFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_GetRelevantAnimTimeRemaining_ReturnValue) == 0x000044, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_GetRelevantAnimTimeRemaining_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_LessEqual_FloatFloat_ReturnValue_1) == 0x000048, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_LessEqual_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_EqualEqual_ByteByte_ReturnValue_7) == 0x000049, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_EqualEqual_ByteByte_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, Temp_bool_Variable_2) == 0x00004A, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, Temp_bool_Variable_3) == 0x00004B, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::Temp_bool_Variable_3' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_NotEqual_ObjectObject_ReturnValue_5) == 0x00004C, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_NotEqual_ObjectObject_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Abs_ReturnValue) == 0x000050, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Abs_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_EqualEqual_ObjectObject_ReturnValue_2) == 0x000054, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_EqualEqual_ObjectObject_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_GreaterEqual_FloatFloat_ReturnValue) == 0x000055, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_GreaterEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Greater_FloatFloat_ReturnValue) == 0x000056, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Less_FloatFloat_ReturnValue_4) == 0x000057, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Less_FloatFloat_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanOR_ReturnValue_1) == 0x000058, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanOR_ReturnValue_2) == 0x000059, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanOR_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Abs_ReturnValue_1) == 0x00005C, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Abs_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x000060, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Greater_FloatFloat_ReturnValue_1) == 0x000064, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Greater_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_LessEqual_FloatFloat_ReturnValue_2) == 0x000065, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_LessEqual_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Less_FloatFloat_ReturnValue_5) == 0x000066, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Less_FloatFloat_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanOR_ReturnValue_3) == 0x000067, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanOR_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanOR_ReturnValue_4) == 0x000068, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanOR_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_LessEqual_FloatFloat_ReturnValue_3) == 0x000069, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_LessEqual_FloatFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Greater_FloatFloat_ReturnValue_2) == 0x00006A, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Greater_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Multiply_FloatFloat_ReturnValue_1) == 0x00006C, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Multiply_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_LessEqual_FloatFloat_ReturnValue_4) == 0x000070, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_LessEqual_FloatFloat_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_LessEqual_FloatFloat_ReturnValue_5) == 0x000071, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_LessEqual_FloatFloat_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_11) == 0x000072, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_GreaterEqual_FloatFloat_ReturnValue_1) == 0x000073, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_GreaterEqual_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_LessEqual_FloatFloat_ReturnValue_6) == 0x000074, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_LessEqual_FloatFloat_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_12) == 0x000075, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_12' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_1) == 0x000078, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_LessEqual_FloatFloat_ReturnValue_7) == 0x00007C, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_LessEqual_FloatFloat_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_13) == 0x00007D, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_13' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_14) == 0x00007E, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_14' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_EqualEqual_ObjectObject_ReturnValue_3) == 0x00007F, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_EqualEqual_ObjectObject_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_EqualEqual_ObjectObject_ReturnValue_4) == 0x000080, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_EqualEqual_ObjectObject_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_GetStatusAdditiveAnim_ReturnValue) == 0x000088, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_GetStatusAdditiveAnim_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_NotEqual_ObjectObject_ReturnValue_6) == 0x000090, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_NotEqual_ObjectObject_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_EqualEqual_ObjectObject_ReturnValue_5) == 0x000091, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_EqualEqual_ObjectObject_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_SelectFloat_ReturnValue) == 0x000094, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_SelectFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_EqualEqual_ObjectObject_ReturnValue_6) == 0x000098, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_EqualEqual_ObjectObject_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_EqualEqual_ObjectObject_ReturnValue_7) == 0x000099, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_EqualEqual_ObjectObject_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_15) == 0x00009A, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_15' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_2) == 0x00009C, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_EqualEqual_ByteByte_ReturnValue_8) == 0x0000A0, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_EqualEqual_ByteByte_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_LessEqual_FloatFloat_ReturnValue_8) == 0x0000A1, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_LessEqual_FloatFloat_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_16) == 0x0000A2, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_16' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanOR_ReturnValue_5) == 0x0000A3, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanOR_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_17) == 0x0000A4, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_17' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Greater_FloatFloat_ReturnValue_3) == 0x0000A5, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Greater_FloatFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, Temp_bool_Variable_4) == 0x0000A6, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::Temp_bool_Variable_4' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, Temp_bool_Variable_5) == 0x0000A7, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::Temp_bool_Variable_5' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, K2Node_Select_Default) == 0x0000A8, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, K2Node_Select_Default_1) == 0x0000B0, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x0000B8, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_IsTurningInProcess_ReturnValue) == 0x0000B9, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_IsTurningInProcess_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_18) == 0x0000BA, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_18' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Not_PreBool_ReturnValue_4) == 0x0000BB, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Not_PreBool_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_GreaterEqual_FloatFloat_ReturnValue_2) == 0x0000BC, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_GreaterEqual_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Greater_FloatFloat_ReturnValue_4) == 0x0000BD, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Greater_FloatFloat_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanOR_ReturnValue_6) == 0x0000BE, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanOR_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanOR_ReturnValue_7) == 0x0000BF, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanOR_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_IsTurningInProcess_ReturnValue_1) == 0x0000C0, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_IsTurningInProcess_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanOR_ReturnValue_8) == 0x0000C1, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanOR_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Not_PreBool_ReturnValue_5) == 0x0000C2, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Not_PreBool_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Multiply_FloatFloat_ReturnValue_2) == 0x0000C4, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Multiply_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Greater_FloatFloat_ReturnValue_5) == 0x0000C8, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Greater_FloatFloat_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_LessEqual_FloatFloat_ReturnValue_9) == 0x0000C9, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_LessEqual_FloatFloat_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanOR_ReturnValue_9) == 0x0000CA, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanOR_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanOR_ReturnValue_10) == 0x0000CB, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanOR_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanOR_ReturnValue_11) == 0x0000CC, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanOR_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_LessEqual_FloatFloat_ReturnValue_10) == 0x0000CD, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_LessEqual_FloatFloat_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Greater_FloatFloat_ReturnValue_6) == 0x0000CE, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Greater_FloatFloat_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Multiply_FloatFloat_ReturnValue_3) == 0x0000D0, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Multiply_FloatFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_LessEqual_FloatFloat_ReturnValue_11) == 0x0000D4, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_LessEqual_FloatFloat_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_LessEqual_FloatFloat_ReturnValue_12) == 0x0000D5, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_LessEqual_FloatFloat_ReturnValue_12' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_19) == 0x0000D6, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_19' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_EqualEqual_ByteByte_ReturnValue_9) == 0x0000D7, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_EqualEqual_ByteByte_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_20) == 0x0000D8, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_20' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_GreaterEqual_FloatFloat_ReturnValue_3) == 0x0000D9, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_GreaterEqual_FloatFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_LessEqual_FloatFloat_ReturnValue_13) == 0x0000DA, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_LessEqual_FloatFloat_ReturnValue_13' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_21) == 0x0000DB, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_21' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_EqualEqual_ByteByte_ReturnValue_10) == 0x0000DC, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_EqualEqual_ByteByte_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_22) == 0x0000DD, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_22' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_NotEqual_ObjectObject_ReturnValue_7) == 0x0000DE, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_NotEqual_ObjectObject_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_GetStatusAdditiveAnim_ReturnValue_1) == 0x0000E0, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_GetStatusAdditiveAnim_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_NotEqual_ObjectObject_ReturnValue_8) == 0x0000E8, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_NotEqual_ObjectObject_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_SelectFloat_ReturnValue_1) == 0x0000EC, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_SelectFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_NotEqual_ObjectObject_ReturnValue_9) == 0x0000F0, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_NotEqual_ObjectObject_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_EqualEqual_ByteByte_ReturnValue_11) == 0x0000F1, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_EqualEqual_ByteByte_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_23) == 0x0000F2, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_23' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_3) == 0x0000F4, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_NotEqual_ObjectObject_ReturnValue_10) == 0x0000F8, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_NotEqual_ObjectObject_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_LessEqual_FloatFloat_ReturnValue_14) == 0x0000F9, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_LessEqual_FloatFloat_ReturnValue_14' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_24) == 0x0000FA, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_24' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_25) == 0x0000FB, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_25' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanOR_ReturnValue_12) == 0x0000FC, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanOR_ReturnValue_12' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_EqualEqual_ByteByte_ReturnValue_12) == 0x0000FD, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_EqualEqual_ByteByte_ReturnValue_12' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_26) == 0x0000FE, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_26' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Greater_FloatFloat_ReturnValue_7) == 0x0000FF, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Greater_FloatFloat_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, Temp_bool_Variable_6) == 0x000100, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::Temp_bool_Variable_6' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, Temp_bool_Variable_7) == 0x000101, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::Temp_bool_Variable_7' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, K2Node_Select_Default_2) == 0x000108, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, K2Node_Select_Default_3) == 0x000110, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::K2Node_Select_Default_3' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Montage_IsPlaying_ReturnValue) == 0x000118, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Montage_IsPlaying_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_NotEqual_ByteByte_ReturnValue_1) == 0x000119, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_NotEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_NotEqual_ByteByte_ReturnValue_2) == 0x00011A, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_NotEqual_ByteByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_27) == 0x00011B, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_27' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_28) == 0x00011C, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_28' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_IsCanPlayStatusAnimMontage_ReturnValue) == 0x00011D, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_IsCanPlayStatusAnimMontage_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_BooleanAND_ReturnValue_29) == 0x00011E, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_BooleanAND_ReturnValue_29' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_Conv_BoolToFloat_ReturnValue) == 0x000120, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_Conv_BoolToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, CallFunc_EqualEqual_ByteByte_ReturnValue_13) == 0x000124, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::CallFunc_EqualEqual_ByteByte_ReturnValue_13' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base, K2Node_Event_DeltaTimeX) == 0x000128, "Member 'ABP_Bot_Base_C_ExecuteUbergraph_ABP_Bot_Base::K2Node_Event_DeltaTimeX' has a wrong offset!");

// Function ABP_Bot_Base.ABP_Bot_Base_C.BlueprintUpdateAnimation
// 0x0004 (0x0004 - 0x0000)
struct ABP_Bot_Base_C_BlueprintUpdateAnimation final
{
public:
	float                                         DeltaTimeX;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ABP_Bot_Base_C_BlueprintUpdateAnimation) == 0x000004, "Wrong alignment on ABP_Bot_Base_C_BlueprintUpdateAnimation");
static_assert(sizeof(ABP_Bot_Base_C_BlueprintUpdateAnimation) == 0x000004, "Wrong size on ABP_Bot_Base_C_BlueprintUpdateAnimation");
static_assert(offsetof(ABP_Bot_Base_C_BlueprintUpdateAnimation, DeltaTimeX) == 0x000000, "Member 'ABP_Bot_Base_C_BlueprintUpdateAnimation::DeltaTimeX' has a wrong offset!");

// Function ABP_Bot_Base.ABP_Bot_Base_C.UpdateAnimsByOldTEMP
// 0x000F (0x000F - 0x0000)
struct ABP_Bot_Base_C_UpdateAnimsByOldTEMP final
{
public:
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_1;    // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_2;    // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_3;    // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_4;    // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue_1;      // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue_2;      // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue_3;      // 0x000B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_3;                 // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue_4;      // 0x000D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_4;                 // 0x000E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ABP_Bot_Base_C_UpdateAnimsByOldTEMP) == 0x000001, "Wrong alignment on ABP_Bot_Base_C_UpdateAnimsByOldTEMP");
static_assert(sizeof(ABP_Bot_Base_C_UpdateAnimsByOldTEMP) == 0x00000F, "Wrong size on ABP_Bot_Base_C_UpdateAnimsByOldTEMP");
static_assert(offsetof(ABP_Bot_Base_C_UpdateAnimsByOldTEMP, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000000, "Member 'ABP_Bot_Base_C_UpdateAnimsByOldTEMP::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_UpdateAnimsByOldTEMP, CallFunc_EqualEqual_ObjectObject_ReturnValue_1) == 0x000001, "Member 'ABP_Bot_Base_C_UpdateAnimsByOldTEMP::CallFunc_EqualEqual_ObjectObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_UpdateAnimsByOldTEMP, CallFunc_EqualEqual_ObjectObject_ReturnValue_2) == 0x000002, "Member 'ABP_Bot_Base_C_UpdateAnimsByOldTEMP::CallFunc_EqualEqual_ObjectObject_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_UpdateAnimsByOldTEMP, CallFunc_NotEqual_ObjectObject_ReturnValue) == 0x000003, "Member 'ABP_Bot_Base_C_UpdateAnimsByOldTEMP::CallFunc_NotEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_UpdateAnimsByOldTEMP, CallFunc_BooleanAND_ReturnValue) == 0x000004, "Member 'ABP_Bot_Base_C_UpdateAnimsByOldTEMP::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_UpdateAnimsByOldTEMP, CallFunc_EqualEqual_ObjectObject_ReturnValue_3) == 0x000005, "Member 'ABP_Bot_Base_C_UpdateAnimsByOldTEMP::CallFunc_EqualEqual_ObjectObject_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_UpdateAnimsByOldTEMP, CallFunc_EqualEqual_ObjectObject_ReturnValue_4) == 0x000006, "Member 'ABP_Bot_Base_C_UpdateAnimsByOldTEMP::CallFunc_EqualEqual_ObjectObject_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_UpdateAnimsByOldTEMP, CallFunc_NotEqual_ObjectObject_ReturnValue_1) == 0x000007, "Member 'ABP_Bot_Base_C_UpdateAnimsByOldTEMP::CallFunc_NotEqual_ObjectObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_UpdateAnimsByOldTEMP, CallFunc_BooleanAND_ReturnValue_1) == 0x000008, "Member 'ABP_Bot_Base_C_UpdateAnimsByOldTEMP::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_UpdateAnimsByOldTEMP, CallFunc_NotEqual_ObjectObject_ReturnValue_2) == 0x000009, "Member 'ABP_Bot_Base_C_UpdateAnimsByOldTEMP::CallFunc_NotEqual_ObjectObject_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_UpdateAnimsByOldTEMP, CallFunc_BooleanAND_ReturnValue_2) == 0x00000A, "Member 'ABP_Bot_Base_C_UpdateAnimsByOldTEMP::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_UpdateAnimsByOldTEMP, CallFunc_NotEqual_ObjectObject_ReturnValue_3) == 0x00000B, "Member 'ABP_Bot_Base_C_UpdateAnimsByOldTEMP::CallFunc_NotEqual_ObjectObject_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_UpdateAnimsByOldTEMP, CallFunc_BooleanAND_ReturnValue_3) == 0x00000C, "Member 'ABP_Bot_Base_C_UpdateAnimsByOldTEMP::CallFunc_BooleanAND_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_UpdateAnimsByOldTEMP, CallFunc_NotEqual_ObjectObject_ReturnValue_4) == 0x00000D, "Member 'ABP_Bot_Base_C_UpdateAnimsByOldTEMP::CallFunc_NotEqual_ObjectObject_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ABP_Bot_Base_C_UpdateAnimsByOldTEMP, CallFunc_BooleanAND_ReturnValue_4) == 0x00000E, "Member 'ABP_Bot_Base_C_UpdateAnimsByOldTEMP::CallFunc_BooleanAND_ReturnValue_4' has a wrong offset!");

// Function ABP_Bot_Base.ABP_Bot_Base_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct ABP_Bot_Base_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(ABP_Bot_Base_C_AnimGraph) == 0x000008, "Wrong alignment on ABP_Bot_Base_C_AnimGraph");
static_assert(sizeof(ABP_Bot_Base_C_AnimGraph) == 0x000010, "Wrong size on ABP_Bot_Base_C_AnimGraph");
static_assert(offsetof(ABP_Bot_Base_C_AnimGraph, AnimGraph_0) == 0x000000, "Member 'ABP_Bot_Base_C_AnimGraph::AnimGraph_0' has a wrong offset!");

}

