#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AttackTarget_BotBehState

#include "Basic.hpp"

#include "BP_AttackTarget_BotBehState_classes.hpp"
#include "BP_AttackTarget_BotBehState_parameters.hpp"


namespace SDK
{

// Function BP_AttackTarget_BotBehState.BP_AttackTarget_BotBehState_C.CanThrowThisItemToTarget
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// const class AActor*                     Item                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UBP_AttackTarget_BotBehState_C::CanThrowThisItemToTarget(const class AActor* Item) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AttackTarget_BotBehState_C", "CanThrowThisItemToTarget");

	Params::BP_AttackTarget_BotBehState_C_CanThrowThisItemToTarget Parms{};

	Parms.Item = Item;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

