#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BaseModActor

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BaseModActor.BP_BaseModActor_C
// 0x0058 (0x02E8 - 0x0290)
class ABP_BaseModActor_C : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0290(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   RootMesh;                                          // 0x0298(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	double                                        InteractionDistance;                               // 0x02A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bHasApply;                                         // 0x02A8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          bHasAction;                                        // 0x02A9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          bHasHold;                                          // 0x02AA(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          bHasUse;                                           // 0x02AB(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_2AC[0x4];                                      // 0x02AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                PickupLocation;                                    // 0x02B0(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               PickupRotation;                                    // 0x02C8(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bDropPhysics;                                      // 0x02E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void EventName(const class FString& Name_0, class UObject* Object);
	void ExecuteUbergraph_BP_BaseModActor(int32 EntryPoint);
	void OnAction(class ACharacter* Character);
	void OnApplied(class AActor* AppliedOn, class ACharacter* Character, bool* bItemStillInHands);
	void OnDrop(class ACharacter* Character);
	void OnPickup(class ACharacter* Character);
	void OnReceivedApply(class AActor* Applying, class ACharacter* Character);
	void OnUse(class ACharacter* Character);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BaseModActor_C">();
	}
	static class ABP_BaseModActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BaseModActor_C>();
	}
};
static_assert(alignof(ABP_BaseModActor_C) == 0x000008, "Wrong alignment on ABP_BaseModActor_C");
static_assert(sizeof(ABP_BaseModActor_C) == 0x0002E8, "Wrong size on ABP_BaseModActor_C");
static_assert(offsetof(ABP_BaseModActor_C, UberGraphFrame) == 0x000290, "Member 'ABP_BaseModActor_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_BaseModActor_C, RootMesh) == 0x000298, "Member 'ABP_BaseModActor_C::RootMesh' has a wrong offset!");
static_assert(offsetof(ABP_BaseModActor_C, InteractionDistance) == 0x0002A0, "Member 'ABP_BaseModActor_C::InteractionDistance' has a wrong offset!");
static_assert(offsetof(ABP_BaseModActor_C, bHasApply) == 0x0002A8, "Member 'ABP_BaseModActor_C::bHasApply' has a wrong offset!");
static_assert(offsetof(ABP_BaseModActor_C, bHasAction) == 0x0002A9, "Member 'ABP_BaseModActor_C::bHasAction' has a wrong offset!");
static_assert(offsetof(ABP_BaseModActor_C, bHasHold) == 0x0002AA, "Member 'ABP_BaseModActor_C::bHasHold' has a wrong offset!");
static_assert(offsetof(ABP_BaseModActor_C, bHasUse) == 0x0002AB, "Member 'ABP_BaseModActor_C::bHasUse' has a wrong offset!");
static_assert(offsetof(ABP_BaseModActor_C, PickupLocation) == 0x0002B0, "Member 'ABP_BaseModActor_C::PickupLocation' has a wrong offset!");
static_assert(offsetof(ABP_BaseModActor_C, PickupRotation) == 0x0002C8, "Member 'ABP_BaseModActor_C::PickupRotation' has a wrong offset!");
static_assert(offsetof(ABP_BaseModActor_C, bDropPhysics) == 0x0002E0, "Member 'ABP_BaseModActor_C::bDropPhysics' has a wrong offset!");

}

