#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Bed_Dog

#include "Basic.hpp"

#include "BP_Bed_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Bed_Dog.BP_Bed_Dog_C
// 0x0000 (0x0910 - 0x0910)
class ABP_Bed_Dog_C final : public ABP_Bed_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Bed_Dog_C">();
	}
	static class ABP_Bed_Dog_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Bed_Dog_C>();
	}
};
static_assert(alignof(ABP_Bed_Dog_C) == 0x000010, "Wrong alignment on ABP_Bed_Dog_C");
static_assert(sizeof(ABP_Bed_Dog_C) == 0x000910, "Wrong size on ABP_Bed_Dog_C");

}

