#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Bakery_Fridge_Key

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "HelloNeighbor2_structs.hpp"


namespace SDK::Params
{

// Function BP_Bakery_Fridge_Key.BP_Bakery_Fridge_Key_C.OnBeginApply
// 0x0218 (0x0218 - 0x0000)
struct BP_Bakery_Fridge_Key_C_OnBeginApply final
{
public:
	class ABaseCharacter*                         Character;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             Hit;                                               // 0x0008(0x0088)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class UAnimConnection*                        Connection;                                        // 0x0090(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTraceActorInfo                        TraceActorInfo;                                    // 0x0098(0x00D8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	struct FCursorInfo                            CursorInfo;                                        // 0x0170(0x0014)(Parm, OutParm, NoDestructor)
	EApplyAnswer                                  ReturnValue;                                       // 0x0184(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x0185(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x0186(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_187[0x1];                                      // 0x0187(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x0188(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x018C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x0190(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x019C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x01A8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x01B4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x01C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x01C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x01D0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x01D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x01E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x01E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x01E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x01EC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x01F8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_204[0x4];                                      // 0x0204(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_Bakery_Fridge_Lock_C*               K2Node_DynamicCast_AsBP_Bakery_Fridge_Lock;        // 0x0208(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0210(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Bakery_Fridge_Key_C_OnBeginApply) == 0x000008, "Wrong alignment on BP_Bakery_Fridge_Key_C_OnBeginApply");
static_assert(sizeof(BP_Bakery_Fridge_Key_C_OnBeginApply) == 0x000218, "Wrong size on BP_Bakery_Fridge_Key_C_OnBeginApply");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, Character) == 0x000000, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::Character' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, Hit) == 0x000008, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::Hit' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, Connection) == 0x000090, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::Connection' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, TraceActorInfo) == 0x000098, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::TraceActorInfo' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, CursorInfo) == 0x000170, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::CursorInfo' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, ReturnValue) == 0x000184, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, CallFunc_BreakHitResult_bBlockingHit) == 0x000185, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, CallFunc_BreakHitResult_bInitialOverlap) == 0x000186, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, CallFunc_BreakHitResult_Time) == 0x000188, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, CallFunc_BreakHitResult_Distance) == 0x00018C, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, CallFunc_BreakHitResult_Location) == 0x000190, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, CallFunc_BreakHitResult_ImpactPoint) == 0x00019C, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, CallFunc_BreakHitResult_Normal) == 0x0001A8, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, CallFunc_BreakHitResult_ImpactNormal) == 0x0001B4, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, CallFunc_BreakHitResult_PhysMat) == 0x0001C0, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, CallFunc_BreakHitResult_HitActor) == 0x0001C8, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, CallFunc_BreakHitResult_HitComponent) == 0x0001D0, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, CallFunc_BreakHitResult_HitBoneName) == 0x0001D8, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, CallFunc_BreakHitResult_HitItem) == 0x0001E0, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, CallFunc_BreakHitResult_ElementIndex) == 0x0001E4, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, CallFunc_BreakHitResult_FaceIndex) == 0x0001E8, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, CallFunc_BreakHitResult_TraceStart) == 0x0001EC, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, CallFunc_BreakHitResult_TraceEnd) == 0x0001F8, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, K2Node_DynamicCast_AsBP_Bakery_Fridge_Lock) == 0x000208, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::K2Node_DynamicCast_AsBP_Bakery_Fridge_Lock' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_OnBeginApply, K2Node_DynamicCast_bSuccess) == 0x000210, "Member 'BP_Bakery_Fridge_Key_C_OnBeginApply::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function BP_Bakery_Fridge_Key.BP_Bakery_Fridge_Key_C.HasApply
// 0x0240 (0x0240 - 0x0000)
struct BP_Bakery_Fridge_Key_C_HasApply final
{
public:
	const class ABaseCharacter*                   Character;                                         // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             Hit;                                               // 0x0008(0x0088)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FActorProxy                            TraceActor;                                        // 0x0090(0x00D0)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	struct FCursorInfo                            CursorInfo;                                        // 0x0160(0x0014)(Parm, OutParm, NoDestructor)
	bool                                          ReturnValue;                                       // 0x0174(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0175(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x0176(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x0177(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_BreakHitResult_Time;                      // 0x0178(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x017C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x0180(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x018C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x0198(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x01A4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x01B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x01B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x01C0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x01C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x01D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x01D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x01D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x01DC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x01E8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FCursorInfo                            K2Node_MakeStruct_CursorInfo;                      // 0x01F4(0x0014)(NoDestructor)
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue;               // 0x0208(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FCursorInfo                            K2Node_MakeStruct_CursorInfo_1;                    // 0x0210(0x0014)(NoDestructor)
	bool                                          CallFunc_ClassIsChildOf_ReturnValue;               // 0x0224(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_225[0x3];                                      // 0x0225(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCursorInfo                            K2Node_Select_Default;                             // 0x0228(0x0014)(NoDestructor)
};
static_assert(alignof(BP_Bakery_Fridge_Key_C_HasApply) == 0x000008, "Wrong alignment on BP_Bakery_Fridge_Key_C_HasApply");
static_assert(sizeof(BP_Bakery_Fridge_Key_C_HasApply) == 0x000240, "Wrong size on BP_Bakery_Fridge_Key_C_HasApply");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, Character) == 0x000000, "Member 'BP_Bakery_Fridge_Key_C_HasApply::Character' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, Hit) == 0x000008, "Member 'BP_Bakery_Fridge_Key_C_HasApply::Hit' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, TraceActor) == 0x000090, "Member 'BP_Bakery_Fridge_Key_C_HasApply::TraceActor' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, CursorInfo) == 0x000160, "Member 'BP_Bakery_Fridge_Key_C_HasApply::CursorInfo' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, ReturnValue) == 0x000174, "Member 'BP_Bakery_Fridge_Key_C_HasApply::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, Temp_bool_Variable) == 0x000175, "Member 'BP_Bakery_Fridge_Key_C_HasApply::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, CallFunc_BreakHitResult_bBlockingHit) == 0x000176, "Member 'BP_Bakery_Fridge_Key_C_HasApply::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, CallFunc_BreakHitResult_bInitialOverlap) == 0x000177, "Member 'BP_Bakery_Fridge_Key_C_HasApply::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, CallFunc_BreakHitResult_Time) == 0x000178, "Member 'BP_Bakery_Fridge_Key_C_HasApply::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, CallFunc_BreakHitResult_Distance) == 0x00017C, "Member 'BP_Bakery_Fridge_Key_C_HasApply::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, CallFunc_BreakHitResult_Location) == 0x000180, "Member 'BP_Bakery_Fridge_Key_C_HasApply::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, CallFunc_BreakHitResult_ImpactPoint) == 0x00018C, "Member 'BP_Bakery_Fridge_Key_C_HasApply::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, CallFunc_BreakHitResult_Normal) == 0x000198, "Member 'BP_Bakery_Fridge_Key_C_HasApply::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, CallFunc_BreakHitResult_ImpactNormal) == 0x0001A4, "Member 'BP_Bakery_Fridge_Key_C_HasApply::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, CallFunc_BreakHitResult_PhysMat) == 0x0001B0, "Member 'BP_Bakery_Fridge_Key_C_HasApply::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, CallFunc_BreakHitResult_HitActor) == 0x0001B8, "Member 'BP_Bakery_Fridge_Key_C_HasApply::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, CallFunc_BreakHitResult_HitComponent) == 0x0001C0, "Member 'BP_Bakery_Fridge_Key_C_HasApply::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, CallFunc_BreakHitResult_HitBoneName) == 0x0001C8, "Member 'BP_Bakery_Fridge_Key_C_HasApply::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, CallFunc_BreakHitResult_HitItem) == 0x0001D0, "Member 'BP_Bakery_Fridge_Key_C_HasApply::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, CallFunc_BreakHitResult_ElementIndex) == 0x0001D4, "Member 'BP_Bakery_Fridge_Key_C_HasApply::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, CallFunc_BreakHitResult_FaceIndex) == 0x0001D8, "Member 'BP_Bakery_Fridge_Key_C_HasApply::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, CallFunc_BreakHitResult_TraceStart) == 0x0001DC, "Member 'BP_Bakery_Fridge_Key_C_HasApply::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, CallFunc_BreakHitResult_TraceEnd) == 0x0001E8, "Member 'BP_Bakery_Fridge_Key_C_HasApply::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, K2Node_MakeStruct_CursorInfo) == 0x0001F4, "Member 'BP_Bakery_Fridge_Key_C_HasApply::K2Node_MakeStruct_CursorInfo' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, CallFunc_GetObjectClass_ReturnValue) == 0x000208, "Member 'BP_Bakery_Fridge_Key_C_HasApply::CallFunc_GetObjectClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, K2Node_MakeStruct_CursorInfo_1) == 0x000210, "Member 'BP_Bakery_Fridge_Key_C_HasApply::K2Node_MakeStruct_CursorInfo_1' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, CallFunc_ClassIsChildOf_ReturnValue) == 0x000224, "Member 'BP_Bakery_Fridge_Key_C_HasApply::CallFunc_ClassIsChildOf_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_HasApply, K2Node_Select_Default) == 0x000228, "Member 'BP_Bakery_Fridge_Key_C_HasApply::K2Node_Select_Default' has a wrong offset!");

// Function BP_Bakery_Fridge_Key.BP_Bakery_Fridge_Key_C.CanApplyToTraceActor
// 0x01F8 (0x01F8 - 0x0000)
struct BP_Bakery_Fridge_Key_C_CanApplyToTraceActor final
{
public:
	const class ABaseCharacter*                   Character;                                         // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FActorProxy                            HandActor;                                         // 0x0008(0x00D0)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	struct FHitResult                             Hit;                                               // 0x00D8(0x0088)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          ReturnValue;                                       // 0x0160(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x0161(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x0162(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_163[0x1];                                      // 0x0163(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x0164(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x0168(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x016C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x0178(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x0184(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x0190(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19C[0x4];                                      // 0x019C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x01A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x01B0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x01B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x01C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x01C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x01C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x01CC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x01D8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E4[0x4];                                      // 0x01E4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue;               // 0x01E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_ClassIsChildOf_ReturnValue;               // 0x01F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor) == 0x000008, "Wrong alignment on BP_Bakery_Fridge_Key_C_CanApplyToTraceActor");
static_assert(sizeof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor) == 0x0001F8, "Wrong size on BP_Bakery_Fridge_Key_C_CanApplyToTraceActor");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, Character) == 0x000000, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::Character' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, HandActor) == 0x000008, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::HandActor' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, Hit) == 0x0000D8, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::Hit' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, ReturnValue) == 0x000160, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, CallFunc_BreakHitResult_bBlockingHit) == 0x000161, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, CallFunc_BreakHitResult_bInitialOverlap) == 0x000162, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, CallFunc_BreakHitResult_Time) == 0x000164, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, CallFunc_BreakHitResult_Distance) == 0x000168, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, CallFunc_BreakHitResult_Location) == 0x00016C, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, CallFunc_BreakHitResult_ImpactPoint) == 0x000178, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, CallFunc_BreakHitResult_Normal) == 0x000184, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, CallFunc_BreakHitResult_ImpactNormal) == 0x000190, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, CallFunc_BreakHitResult_PhysMat) == 0x0001A0, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, CallFunc_BreakHitResult_HitActor) == 0x0001A8, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, CallFunc_BreakHitResult_HitComponent) == 0x0001B0, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, CallFunc_BreakHitResult_HitBoneName) == 0x0001B8, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, CallFunc_BreakHitResult_HitItem) == 0x0001C0, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, CallFunc_BreakHitResult_ElementIndex) == 0x0001C4, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, CallFunc_BreakHitResult_FaceIndex) == 0x0001C8, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, CallFunc_BreakHitResult_TraceStart) == 0x0001CC, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, CallFunc_BreakHitResult_TraceEnd) == 0x0001D8, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, CallFunc_GetObjectClass_ReturnValue) == 0x0001E8, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::CallFunc_GetObjectClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Bakery_Fridge_Key_C_CanApplyToTraceActor, CallFunc_ClassIsChildOf_ReturnValue) == 0x0001F0, "Member 'BP_Bakery_Fridge_Key_C_CanApplyToTraceActor::CallFunc_ClassIsChildOf_ReturnValue' has a wrong offset!");

}

