#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DoorTimesDay

#include "Basic.hpp"

#include "BP_DoorTimesDay_classes.hpp"
#include "BP_DoorTimesDay_parameters.hpp"


namespace SDK
{

// Function BP_DoorTimesDay.BP_DoorTimesDay_C.ExecuteUbergraph_BP_DoorTimesDay
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DoorTimesDay_C::ExecuteUbergraph_BP_DoorTimesDay(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorTimesDay_C", "ExecuteUbergraph_BP_DoorTimesDay");

	Params::BP_DoorTimesDay_C_ExecuteUbergraph_BP_DoorTimesDay Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DoorTimesDay.BP_DoorTimesDay_C.OnPostLoad
// (Event, Public, BlueprintEvent)

void ABP_DoorTimesDay_C::OnPostLoad()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorTimesDay_C", "OnPostLoad");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorTimesDay.BP_DoorTimesDay_C.EventRefreshGameData
// (Event, Public, BlueprintEvent)

void ABP_DoorTimesDay_C::EventRefreshGameData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorTimesDay_C", "EventRefreshGameData");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorTimesDay.BP_DoorTimesDay_C.OnLoad
// (Event, Public, BlueprintEvent)
// Parameters:
// const struct FJSON&                     JsonObject                                             (ConstParm, Parm, NoDestructor)

void ABP_DoorTimesDay_C::OnLoad(const struct FJSON& JsonObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorTimesDay_C", "OnLoad");

	Params::BP_DoorTimesDay_C_OnLoad Parms{};

	Parms.JsonObject = std::move(JsonObject);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DoorTimesDay.BP_DoorTimesDay_C.OnForceChangeDoorState
// (Event, Protected, BlueprintEvent)
// Parameters:
// EDoorState                              NewState                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_DoorTimesDay_C::OnForceChangeDoorState(EDoorState NewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorTimesDay_C", "OnForceChangeDoorState");

	Params::BP_DoorTimesDay_C_OnForceChangeDoorState Parms{};

	Parms.NewState = NewState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DoorTimesDay.BP_DoorTimesDay_C.OnChangeDoorState
// (Event, Protected, BlueprintEvent)
// Parameters:
// EDoorState                              NewState                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_DoorTimesDay_C::OnChangeDoorState(EDoorState NewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorTimesDay_C", "OnChangeDoorState");

	Params::BP_DoorTimesDay_C_OnChangeDoorState Parms{};

	Parms.NewState = NewState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DoorTimesDay.BP_DoorTimesDay_C.OnEventAction
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AActor*                           ActionMaker                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              SpecialComponent                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DoorTimesDay_C::OnEventAction(class AActor* ActionMaker, class UPrimitiveComponent* SpecialComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorTimesDay_C", "OnEventAction");

	Params::BP_DoorTimesDay_C_OnEventAction Parms{};

	Parms.ActionMaker = ActionMaker;
	Parms.SpecialComponent = SpecialComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DoorTimesDay.BP_DoorTimesDay_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DoorTimesDay_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorTimesDay_C", "ReceiveTick");

	Params::BP_DoorTimesDay_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DoorTimesDay.BP_DoorTimesDay_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_DoorTimesDay_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorTimesDay_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorTimesDay.BP_DoorTimesDay_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_DoorTimesDay_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorTimesDay_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DoorTimesDay.BP_DoorTimesDay_C.CheckDoor
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DoorTimesDay_C::CheckDoor(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorTimesDay_C", "CheckDoor");

	Params::BP_DoorTimesDay_C_CheckDoor Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DoorTimesDay.BP_DoorTimesDay_C.OnSetBucketOnDoor
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABucket**                         Bucket                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DoorTimesDay_C::OnSetBucketOnDoor(class ABucket** Bucket)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorTimesDay_C", "OnSetBucketOnDoor");

	Params::BP_DoorTimesDay_C_OnSetBucketOnDoor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Bucket != nullptr)
		*Bucket = Parms.Bucket;
}


// Function BP_DoorTimesDay.BP_DoorTimesDay_C.OnIsActionComponent
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              Component                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_DoorTimesDay_C::OnIsActionComponent(class UPrimitiveComponent* Component, bool* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorTimesDay_C", "OnIsActionComponent");

	Params::BP_DoorTimesDay_C_OnIsActionComponent Parms{};

	Parms.Component = Component;

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;
}


// Function BP_DoorTimesDay.BP_DoorTimesDay_C.OnSave
// (Event, Public, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// const struct FJSON&                     JsonObject                                             (Parm, NoDestructor)

void ABP_DoorTimesDay_C::OnSave(const struct FJSON& JsonObject) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DoorTimesDay_C", "OnSave");

	Params::BP_DoorTimesDay_C_OnSave Parms{};

	Parms.JsonObject = std::move(JsonObject);

	UObject::ProcessEvent(Func, &Parms);
}

}

