#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DoorWater

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "HelloNeighborReborn_structs.hpp"
#include "HelloNeighborReborn_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DoorWater.BP_DoorWater_C
// 0x00B0 (0x0750 - 0x06A0)
class ABP_DoorWater_C final : public ADoor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x06A0(0x0008)(Transient, DuplicateTransient)
	class UArrowComponent*                        arrow;                                             // 0x06A8(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPhysicsThrusterComponent*              PhysicsThrusterClose;                              // 0x06B0(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPhysicsThrusterComponent*              PhysicsThrusterOpen;                               // 0x06B8(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPhysicsConstraintComponent*            PhysicsConstraint1;                                // 0x06C0(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPhysicsConstraintComponent*            PhysicsConstraint;                                 // 0x06C8(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Door;                                              // 0x06D0(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               Start;                                             // 0x06D8(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	struct FRotator                               End;                                               // 0x06E4(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	float                                         Alpha;                                             // 0x06F0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Speed;                                             // 0x06F4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Timer;                                             // 0x06F8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               DoorRotationForBucket;                             // 0x06FC(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_708[0x8];                                      // 0x0708(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             BucketTransform;                                   // 0x0710(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	class ABP_WaterCube_C*                        WaterBlock;                                        // 0x0740(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_DoorWater(int32 EntryPoint);
	void OnEndDrain();
	void OnForceChangeDoorState(EDoorState NewState);
	void OnChangeDoorState(EDoorState NewState);
	void OnEventAction(class AActor* ActionMaker, class UPrimitiveComponent* SpecialComponent);
	void ReceiveTick(float DeltaSeconds);
	void ReceiveBeginPlay();
	void UserConstructionScript();
	void CheckDoor(float DeltaTime);
	void OnSetBucketOnDoor(class ABucket** Bucket);
	void OnIsActionComponent(class UPrimitiveComponent* Component, bool* Result);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_DoorWater_C">();
	}
	static class ABP_DoorWater_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DoorWater_C>();
	}
};
static_assert(alignof(ABP_DoorWater_C) == 0x000010, "Wrong alignment on ABP_DoorWater_C");
static_assert(sizeof(ABP_DoorWater_C) == 0x000750, "Wrong size on ABP_DoorWater_C");
static_assert(offsetof(ABP_DoorWater_C, UberGraphFrame) == 0x0006A0, "Member 'ABP_DoorWater_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_DoorWater_C, arrow) == 0x0006A8, "Member 'ABP_DoorWater_C::arrow' has a wrong offset!");
static_assert(offsetof(ABP_DoorWater_C, PhysicsThrusterClose) == 0x0006B0, "Member 'ABP_DoorWater_C::PhysicsThrusterClose' has a wrong offset!");
static_assert(offsetof(ABP_DoorWater_C, PhysicsThrusterOpen) == 0x0006B8, "Member 'ABP_DoorWater_C::PhysicsThrusterOpen' has a wrong offset!");
static_assert(offsetof(ABP_DoorWater_C, PhysicsConstraint1) == 0x0006C0, "Member 'ABP_DoorWater_C::PhysicsConstraint1' has a wrong offset!");
static_assert(offsetof(ABP_DoorWater_C, PhysicsConstraint) == 0x0006C8, "Member 'ABP_DoorWater_C::PhysicsConstraint' has a wrong offset!");
static_assert(offsetof(ABP_DoorWater_C, Door) == 0x0006D0, "Member 'ABP_DoorWater_C::Door' has a wrong offset!");
static_assert(offsetof(ABP_DoorWater_C, Start) == 0x0006D8, "Member 'ABP_DoorWater_C::Start' has a wrong offset!");
static_assert(offsetof(ABP_DoorWater_C, End) == 0x0006E4, "Member 'ABP_DoorWater_C::End' has a wrong offset!");
static_assert(offsetof(ABP_DoorWater_C, Alpha) == 0x0006F0, "Member 'ABP_DoorWater_C::Alpha' has a wrong offset!");
static_assert(offsetof(ABP_DoorWater_C, Speed) == 0x0006F4, "Member 'ABP_DoorWater_C::Speed' has a wrong offset!");
static_assert(offsetof(ABP_DoorWater_C, Timer) == 0x0006F8, "Member 'ABP_DoorWater_C::Timer' has a wrong offset!");
static_assert(offsetof(ABP_DoorWater_C, DoorRotationForBucket) == 0x0006FC, "Member 'ABP_DoorWater_C::DoorRotationForBucket' has a wrong offset!");
static_assert(offsetof(ABP_DoorWater_C, BucketTransform) == 0x000710, "Member 'ABP_DoorWater_C::BucketTransform' has a wrong offset!");
static_assert(offsetof(ABP_DoorWater_C, WaterBlock) == 0x000740, "Member 'ABP_DoorWater_C::WaterBlock' has a wrong offset!");

}

