#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Factory

#include "Basic.hpp"

#include "BP_Factory_classes.hpp"


namespace SDK
{

// Function BP_Factory.BP_Factory_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Factory_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Factory_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

