#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Glue

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HelloNeighbor2_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_Glue.BP_Glue_C.ExecuteUbergraph_BP_Glue
// 0x00B8 (0x00B8 - 0x0000)
struct BP_Glue_C_ExecuteUbergraph_BP_Glue final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_HitComponent;           // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor;             // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp;              // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_ComponentBoundEvent_NormalImpulse;          // 0x0020(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_ComponentBoundEvent_Hit;                    // 0x002C(0x0088)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	EMovingState                                  K2Node_CustomEvent_NewState;                       // 0x00B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Glue_C_ExecuteUbergraph_BP_Glue) == 0x000008, "Wrong alignment on BP_Glue_C_ExecuteUbergraph_BP_Glue");
static_assert(sizeof(BP_Glue_C_ExecuteUbergraph_BP_Glue) == 0x0000B8, "Wrong size on BP_Glue_C_ExecuteUbergraph_BP_Glue");
static_assert(offsetof(BP_Glue_C_ExecuteUbergraph_BP_Glue, EntryPoint) == 0x000000, "Member 'BP_Glue_C_ExecuteUbergraph_BP_Glue::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_ExecuteUbergraph_BP_Glue, K2Node_ComponentBoundEvent_HitComponent) == 0x000008, "Member 'BP_Glue_C_ExecuteUbergraph_BP_Glue::K2Node_ComponentBoundEvent_HitComponent' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_ExecuteUbergraph_BP_Glue, K2Node_ComponentBoundEvent_OtherActor) == 0x000010, "Member 'BP_Glue_C_ExecuteUbergraph_BP_Glue::K2Node_ComponentBoundEvent_OtherActor' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_ExecuteUbergraph_BP_Glue, K2Node_ComponentBoundEvent_OtherComp) == 0x000018, "Member 'BP_Glue_C_ExecuteUbergraph_BP_Glue::K2Node_ComponentBoundEvent_OtherComp' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_ExecuteUbergraph_BP_Glue, K2Node_ComponentBoundEvent_NormalImpulse) == 0x000020, "Member 'BP_Glue_C_ExecuteUbergraph_BP_Glue::K2Node_ComponentBoundEvent_NormalImpulse' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_ExecuteUbergraph_BP_Glue, K2Node_ComponentBoundEvent_Hit) == 0x00002C, "Member 'BP_Glue_C_ExecuteUbergraph_BP_Glue::K2Node_ComponentBoundEvent_Hit' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_ExecuteUbergraph_BP_Glue, K2Node_CustomEvent_NewState) == 0x0000B4, "Member 'BP_Glue_C_ExecuteUbergraph_BP_Glue::K2Node_CustomEvent_NewState' has a wrong offset!");

// Function BP_Glue.BP_Glue_C.OnDoorChageState
// 0x0001 (0x0001 - 0x0000)
struct BP_Glue_C_OnDoorChageState final
{
public:
	EMovingState                                  NewState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Glue_C_OnDoorChageState) == 0x000001, "Wrong alignment on BP_Glue_C_OnDoorChageState");
static_assert(sizeof(BP_Glue_C_OnDoorChageState) == 0x000001, "Wrong size on BP_Glue_C_OnDoorChageState");
static_assert(offsetof(BP_Glue_C_OnDoorChageState, NewState) == 0x000000, "Member 'BP_Glue_C_OnDoorChageState::NewState' has a wrong offset!");

// Function BP_Glue.BP_Glue_C.BndEvt__BP_Test_PaintCan_StaticMeshComponent_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature
// 0x00B0 (0x00B0 - 0x0000)
struct BP_Glue_C_BndEvt__BP_Test_PaintCan_StaticMeshComponent_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    HitComponent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                NormalImpulse;                                     // 0x0018(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             Hit;                                               // 0x0024(0x0088)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_Glue_C_BndEvt__BP_Test_PaintCan_StaticMeshComponent_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_Glue_C_BndEvt__BP_Test_PaintCan_StaticMeshComponent_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature");
static_assert(sizeof(BP_Glue_C_BndEvt__BP_Test_PaintCan_StaticMeshComponent_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature) == 0x0000B0, "Wrong size on BP_Glue_C_BndEvt__BP_Test_PaintCan_StaticMeshComponent_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature");
static_assert(offsetof(BP_Glue_C_BndEvt__BP_Test_PaintCan_StaticMeshComponent_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature, HitComponent) == 0x000000, "Member 'BP_Glue_C_BndEvt__BP_Test_PaintCan_StaticMeshComponent_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature::HitComponent' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_BndEvt__BP_Test_PaintCan_StaticMeshComponent_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'BP_Glue_C_BndEvt__BP_Test_PaintCan_StaticMeshComponent_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_BndEvt__BP_Test_PaintCan_StaticMeshComponent_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'BP_Glue_C_BndEvt__BP_Test_PaintCan_StaticMeshComponent_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_BndEvt__BP_Test_PaintCan_StaticMeshComponent_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature, NormalImpulse) == 0x000018, "Member 'BP_Glue_C_BndEvt__BP_Test_PaintCan_StaticMeshComponent_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature::NormalImpulse' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_BndEvt__BP_Test_PaintCan_StaticMeshComponent_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature, Hit) == 0x000024, "Member 'BP_Glue_C_BndEvt__BP_Test_PaintCan_StaticMeshComponent_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature::Hit' has a wrong offset!");

// Function BP_Glue.BP_Glue_C.OnBeginApply
// 0x0188 (0x0188 - 0x0000)
struct BP_Glue_C_OnBeginApply final
{
public:
	class ABaseCharacter*                         Character;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             Hit;                                               // 0x0008(0x0088)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class UAnimConnection*                        Connection;                                        // 0x0090(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTraceActorInfo                        TraceActorInfo;                                    // 0x0098(0x00D8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	struct FCursorInfo                            CursorInfo;                                        // 0x0170(0x0014)(Parm, OutParm, NoDestructor)
	EApplyAnswer                                  ReturnValue;                                       // 0x0184(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Glue_C_OnBeginApply) == 0x000008, "Wrong alignment on BP_Glue_C_OnBeginApply");
static_assert(sizeof(BP_Glue_C_OnBeginApply) == 0x000188, "Wrong size on BP_Glue_C_OnBeginApply");
static_assert(offsetof(BP_Glue_C_OnBeginApply, Character) == 0x000000, "Member 'BP_Glue_C_OnBeginApply::Character' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_OnBeginApply, Hit) == 0x000008, "Member 'BP_Glue_C_OnBeginApply::Hit' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_OnBeginApply, Connection) == 0x000090, "Member 'BP_Glue_C_OnBeginApply::Connection' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_OnBeginApply, TraceActorInfo) == 0x000098, "Member 'BP_Glue_C_OnBeginApply::TraceActorInfo' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_OnBeginApply, CursorInfo) == 0x000170, "Member 'BP_Glue_C_OnBeginApply::CursorInfo' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_OnBeginApply, ReturnValue) == 0x000184, "Member 'BP_Glue_C_OnBeginApply::ReturnValue' has a wrong offset!");

// Function BP_Glue.BP_Glue_C.OnUpdateApply
// 0x0180 (0x0180 - 0x0000)
struct BP_Glue_C_OnUpdateApply final
{
public:
	float                                         DeltaTime;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABaseCharacter*                         Character;                                         // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             Hit;                                               // 0x0010(0x0088)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FActorProxy                            TraceActor;                                        // 0x0098(0x00D0)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	struct FCursorInfo                            CursorInfo;                                        // 0x0168(0x0014)(Parm, OutParm, NoDestructor)
	bool                                          ReturnValue;                                       // 0x017C(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Glue_C_OnUpdateApply) == 0x000008, "Wrong alignment on BP_Glue_C_OnUpdateApply");
static_assert(sizeof(BP_Glue_C_OnUpdateApply) == 0x000180, "Wrong size on BP_Glue_C_OnUpdateApply");
static_assert(offsetof(BP_Glue_C_OnUpdateApply, DeltaTime) == 0x000000, "Member 'BP_Glue_C_OnUpdateApply::DeltaTime' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_OnUpdateApply, Character) == 0x000008, "Member 'BP_Glue_C_OnUpdateApply::Character' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_OnUpdateApply, Hit) == 0x000010, "Member 'BP_Glue_C_OnUpdateApply::Hit' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_OnUpdateApply, TraceActor) == 0x000098, "Member 'BP_Glue_C_OnUpdateApply::TraceActor' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_OnUpdateApply, CursorInfo) == 0x000168, "Member 'BP_Glue_C_OnUpdateApply::CursorInfo' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_OnUpdateApply, ReturnValue) == 0x00017C, "Member 'BP_Glue_C_OnUpdateApply::ReturnValue' has a wrong offset!");

// Function BP_Glue.BP_Glue_C.Update Visuals
// 0x0028 (0x0028 - 0x0000)
struct BP_Glue_C_Update_Visuals final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMesh*                            Temp_object_Variable;                              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UStaticMesh*                            Temp_object_Variable_1;                            // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UStaticMesh*                            K2Node_Select_Default;                             // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetStaticMesh_ReturnValue;                // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Glue_C_Update_Visuals) == 0x000008, "Wrong alignment on BP_Glue_C_Update_Visuals");
static_assert(sizeof(BP_Glue_C_Update_Visuals) == 0x000028, "Wrong size on BP_Glue_C_Update_Visuals");
static_assert(offsetof(BP_Glue_C_Update_Visuals, Temp_bool_Variable) == 0x000000, "Member 'BP_Glue_C_Update_Visuals::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_Update_Visuals, Temp_object_Variable) == 0x000008, "Member 'BP_Glue_C_Update_Visuals::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_Update_Visuals, Temp_object_Variable_1) == 0x000010, "Member 'BP_Glue_C_Update_Visuals::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_Update_Visuals, K2Node_Select_Default) == 0x000018, "Member 'BP_Glue_C_Update_Visuals::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_Update_Visuals, CallFunc_SetStaticMesh_ReturnValue) == 0x000020, "Member 'BP_Glue_C_Update_Visuals::CallFunc_SetStaticMesh_ReturnValue' has a wrong offset!");

// Function BP_Glue.BP_Glue_C.SpawnDecal
// 0x0160 (0x0160 - 0x0000)
struct BP_Glue_C_SpawnDecal final
{
public:
	struct FHitResult                             Hit;                                               // 0x0000(0x0088)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x0089(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_8A[0x2];                                       // 0x008A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x0094(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x00A0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x00AC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x00B8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C4[0x4];                                       // 0x00C4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x00D8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x00E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x00EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x00F4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0100(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotFromZ_ReturnValue;                 // 0x010C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_118[0x8];                                      // 0x0118(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0120(0x0030)(IsPlainOldData, NoDestructor)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0150(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ADecalActor*                            CallFunc_FinishSpawningActor_ReturnValue;          // 0x0158(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Glue_C_SpawnDecal) == 0x000010, "Wrong alignment on BP_Glue_C_SpawnDecal");
static_assert(sizeof(BP_Glue_C_SpawnDecal) == 0x000160, "Wrong size on BP_Glue_C_SpawnDecal");
static_assert(offsetof(BP_Glue_C_SpawnDecal, Hit) == 0x000000, "Member 'BP_Glue_C_SpawnDecal::Hit' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_SpawnDecal, CallFunc_BreakHitResult_bBlockingHit) == 0x000088, "Member 'BP_Glue_C_SpawnDecal::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_SpawnDecal, CallFunc_BreakHitResult_bInitialOverlap) == 0x000089, "Member 'BP_Glue_C_SpawnDecal::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_SpawnDecal, CallFunc_BreakHitResult_Time) == 0x00008C, "Member 'BP_Glue_C_SpawnDecal::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_SpawnDecal, CallFunc_BreakHitResult_Distance) == 0x000090, "Member 'BP_Glue_C_SpawnDecal::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_SpawnDecal, CallFunc_BreakHitResult_Location) == 0x000094, "Member 'BP_Glue_C_SpawnDecal::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_SpawnDecal, CallFunc_BreakHitResult_ImpactPoint) == 0x0000A0, "Member 'BP_Glue_C_SpawnDecal::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_SpawnDecal, CallFunc_BreakHitResult_Normal) == 0x0000AC, "Member 'BP_Glue_C_SpawnDecal::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_SpawnDecal, CallFunc_BreakHitResult_ImpactNormal) == 0x0000B8, "Member 'BP_Glue_C_SpawnDecal::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_SpawnDecal, CallFunc_BreakHitResult_PhysMat) == 0x0000C8, "Member 'BP_Glue_C_SpawnDecal::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_SpawnDecal, CallFunc_BreakHitResult_HitActor) == 0x0000D0, "Member 'BP_Glue_C_SpawnDecal::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_SpawnDecal, CallFunc_BreakHitResult_HitComponent) == 0x0000D8, "Member 'BP_Glue_C_SpawnDecal::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_SpawnDecal, CallFunc_BreakHitResult_HitBoneName) == 0x0000E0, "Member 'BP_Glue_C_SpawnDecal::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_SpawnDecal, CallFunc_BreakHitResult_HitItem) == 0x0000E8, "Member 'BP_Glue_C_SpawnDecal::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_SpawnDecal, CallFunc_BreakHitResult_ElementIndex) == 0x0000EC, "Member 'BP_Glue_C_SpawnDecal::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_SpawnDecal, CallFunc_BreakHitResult_FaceIndex) == 0x0000F0, "Member 'BP_Glue_C_SpawnDecal::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_SpawnDecal, CallFunc_BreakHitResult_TraceStart) == 0x0000F4, "Member 'BP_Glue_C_SpawnDecal::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_SpawnDecal, CallFunc_BreakHitResult_TraceEnd) == 0x000100, "Member 'BP_Glue_C_SpawnDecal::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_SpawnDecal, CallFunc_MakeRotFromZ_ReturnValue) == 0x00010C, "Member 'BP_Glue_C_SpawnDecal::CallFunc_MakeRotFromZ_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_SpawnDecal, CallFunc_MakeTransform_ReturnValue) == 0x000120, "Member 'BP_Glue_C_SpawnDecal::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_SpawnDecal, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000150, "Member 'BP_Glue_C_SpawnDecal::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_SpawnDecal, CallFunc_FinishSpawningActor_ReturnValue) == 0x000158, "Member 'BP_Glue_C_SpawnDecal::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");

// Function BP_Glue.BP_Glue_C.HasApply
// 0x0178 (0x0178 - 0x0000)
struct BP_Glue_C_HasApply final
{
public:
	const class ABaseCharacter*                   Character;                                         // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             Hit;                                               // 0x0008(0x0088)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FActorProxy                            TraceActor;                                        // 0x0090(0x00D0)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	struct FCursorInfo                            CursorInfo;                                        // 0x0160(0x0014)(Parm, OutParm, NoDestructor)
	bool                                          ReturnValue;                                       // 0x0174(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Glue_C_HasApply) == 0x000008, "Wrong alignment on BP_Glue_C_HasApply");
static_assert(sizeof(BP_Glue_C_HasApply) == 0x000178, "Wrong size on BP_Glue_C_HasApply");
static_assert(offsetof(BP_Glue_C_HasApply, Character) == 0x000000, "Member 'BP_Glue_C_HasApply::Character' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_HasApply, Hit) == 0x000008, "Member 'BP_Glue_C_HasApply::Hit' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_HasApply, TraceActor) == 0x000090, "Member 'BP_Glue_C_HasApply::TraceActor' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_HasApply, CursorInfo) == 0x000160, "Member 'BP_Glue_C_HasApply::CursorInfo' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_HasApply, ReturnValue) == 0x000174, "Member 'BP_Glue_C_HasApply::ReturnValue' has a wrong offset!");

// Function BP_Glue.BP_Glue_C.CanApplyToTraceActor
// 0x0168 (0x0168 - 0x0000)
struct BP_Glue_C_CanApplyToTraceActor final
{
public:
	const class ABaseCharacter*                   Character;                                         // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FActorProxy                            HandActor;                                         // 0x0008(0x00D0)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	struct FHitResult                             Hit;                                               // 0x00D8(0x0088)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          ReturnValue;                                       // 0x0160(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Glue_C_CanApplyToTraceActor) == 0x000008, "Wrong alignment on BP_Glue_C_CanApplyToTraceActor");
static_assert(sizeof(BP_Glue_C_CanApplyToTraceActor) == 0x000168, "Wrong size on BP_Glue_C_CanApplyToTraceActor");
static_assert(offsetof(BP_Glue_C_CanApplyToTraceActor, Character) == 0x000000, "Member 'BP_Glue_C_CanApplyToTraceActor::Character' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_CanApplyToTraceActor, HandActor) == 0x000008, "Member 'BP_Glue_C_CanApplyToTraceActor::HandActor' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_CanApplyToTraceActor, Hit) == 0x0000D8, "Member 'BP_Glue_C_CanApplyToTraceActor::Hit' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_CanApplyToTraceActor, ReturnValue) == 0x000160, "Member 'BP_Glue_C_CanApplyToTraceActor::ReturnValue' has a wrong offset!");

// Function BP_Glue.BP_Glue_C.CanPickUp
// 0x00A8 (0x00A8 - 0x0000)
struct BP_Glue_C_CanPickUp final
{
public:
	const class ABaseCharacter*                   Character;                                         // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             Hit;                                               // 0x0008(0x0088)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FCursorInfo                            CursorInfo;                                        // 0x0090(0x0014)(Parm, OutParm, NoDestructor)
	bool                                          ReturnValue;                                       // 0x00A4(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Glue_C_CanPickUp) == 0x000008, "Wrong alignment on BP_Glue_C_CanPickUp");
static_assert(sizeof(BP_Glue_C_CanPickUp) == 0x0000A8, "Wrong size on BP_Glue_C_CanPickUp");
static_assert(offsetof(BP_Glue_C_CanPickUp, Character) == 0x000000, "Member 'BP_Glue_C_CanPickUp::Character' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_CanPickUp, Hit) == 0x000008, "Member 'BP_Glue_C_CanPickUp::Hit' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_CanPickUp, CursorInfo) == 0x000090, "Member 'BP_Glue_C_CanPickUp::CursorInfo' has a wrong offset!");
static_assert(offsetof(BP_Glue_C_CanPickUp, ReturnValue) == 0x0000A4, "Member 'BP_Glue_C_CanPickUp::ReturnValue' has a wrong offset!");

}

