#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GunScanner

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_GunScanner.BP_GunScanner_C.ExecuteUbergraph_BP_GunScanner
// 0x0230 (0x0230 - 0x0000)
struct BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable2;                   // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue2;                  // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable3;                   // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue3;                  // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable2;                    // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable4;                   // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable5;                   // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue4;                  // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue5;                  // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_True_if_break_was_hit_Variable2;         // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3D[0x3];                                       // 0x003D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable6;                   // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue6;                  // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue2;                 // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x3];                                       // 0x0049(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable3;                    // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent2;   // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor2;            // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp2;             // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex2;        // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep;             // 0x006C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6D[0x3];                                       // 0x006D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult;            // 0x0070(0x0088)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class AHuman*                                 K2Node_DynamicCast_AsHuman;                        // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_101[0x3];                                      // 0x0101(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0104(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UInventory*                             CallFunc_GetInventory_ReturnValue;                 // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0110(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_111[0x7];                                      // 0x0111(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AFlatActor*                             CallFunc_GetCurrentObject_ReturnValue;             // 0x0118(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AFlatActor*>                     CallFunc_GetActorsInSlots_ReturnValue;             // 0x0120(0x0010)(ConstParm, ZeroConstructor, ReferenceParm)
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue;               // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue2;                // 0x0138(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue2;                 // 0x013C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_13D[0x3];                                      // 0x013D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_AddUnique_ReturnValue;              // 0x0140(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable4;                    // 0x0144(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue3;                // 0x0148(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14C[0x4];                                      // 0x014C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_Array_Get_Item;                           // 0x0150(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue3;                 // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0159(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15A[0x6];                                      // 0x015A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent;    // 0x0160(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor;             // 0x0168(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp;              // 0x0170(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex;         // 0x0178(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue4;                // 0x017C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0180(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0181(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_182[0x6];                                      // 0x0182(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AHuman*                                 K2Node_DynamicCast_AsHuman2;                       // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess2;                      // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_191[0x3];                                      // 0x0191(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable5;                    // 0x0194(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UInventory*                             CallFunc_GetInventory_ReturnValue2;                // 0x0198(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 CallFunc_Array_Get_Item2;                          // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AFlatActor*>                     CallFunc_GetActorsInSlots_ReturnValue2;            // 0x01A8(0x0010)(ConstParm, ZeroConstructor, ReferenceParm)
	bool                                          CallFunc_EqualEqual_ClassClass_ReturnValue;        // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1B9[0x7];                                      // 0x01B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AFlatActor*                             CallFunc_Array_Get_Item3;                          // 0x01C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x01C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1C9[0x3];                                      // 0x01C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue5;                // 0x01CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFlatActor*                             CallFunc_GetCurrentObject_ReturnValue2;            // 0x01D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue4;                 // 0x01D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x01D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1DA[0x6];                                      // 0x01DA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_Array_Get_Item4;                          // 0x01E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue6;                // 0x01E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue5;                 // 0x01EC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsOverlappingActor_ReturnValue;           // 0x01ED(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1EE[0x2];                                      // 0x01EE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue7;                // 0x01F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue2;                  // 0x01F4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue6;                 // 0x01F5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue3;                  // 0x01F6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1F7[0x1];                                      // 0x01F7(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_Array_Get_Item5;                          // 0x01F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue2;     // 0x0200(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue4;                  // 0x0201(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_202[0x2];                                      // 0x0202(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue8;                // 0x0204(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue5;                  // 0x0208(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0209(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_20A[0x2];                                      // 0x020A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable6;                    // 0x020C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFlatActor*                             CallFunc_Array_Get_Item6;                          // 0x0210(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_AddUnique_ReturnValue2;             // 0x0218(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21C[0x4];                                      // 0x021C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue2;              // 0x0220(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue2;                     // 0x0228(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ClassClass_ReturnValue2;       // 0x0229(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue2;       // 0x022A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue6;                  // 0x022B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner) == 0x000008, "Wrong alignment on BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner");
static_assert(sizeof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner) == 0x000230, "Wrong size on BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, EntryPoint) == 0x000000, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, Temp_int_Array_Index_Variable) == 0x00000C, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, Temp_int_Loop_Counter_Variable2) == 0x000010, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::Temp_int_Loop_Counter_Variable2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Add_IntInt_ReturnValue2) == 0x000014, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Add_IntInt_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, Temp_bool_True_if_break_was_hit_Variable) == 0x000018, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::Temp_bool_True_if_break_was_hit_Variable' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, Temp_int_Loop_Counter_Variable3) == 0x00001C, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::Temp_int_Loop_Counter_Variable3' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Add_IntInt_ReturnValue3) == 0x000020, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Add_IntInt_ReturnValue3' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Not_PreBool_ReturnValue) == 0x000024, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, Temp_int_Array_Index_Variable2) == 0x000028, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::Temp_int_Array_Index_Variable2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, Temp_int_Loop_Counter_Variable4) == 0x00002C, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::Temp_int_Loop_Counter_Variable4' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, Temp_int_Loop_Counter_Variable5) == 0x000030, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::Temp_int_Loop_Counter_Variable5' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Add_IntInt_ReturnValue4) == 0x000034, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Add_IntInt_ReturnValue4' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Add_IntInt_ReturnValue5) == 0x000038, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Add_IntInt_ReturnValue5' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, Temp_bool_True_if_break_was_hit_Variable2) == 0x00003C, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::Temp_bool_True_if_break_was_hit_Variable2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, Temp_int_Loop_Counter_Variable6) == 0x000040, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::Temp_int_Loop_Counter_Variable6' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Add_IntInt_ReturnValue6) == 0x000044, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Add_IntInt_ReturnValue6' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Not_PreBool_ReturnValue2) == 0x000048, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Not_PreBool_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, Temp_int_Array_Index_Variable3) == 0x00004C, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::Temp_int_Array_Index_Variable3' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, K2Node_ComponentBoundEvent_OverlappedComponent2) == 0x000050, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::K2Node_ComponentBoundEvent_OverlappedComponent2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, K2Node_ComponentBoundEvent_OtherActor2) == 0x000058, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::K2Node_ComponentBoundEvent_OtherActor2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, K2Node_ComponentBoundEvent_OtherComp2) == 0x000060, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::K2Node_ComponentBoundEvent_OtherComp2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, K2Node_ComponentBoundEvent_OtherBodyIndex2) == 0x000068, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::K2Node_ComponentBoundEvent_OtherBodyIndex2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, K2Node_ComponentBoundEvent_bFromSweep) == 0x00006C, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::K2Node_ComponentBoundEvent_bFromSweep' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, K2Node_ComponentBoundEvent_SweepResult) == 0x000070, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::K2Node_ComponentBoundEvent_SweepResult' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, K2Node_DynamicCast_AsHuman) == 0x0000F8, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::K2Node_DynamicCast_AsHuman' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, K2Node_DynamicCast_bSuccess) == 0x000100, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Array_Length_ReturnValue) == 0x000104, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_GetInventory_ReturnValue) == 0x000108, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_GetInventory_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Less_IntInt_ReturnValue) == 0x000110, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_GetCurrentObject_ReturnValue) == 0x000118, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_GetCurrentObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_GetActorsInSlots_ReturnValue) == 0x000120, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_GetActorsInSlots_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_GetObjectClass_ReturnValue) == 0x000130, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_GetObjectClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Array_Length_ReturnValue2) == 0x000138, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Array_Length_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Less_IntInt_ReturnValue2) == 0x00013C, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Less_IntInt_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Array_AddUnique_ReturnValue) == 0x000140, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Array_AddUnique_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, Temp_int_Array_Index_Variable4) == 0x000144, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::Temp_int_Array_Index_Variable4' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Array_Length_ReturnValue3) == 0x000148, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Array_Length_ReturnValue3' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Array_Get_Item) == 0x000150, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Less_IntInt_ReturnValue3) == 0x000158, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Less_IntInt_ReturnValue3' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_BooleanAND_ReturnValue) == 0x000159, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, K2Node_ComponentBoundEvent_OverlappedComponent) == 0x000160, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::K2Node_ComponentBoundEvent_OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, K2Node_ComponentBoundEvent_OtherActor) == 0x000168, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::K2Node_ComponentBoundEvent_OtherActor' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, K2Node_ComponentBoundEvent_OtherComp) == 0x000170, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::K2Node_ComponentBoundEvent_OtherComp' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, K2Node_ComponentBoundEvent_OtherBodyIndex) == 0x000178, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::K2Node_ComponentBoundEvent_OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Array_Length_ReturnValue4) == 0x00017C, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Array_Length_ReturnValue4' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000180, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Greater_IntInt_ReturnValue) == 0x000181, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, K2Node_DynamicCast_AsHuman2) == 0x000188, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::K2Node_DynamicCast_AsHuman2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, K2Node_DynamicCast_bSuccess2) == 0x000190, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::K2Node_DynamicCast_bSuccess2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, Temp_int_Array_Index_Variable5) == 0x000194, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::Temp_int_Array_Index_Variable5' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_GetInventory_ReturnValue2) == 0x000198, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_GetInventory_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Array_Get_Item2) == 0x0001A0, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Array_Get_Item2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_GetActorsInSlots_ReturnValue2) == 0x0001A8, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_GetActorsInSlots_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_EqualEqual_ClassClass_ReturnValue) == 0x0001B8, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_EqualEqual_ClassClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Array_Get_Item3) == 0x0001C0, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Array_Get_Item3' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_IsValid_ReturnValue) == 0x0001C8, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Array_Length_ReturnValue5) == 0x0001CC, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Array_Length_ReturnValue5' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_GetCurrentObject_ReturnValue2) == 0x0001D0, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_GetCurrentObject_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Less_IntInt_ReturnValue4) == 0x0001D8, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Less_IntInt_ReturnValue4' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_NotEqual_ObjectObject_ReturnValue) == 0x0001D9, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_NotEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Array_Get_Item4) == 0x0001E0, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Array_Get_Item4' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Array_Length_ReturnValue6) == 0x0001E8, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Array_Length_ReturnValue6' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Less_IntInt_ReturnValue5) == 0x0001EC, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Less_IntInt_ReturnValue5' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_IsOverlappingActor_ReturnValue) == 0x0001ED, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_IsOverlappingActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Array_Length_ReturnValue7) == 0x0001F0, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Array_Length_ReturnValue7' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_BooleanAND_ReturnValue2) == 0x0001F4, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_BooleanAND_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Less_IntInt_ReturnValue6) == 0x0001F5, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Less_IntInt_ReturnValue6' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_BooleanAND_ReturnValue3) == 0x0001F6, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_BooleanAND_ReturnValue3' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Array_Get_Item5) == 0x0001F8, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Array_Get_Item5' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_EqualEqual_ObjectObject_ReturnValue2) == 0x000200, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_EqualEqual_ObjectObject_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_BooleanAND_ReturnValue4) == 0x000201, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_BooleanAND_ReturnValue4' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Array_Length_ReturnValue8) == 0x000204, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Array_Length_ReturnValue8' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_BooleanAND_ReturnValue5) == 0x000208, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_BooleanAND_ReturnValue5' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000209, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, Temp_int_Array_Index_Variable6) == 0x00020C, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::Temp_int_Array_Index_Variable6' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Array_Get_Item6) == 0x000210, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Array_Get_Item6' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_Array_AddUnique_ReturnValue2) == 0x000218, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_Array_AddUnique_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_GetObjectClass_ReturnValue2) == 0x000220, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_GetObjectClass_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_IsValid_ReturnValue2) == 0x000228, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_IsValid_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_EqualEqual_ClassClass_ReturnValue2) == 0x000229, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_EqualEqual_ClassClass_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_NotEqual_ObjectObject_ReturnValue2) == 0x00022A, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_NotEqual_ObjectObject_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner, CallFunc_BooleanAND_ReturnValue6) == 0x00022B, "Member 'BP_GunScanner_C_ExecuteUbergraph_BP_GunScanner::CallFunc_BooleanAND_ReturnValue6' has a wrong offset!");

// Function BP_GunScanner.BP_GunScanner_C.BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature
// 0x0020 (0x0020 - 0x0000)
struct BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature");
static_assert(sizeof(BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature) == 0x000020, "Wrong size on BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature");
static_assert(offsetof(BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");

// Function BP_GunScanner.BP_GunScanner_C.BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// 0x00A8 (0x00A8 - 0x0000)
struct BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature) == 0x0000A8, "Wrong size on BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00001C, "Member 'BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000020, "Member 'BP_GunScanner_C_BndEvt__Scanner_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

}

