#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HidingStoreRoom

#include "Basic.hpp"

#include "BP_HidingStoreRoom_classes.hpp"
#include "BP_HidingStoreRoom_parameters.hpp"


namespace SDK
{

// Function BP_HidingStoreRoom.BP_HidingStoreRoom_C.ExecuteUbergraph_BP_HidingStoreRoom
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HidingStoreRoom_C::ExecuteUbergraph_BP_HidingStoreRoom(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HidingStoreRoom_C", "ExecuteUbergraph_BP_HidingStoreRoom");

	Params::BP_HidingStoreRoom_C_ExecuteUbergraph_BP_HidingStoreRoom Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HidingStoreRoom.BP_HidingStoreRoom_C.TurnOffLights
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EHidingState                            NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HidingStoreRoom_C::TurnOffLights(EHidingState NewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HidingStoreRoom_C", "TurnOffLights");

	Params::BP_HidingStoreRoom_C_TurnOffLights Parms{};

	Parms.NewState = NewState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HidingStoreRoom.BP_HidingStoreRoom_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_HidingStoreRoom_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HidingStoreRoom_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

