#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MillButtonClear

#include "Basic.hpp"

#include "HelloNeighborReborn_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_MillButtonClear.BP_MillButtonClear_C.ExecuteUbergraph_BP_MillButtonClear
// 0x00E8 (0x00E8 - 0x0000)
struct BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_ActionMaker;                          // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_Event_SpecialComponent;                     // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EMovingState                                  CallFunc_GetMovingState_ReturnValue;               // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x001A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EMovingState                                  CallFunc_GetMovingState_ReturnValue2;              // 0x001B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchEnum2_CmpSuccess;                     // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue2;         // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue3;         // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue2;              // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_Array_Get_Item;                           // 0x0034(0x000C)(IsPlainOldData, NoDestructor)
	struct FRotator                               CallFunc_Array_Get_Item2;                          // 0x0040(0x000C)(IsPlainOldData, NoDestructor)
	struct FRotator                               CallFunc_RLerp_ReturnValue;                        // 0x004C(0x000C)(IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_SetRelativeRotation_SweepHitResult;    // 0x0058(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue;      // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue;         // 0x00E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear) == 0x000008, "Wrong alignment on BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear");
static_assert(sizeof(BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear) == 0x0000E8, "Wrong size on BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear");
static_assert(offsetof(BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear, EntryPoint) == 0x000000, "Member 'BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear, K2Node_Event_DeltaSeconds) == 0x000004, "Member 'BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear, K2Node_Event_ActionMaker) == 0x000008, "Member 'BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear::K2Node_Event_ActionMaker' has a wrong offset!");
static_assert(offsetof(BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear, K2Node_Event_SpecialComponent) == 0x000010, "Member 'BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear::K2Node_Event_SpecialComponent' has a wrong offset!");
static_assert(offsetof(BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000018, "Member 'BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear, CallFunc_GetMovingState_ReturnValue) == 0x000019, "Member 'BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear::CallFunc_GetMovingState_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear, K2Node_SwitchEnum_CmpSuccess) == 0x00001A, "Member 'BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear, CallFunc_GetMovingState_ReturnValue2) == 0x00001B, "Member 'BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear::CallFunc_GetMovingState_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear, K2Node_SwitchEnum2_CmpSuccess) == 0x00001C, "Member 'BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear::K2Node_SwitchEnum2_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x000020, "Member 'BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear, CallFunc_Multiply_FloatFloat_ReturnValue2) == 0x000024, "Member 'BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear::CallFunc_Multiply_FloatFloat_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear, CallFunc_Multiply_FloatFloat_ReturnValue3) == 0x000028, "Member 'BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear::CallFunc_Multiply_FloatFloat_ReturnValue3' has a wrong offset!");
static_assert(offsetof(BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear, CallFunc_Add_FloatFloat_ReturnValue) == 0x00002C, "Member 'BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear, CallFunc_Add_FloatFloat_ReturnValue2) == 0x000030, "Member 'BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear::CallFunc_Add_FloatFloat_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear, CallFunc_Array_Get_Item) == 0x000034, "Member 'BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear, CallFunc_Array_Get_Item2) == 0x000040, "Member 'BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear::CallFunc_Array_Get_Item2' has a wrong offset!");
static_assert(offsetof(BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear, CallFunc_RLerp_ReturnValue) == 0x00004C, "Member 'BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear::CallFunc_RLerp_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear, CallFunc_K2_SetRelativeRotation_SweepHitResult) == 0x000058, "Member 'BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear::CallFunc_K2_SetRelativeRotation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear, CallFunc_GreaterEqual_FloatFloat_ReturnValue) == 0x0000E0, "Member 'BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear::CallFunc_GreaterEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear, CallFunc_LessEqual_FloatFloat_ReturnValue) == 0x0000E1, "Member 'BP_MillButtonClear_C_ExecuteUbergraph_BP_MillButtonClear::CallFunc_LessEqual_FloatFloat_ReturnValue' has a wrong offset!");

// Function BP_MillButtonClear.BP_MillButtonClear_C.OnEventAction
// 0x0010 (0x0010 - 0x0000)
struct BP_MillButtonClear_C_OnEventAction final
{
public:
	class AActor*                                 ActionMaker;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    SpecialComponent;                                  // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MillButtonClear_C_OnEventAction) == 0x000008, "Wrong alignment on BP_MillButtonClear_C_OnEventAction");
static_assert(sizeof(BP_MillButtonClear_C_OnEventAction) == 0x000010, "Wrong size on BP_MillButtonClear_C_OnEventAction");
static_assert(offsetof(BP_MillButtonClear_C_OnEventAction, ActionMaker) == 0x000000, "Member 'BP_MillButtonClear_C_OnEventAction::ActionMaker' has a wrong offset!");
static_assert(offsetof(BP_MillButtonClear_C_OnEventAction, SpecialComponent) == 0x000008, "Member 'BP_MillButtonClear_C_OnEventAction::SpecialComponent' has a wrong offset!");

// Function BP_MillButtonClear.BP_MillButtonClear_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_MillButtonClear_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MillButtonClear_C_ReceiveTick) == 0x000004, "Wrong alignment on BP_MillButtonClear_C_ReceiveTick");
static_assert(sizeof(BP_MillButtonClear_C_ReceiveTick) == 0x000004, "Wrong size on BP_MillButtonClear_C_ReceiveTick");
static_assert(offsetof(BP_MillButtonClear_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BP_MillButtonClear_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function BP_MillButtonClear.BP_MillButtonClear_C.OnIsActionComponent
// 0x0010 (0x0010 - 0x0000)
struct BP_MillButtonClear_C_OnIsActionComponent final
{
public:
	class UPrimitiveComponent*                    Component;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Result;                                            // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_MillButtonClear_C_OnIsActionComponent) == 0x000008, "Wrong alignment on BP_MillButtonClear_C_OnIsActionComponent");
static_assert(sizeof(BP_MillButtonClear_C_OnIsActionComponent) == 0x000010, "Wrong size on BP_MillButtonClear_C_OnIsActionComponent");
static_assert(offsetof(BP_MillButtonClear_C_OnIsActionComponent, Component) == 0x000000, "Member 'BP_MillButtonClear_C_OnIsActionComponent::Component' has a wrong offset!");
static_assert(offsetof(BP_MillButtonClear_C_OnIsActionComponent, Result) == 0x000008, "Member 'BP_MillButtonClear_C_OnIsActionComponent::Result' has a wrong offset!");
static_assert(offsetof(BP_MillButtonClear_C_OnIsActionComponent, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000009, "Member 'BP_MillButtonClear_C_OnIsActionComponent::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");

}

