#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MillTube

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_MillTube.BP_MillTube_C.ExecuteUbergraph_BP_MillTube
// 0x0110 (0x0110 - 0x0000)
struct BP_MillTube_C_ExecuteUbergraph_BP_MillTube final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue;      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0014(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue2;     // 0x0020(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Conv_FloatToVector_ReturnValue;           // 0x002C(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_VLerp_ReturnValue;                        // 0x0038(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44[0xC];                                       // 0x0044(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0050(0x0030)(IsPlainOldData, NoDestructor)
	struct FHitResult                             CallFunc_K2_SetActorTransform_SweepHitResult;      // 0x0080(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_K2_SetActorTransform_ReturnValue;         // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_MillTube_C_ExecuteUbergraph_BP_MillTube) == 0x000010, "Wrong alignment on BP_MillTube_C_ExecuteUbergraph_BP_MillTube");
static_assert(sizeof(BP_MillTube_C_ExecuteUbergraph_BP_MillTube) == 0x000110, "Wrong size on BP_MillTube_C_ExecuteUbergraph_BP_MillTube");
static_assert(offsetof(BP_MillTube_C_ExecuteUbergraph_BP_MillTube, EntryPoint) == 0x000000, "Member 'BP_MillTube_C_ExecuteUbergraph_BP_MillTube::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_MillTube_C_ExecuteUbergraph_BP_MillTube, CallFunc_GreaterEqual_FloatFloat_ReturnValue) == 0x000004, "Member 'BP_MillTube_C_ExecuteUbergraph_BP_MillTube::CallFunc_GreaterEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MillTube_C_ExecuteUbergraph_BP_MillTube, K2Node_Event_DeltaSeconds) == 0x000008, "Member 'BP_MillTube_C_ExecuteUbergraph_BP_MillTube::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BP_MillTube_C_ExecuteUbergraph_BP_MillTube, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x00000C, "Member 'BP_MillTube_C_ExecuteUbergraph_BP_MillTube::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MillTube_C_ExecuteUbergraph_BP_MillTube, CallFunc_Add_FloatFloat_ReturnValue) == 0x000010, "Member 'BP_MillTube_C_ExecuteUbergraph_BP_MillTube::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MillTube_C_ExecuteUbergraph_BP_MillTube, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000014, "Member 'BP_MillTube_C_ExecuteUbergraph_BP_MillTube::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MillTube_C_ExecuteUbergraph_BP_MillTube, CallFunc_K2_GetComponentLocation_ReturnValue2) == 0x000020, "Member 'BP_MillTube_C_ExecuteUbergraph_BP_MillTube::CallFunc_K2_GetComponentLocation_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_MillTube_C_ExecuteUbergraph_BP_MillTube, CallFunc_Conv_FloatToVector_ReturnValue) == 0x00002C, "Member 'BP_MillTube_C_ExecuteUbergraph_BP_MillTube::CallFunc_Conv_FloatToVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MillTube_C_ExecuteUbergraph_BP_MillTube, CallFunc_VLerp_ReturnValue) == 0x000038, "Member 'BP_MillTube_C_ExecuteUbergraph_BP_MillTube::CallFunc_VLerp_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MillTube_C_ExecuteUbergraph_BP_MillTube, CallFunc_MakeTransform_ReturnValue) == 0x000050, "Member 'BP_MillTube_C_ExecuteUbergraph_BP_MillTube::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MillTube_C_ExecuteUbergraph_BP_MillTube, CallFunc_K2_SetActorTransform_SweepHitResult) == 0x000080, "Member 'BP_MillTube_C_ExecuteUbergraph_BP_MillTube::CallFunc_K2_SetActorTransform_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_MillTube_C_ExecuteUbergraph_BP_MillTube, CallFunc_K2_SetActorTransform_ReturnValue) == 0x000108, "Member 'BP_MillTube_C_ExecuteUbergraph_BP_MillTube::CallFunc_K2_SetActorTransform_ReturnValue' has a wrong offset!");

// Function BP_MillTube.BP_MillTube_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_MillTube_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MillTube_C_ReceiveTick) == 0x000004, "Wrong alignment on BP_MillTube_C_ReceiveTick");
static_assert(sizeof(BP_MillTube_C_ReceiveTick) == 0x000004, "Wrong size on BP_MillTube_C_ReceiveTick");
static_assert(offsetof(BP_MillTube_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BP_MillTube_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function BP_MillTube.BP_MillTube_C.Push
// 0x0008 (0x0008 - 0x0000)
struct BP_MillTube_C_Push final
{
public:
	class AFlatActor*                             Actor;                                             // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MillTube_C_Push) == 0x000008, "Wrong alignment on BP_MillTube_C_Push");
static_assert(sizeof(BP_MillTube_C_Push) == 0x000008, "Wrong size on BP_MillTube_C_Push");
static_assert(offsetof(BP_MillTube_C_Push, Actor) == 0x000000, "Member 'BP_MillTube_C_Push::Actor' has a wrong offset!");

// Function BP_MillTube.BP_MillTube_C.IsFree
// 0x0003 (0x0003 - 0x0000)
struct BP_MillTube_C_IsFree final
{
public:
	bool                                          Free;                                              // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_MillTube_C_IsFree) == 0x000001, "Wrong alignment on BP_MillTube_C_IsFree");
static_assert(sizeof(BP_MillTube_C_IsFree) == 0x000003, "Wrong size on BP_MillTube_C_IsFree");
static_assert(offsetof(BP_MillTube_C_IsFree, Free) == 0x000000, "Member 'BP_MillTube_C_IsFree::Free' has a wrong offset!");
static_assert(offsetof(BP_MillTube_C_IsFree, CallFunc_IsValid_ReturnValue) == 0x000001, "Member 'BP_MillTube_C_IsFree::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MillTube_C_IsFree, CallFunc_Not_PreBool_ReturnValue) == 0x000002, "Member 'BP_MillTube_C_IsFree::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");

}

