#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MobileSpotlight

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HelloNeighbor2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MobileSpotlight.BP_MobileSpotlight_C
// 0x0040 (0x0A80 - 0x0A40)
class ABP_MobileSpotlight_C final : public AMobileSpotlight
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0A40(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAudioComponent*                        SC_Electricity_Hum_High_End_Cue;                   // 0x0A48(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        SC_Electricity_Hum_High_Loop_Cue;                  // 0x0A50(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        SC_Electricity_Hum_High_Start_Cue;                 // 0x0A58(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        SC_Box_Unpacking_Loop_Cue;                         // 0x0A60(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          InletLocator1;                                     // 0x0A68(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          HasInlets;                                         // 0x0A70(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_BP_MobileSpotlight(int32 EntryPoint);
	void OnChangeLights(bool IsOn);
	void BndEvt__BaseMeshComponent_K2Node_ComponentBoundEvent_2_OnEmpty__DelegateSignature();
	void BndEvt__BaseMeshComponent_K2Node_ComponentBoundEvent_1_OnEmpty__DelegateSignature(bool PackingComplete);
	void BndEvt__BaseMeshComponent_K2Node_ComponentBoundEvent_0_OnEmpty__DelegateSignature();
	void ReceiveBeginPlay();
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MobileSpotlight_C">();
	}
	static class ABP_MobileSpotlight_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MobileSpotlight_C>();
	}
};
static_assert(alignof(ABP_MobileSpotlight_C) == 0x000010, "Wrong alignment on ABP_MobileSpotlight_C");
static_assert(sizeof(ABP_MobileSpotlight_C) == 0x000A80, "Wrong size on ABP_MobileSpotlight_C");
static_assert(offsetof(ABP_MobileSpotlight_C, UberGraphFrame) == 0x000A40, "Member 'ABP_MobileSpotlight_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_MobileSpotlight_C, SC_Electricity_Hum_High_End_Cue) == 0x000A48, "Member 'ABP_MobileSpotlight_C::SC_Electricity_Hum_High_End_Cue' has a wrong offset!");
static_assert(offsetof(ABP_MobileSpotlight_C, SC_Electricity_Hum_High_Loop_Cue) == 0x000A50, "Member 'ABP_MobileSpotlight_C::SC_Electricity_Hum_High_Loop_Cue' has a wrong offset!");
static_assert(offsetof(ABP_MobileSpotlight_C, SC_Electricity_Hum_High_Start_Cue) == 0x000A58, "Member 'ABP_MobileSpotlight_C::SC_Electricity_Hum_High_Start_Cue' has a wrong offset!");
static_assert(offsetof(ABP_MobileSpotlight_C, SC_Box_Unpacking_Loop_Cue) == 0x000A60, "Member 'ABP_MobileSpotlight_C::SC_Box_Unpacking_Loop_Cue' has a wrong offset!");
static_assert(offsetof(ABP_MobileSpotlight_C, InletLocator1) == 0x000A68, "Member 'ABP_MobileSpotlight_C::InletLocator1' has a wrong offset!");
static_assert(offsetof(ABP_MobileSpotlight_C, HasInlets) == 0x000A70, "Member 'ABP_MobileSpotlight_C::HasInlets' has a wrong offset!");

}

