#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MoveOutDoor_CompositeTask

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HelloNeighbor2_classes.hpp"
#include "AIModule_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MoveOutDoor_CompositeTask.BP_MoveOutDoor_CompositeTask_C
// 0x0020 (0x0090 - 0x0070)
class UBP_MoveOutDoor_CompositeTask_C final : public UCompositeTask_MoveByNavLink
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0070(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ABaseDoor*                              Door;                                              // 0x0078(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	int32                                         CountHit;                                          // 0x0080(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_84[0x4];                                       // 0x0084(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UCharacterStatus>           Status_Class;                                      // 0x0088(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_MoveOutDoor_CompositeTask(int32 EntryPoint);
	void SetSpecificBotSettings(const class UCompositeTaskSettings* Settings);
	void OnHitRecoilActor(const class UPushingComponent* PushingComponent, class AActor* Actor);
	void OnEndRun(EBTNodeResult Result);
	bool OnBeginRun();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MoveOutDoor_CompositeTask_C">();
	}
	static class UBP_MoveOutDoor_CompositeTask_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MoveOutDoor_CompositeTask_C>();
	}
};
static_assert(alignof(UBP_MoveOutDoor_CompositeTask_C) == 0x000008, "Wrong alignment on UBP_MoveOutDoor_CompositeTask_C");
static_assert(sizeof(UBP_MoveOutDoor_CompositeTask_C) == 0x000090, "Wrong size on UBP_MoveOutDoor_CompositeTask_C");
static_assert(offsetof(UBP_MoveOutDoor_CompositeTask_C, UberGraphFrame) == 0x000070, "Member 'UBP_MoveOutDoor_CompositeTask_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_MoveOutDoor_CompositeTask_C, Door) == 0x000078, "Member 'UBP_MoveOutDoor_CompositeTask_C::Door' has a wrong offset!");
static_assert(offsetof(UBP_MoveOutDoor_CompositeTask_C, CountHit) == 0x000080, "Member 'UBP_MoveOutDoor_CompositeTask_C::CountHit' has a wrong offset!");
static_assert(offsetof(UBP_MoveOutDoor_CompositeTask_C, Status_Class) == 0x000088, "Member 'UBP_MoveOutDoor_CompositeTask_C::Status_Class' has a wrong offset!");

}

