#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MillMagnet

#include "Basic.hpp"

#include "BP_MillMagnet_classes.hpp"
#include "BP_MillMagnet_parameters.hpp"


namespace SDK
{

// Function BP_MillMagnet.BP_MillMagnet_C.ExecuteUbergraph_BP_MillMagnet
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MillMagnet_C::ExecuteUbergraph_BP_MillMagnet(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MillMagnet_C", "ExecuteUbergraph_BP_MillMagnet");

	Params::BP_MillMagnet_C_ExecuteUbergraph_BP_MillMagnet Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MillMagnet.BP_MillMagnet_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_MillMagnet_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MillMagnet_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MillMagnet.BP_MillMagnet_C.OnChangeState
// (Event, Protected, BlueprintEvent)
// Parameters:
// ETumblerState                           NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MillMagnet_C::OnChangeState(ETumblerState NewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MillMagnet_C", "OnChangeState");

	Params::BP_MillMagnet_C_OnChangeState Parms{};

	Parms.NewState = NewState;

	UObject::ProcessEvent(Func, &Parms);
}

}

