#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PuddleGlue

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HelloNeighborReborn_structs.hpp"
#include "HelloNeighborReborn_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PuddleGlue.BP_PuddleGlue_C
// 0x0018 (0x04E8 - 0x04D0)
class ABP_PuddleGlue_C final : public AGlue
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04D0(0x0008)(Transient, DuplicateTransient)
	class UBoxComponent*                          Box;                                               // 0x04D8(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         SpeedScale;                                        // 0x04E0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Delay;                                             // 0x04E4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_PuddleGlue(int32 EntryPoint);
	void ReceiveTick(float DeltaSeconds);
	void BndEvt__Box_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
	void BndEvt__Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PuddleGlue_C">();
	}
	static class ABP_PuddleGlue_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PuddleGlue_C>();
	}
};
static_assert(alignof(ABP_PuddleGlue_C) == 0x000008, "Wrong alignment on ABP_PuddleGlue_C");
static_assert(sizeof(ABP_PuddleGlue_C) == 0x0004E8, "Wrong size on ABP_PuddleGlue_C");
static_assert(offsetof(ABP_PuddleGlue_C, UberGraphFrame) == 0x0004D0, "Member 'ABP_PuddleGlue_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_PuddleGlue_C, Box) == 0x0004D8, "Member 'ABP_PuddleGlue_C::Box' has a wrong offset!");
static_assert(offsetof(ABP_PuddleGlue_C, SpeedScale) == 0x0004E0, "Member 'ABP_PuddleGlue_C::SpeedScale' has a wrong offset!");
static_assert(offsetof(ABP_PuddleGlue_C, Delay) == 0x0004E4, "Member 'ABP_PuddleGlue_C::Delay' has a wrong offset!");

}

