#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Proxy

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Proxy.BP_Proxy_C
// 0x0010 (0x0328 - 0x0318)
class ABP_Proxy_C final : public AActor
{
public:
	class UNavLinkerComponent*                    NavLinker;                                         // 0x0318(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBillboardComponent*                    Billboard;                                         // 0x0320(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Proxy_C">();
	}
	static class ABP_Proxy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Proxy_C>();
	}
};
static_assert(alignof(ABP_Proxy_C) == 0x000008, "Wrong alignment on ABP_Proxy_C");
static_assert(sizeof(ABP_Proxy_C) == 0x000328, "Wrong size on ABP_Proxy_C");
static_assert(offsetof(ABP_Proxy_C, NavLinker) == 0x000318, "Member 'ABP_Proxy_C::NavLinker' has a wrong offset!");
static_assert(offsetof(ABP_Proxy_C, Billboard) == 0x000320, "Member 'ABP_Proxy_C::Billboard' has a wrong offset!");

}

