#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Screwdriver

#include "Basic.hpp"

#include "BP_Item_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Screwdriver.BP_Screwdriver_C
// 0x0000 (0x03F0 - 0x03F0)
class ABP_Screwdriver_C final : public ABP_Item_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Screwdriver_C">();
	}
	static class ABP_Screwdriver_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Screwdriver_C>();
	}
};
static_assert(alignof(ABP_Screwdriver_C) == 0x000008, "Wrong alignment on ABP_Screwdriver_C");
static_assert(sizeof(ABP_Screwdriver_C) == 0x0003F0, "Wrong size on ABP_Screwdriver_C");

}

