#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Teleporter_Lost_Found

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Teleporter_Lost_Found.BP_Teleporter_Lost_Found_C
// 0x0020 (0x03A8 - 0x0388)
class ABP_Teleporter_Lost_Found_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0388(0x0008)(Transient, DuplicateTransient)
	class UArrowComponent*                        arrow;                                             // 0x0390(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box;                                               // 0x0398(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x03A0(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Teleporter_Lost_Found(int32 EntryPoint);
	void BndEvt__Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Teleporter_Lost_Found_C">();
	}
	static class ABP_Teleporter_Lost_Found_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Teleporter_Lost_Found_C>();
	}
};
static_assert(alignof(ABP_Teleporter_Lost_Found_C) == 0x000008, "Wrong alignment on ABP_Teleporter_Lost_Found_C");
static_assert(sizeof(ABP_Teleporter_Lost_Found_C) == 0x0003A8, "Wrong size on ABP_Teleporter_Lost_Found_C");
static_assert(offsetof(ABP_Teleporter_Lost_Found_C, UberGraphFrame) == 0x000388, "Member 'ABP_Teleporter_Lost_Found_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_Teleporter_Lost_Found_C, arrow) == 0x000390, "Member 'ABP_Teleporter_Lost_Found_C::arrow' has a wrong offset!");
static_assert(offsetof(ABP_Teleporter_Lost_Found_C, Box) == 0x000398, "Member 'ABP_Teleporter_Lost_Found_C::Box' has a wrong offset!");
static_assert(offsetof(ABP_Teleporter_Lost_Found_C, DefaultSceneRoot) == 0x0003A0, "Member 'ABP_Teleporter_Lost_Found_C::DefaultSceneRoot' has a wrong offset!");

}

