#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Tutorial_Key

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Tutorial_Key.BP_Tutorial_Key_C.ExecuteUbergraph_BP_Tutorial_Key
// 0x0020 (0x0020 - 0x0000)
struct BP_Tutorial_Key_C_ExecuteUbergraph_BP_Tutorial_Key final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_Character;                            // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBPW_TaskItem_C*                        CallFunc_GetTask_Item;                             // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Tutorial_Key_C_ExecuteUbergraph_BP_Tutorial_Key) == 0x000008, "Wrong alignment on BP_Tutorial_Key_C_ExecuteUbergraph_BP_Tutorial_Key");
static_assert(sizeof(BP_Tutorial_Key_C_ExecuteUbergraph_BP_Tutorial_Key) == 0x000020, "Wrong size on BP_Tutorial_Key_C_ExecuteUbergraph_BP_Tutorial_Key");
static_assert(offsetof(BP_Tutorial_Key_C_ExecuteUbergraph_BP_Tutorial_Key, EntryPoint) == 0x000000, "Member 'BP_Tutorial_Key_C_ExecuteUbergraph_BP_Tutorial_Key::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_Tutorial_Key_C_ExecuteUbergraph_BP_Tutorial_Key, K2Node_Event_Character) == 0x000008, "Member 'BP_Tutorial_Key_C_ExecuteUbergraph_BP_Tutorial_Key::K2Node_Event_Character' has a wrong offset!");
static_assert(offsetof(BP_Tutorial_Key_C_ExecuteUbergraph_BP_Tutorial_Key, CallFunc_GetTask_Item) == 0x000010, "Member 'BP_Tutorial_Key_C_ExecuteUbergraph_BP_Tutorial_Key::CallFunc_GetTask_Item' has a wrong offset!");
static_assert(offsetof(BP_Tutorial_Key_C_ExecuteUbergraph_BP_Tutorial_Key, CallFunc_IsValid_ReturnValue) == 0x000018, "Member 'BP_Tutorial_Key_C_ExecuteUbergraph_BP_Tutorial_Key::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function BP_Tutorial_Key.BP_Tutorial_Key_C.OnGrab
// 0x0008 (0x0008 - 0x0000)
struct BP_Tutorial_Key_C_OnGrab final
{
public:
	class AActor*                                 Character;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Tutorial_Key_C_OnGrab) == 0x000008, "Wrong alignment on BP_Tutorial_Key_C_OnGrab");
static_assert(sizeof(BP_Tutorial_Key_C_OnGrab) == 0x000008, "Wrong size on BP_Tutorial_Key_C_OnGrab");
static_assert(offsetof(BP_Tutorial_Key_C_OnGrab, Character) == 0x000000, "Member 'BP_Tutorial_Key_C_OnGrab::Character' has a wrong offset!");

// Function BP_Tutorial_Key.BP_Tutorial_Key_C.OnIsActionComponent
// 0x0010 (0x0010 - 0x0000)
struct BP_Tutorial_Key_C_OnIsActionComponent final
{
public:
	class UPrimitiveComponent*                    Component;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Result;                                            // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Tutorial_Key_C_OnIsActionComponent) == 0x000008, "Wrong alignment on BP_Tutorial_Key_C_OnIsActionComponent");
static_assert(sizeof(BP_Tutorial_Key_C_OnIsActionComponent) == 0x000010, "Wrong size on BP_Tutorial_Key_C_OnIsActionComponent");
static_assert(offsetof(BP_Tutorial_Key_C_OnIsActionComponent, Component) == 0x000000, "Member 'BP_Tutorial_Key_C_OnIsActionComponent::Component' has a wrong offset!");
static_assert(offsetof(BP_Tutorial_Key_C_OnIsActionComponent, Result) == 0x000008, "Member 'BP_Tutorial_Key_C_OnIsActionComponent::Result' has a wrong offset!");

}

