#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Trap

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HelloNeighborReborn_structs.hpp"
#include "HelloNeighborReborn_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Trap.BP_Trap_C
// 0x0050 (0x0580 - 0x0530)
class ABP_Trap_C final : public ATrap
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0530(0x0008)(Transient, DuplicateTransient)
	class UBoxComponent*                          Box;                                               // 0x0538(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box2;                                              // 0x0540(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box1;                                              // 0x0548(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Trigger;                                           // 0x0550(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         LeftAngle;                                         // 0x0558(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         RightAngle;                                        // 0x055C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 LeftActor;                                         // 0x0560(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 RightActor;                                        // 0x0568(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         SpeedClose;                                        // 0x0570(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MaxRotAngle;                                       // 0x0574(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 ActorOverlap;                                      // 0x0578(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Trap(int32 EntryPoint);
	void ReceiveTick(float DeltaSeconds);
	void ReceiveBeginPlay();
	void BndEvt__Trigger_K2Node_ComponentBoundEvent_0_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
	void BndEvt__Box2_K2Node_ComponentBoundEvent_6_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void BndEvt__Box1_K2Node_ComponentBoundEvent_5_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void BndEvt__Box_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void UserConstructionScript();
	void OnIsActionComponent(class UPrimitiveComponent* Component, bool* Result);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Trap_C">();
	}
	static class ABP_Trap_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Trap_C>();
	}
};
static_assert(alignof(ABP_Trap_C) == 0x000008, "Wrong alignment on ABP_Trap_C");
static_assert(sizeof(ABP_Trap_C) == 0x000580, "Wrong size on ABP_Trap_C");
static_assert(offsetof(ABP_Trap_C, UberGraphFrame) == 0x000530, "Member 'ABP_Trap_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_Trap_C, Box) == 0x000538, "Member 'ABP_Trap_C::Box' has a wrong offset!");
static_assert(offsetof(ABP_Trap_C, Box2) == 0x000540, "Member 'ABP_Trap_C::Box2' has a wrong offset!");
static_assert(offsetof(ABP_Trap_C, Box1) == 0x000548, "Member 'ABP_Trap_C::Box1' has a wrong offset!");
static_assert(offsetof(ABP_Trap_C, Trigger) == 0x000550, "Member 'ABP_Trap_C::Trigger' has a wrong offset!");
static_assert(offsetof(ABP_Trap_C, LeftAngle) == 0x000558, "Member 'ABP_Trap_C::LeftAngle' has a wrong offset!");
static_assert(offsetof(ABP_Trap_C, RightAngle) == 0x00055C, "Member 'ABP_Trap_C::RightAngle' has a wrong offset!");
static_assert(offsetof(ABP_Trap_C, LeftActor) == 0x000560, "Member 'ABP_Trap_C::LeftActor' has a wrong offset!");
static_assert(offsetof(ABP_Trap_C, RightActor) == 0x000568, "Member 'ABP_Trap_C::RightActor' has a wrong offset!");
static_assert(offsetof(ABP_Trap_C, SpeedClose) == 0x000570, "Member 'ABP_Trap_C::SpeedClose' has a wrong offset!");
static_assert(offsetof(ABP_Trap_C, MaxRotAngle) == 0x000574, "Member 'ABP_Trap_C::MaxRotAngle' has a wrong offset!");
static_assert(offsetof(ABP_Trap_C, ActorOverlap) == 0x000578, "Member 'ABP_Trap_C::ActorOverlap' has a wrong offset!");

}

