#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Umbrella

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HelloNeighbor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Umbrella.BP_Umbrella_C
// 0x0008 (0x0468 - 0x0460)
class ABP_Umbrella_C final : public AUmbrella
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0460(0x0008)(Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_Umbrella(int32 EntryPoint);
	void OnIsActionComponent(class UPrimitiveComponent* Component, bool* Result);
	void UserConstructionScript();
	void ReceiveBeginPlay();
	void OnChangeState(bool NewState);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Umbrella_C">();
	}
	static class ABP_Umbrella_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Umbrella_C>();
	}
};
static_assert(alignof(ABP_Umbrella_C) == 0x000008, "Wrong alignment on ABP_Umbrella_C");
static_assert(sizeof(ABP_Umbrella_C) == 0x000468, "Wrong size on ABP_Umbrella_C");
static_assert(offsetof(ABP_Umbrella_C, UberGraphFrame) == 0x000460, "Member 'ABP_Umbrella_C::UberGraphFrame' has a wrong offset!");

}

