#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_UETWidgets

#include "Basic.hpp"

#include "BPI_UETWidgets_classes.hpp"
#include "BPI_UETWidgets_parameters.hpp"


namespace SDK
{

// Function BPI_UETWidgets.BPI_UETWidgets_C.CanVisible
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   bVisible                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_UETWidgets_C::CanVisible(bool* bVisible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_UETWidgets_C", "CanVisible");

	Params::BPI_UETWidgets_C_CanVisible Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (bVisible != nullptr)
		*bVisible = Parms.bVisible;
}


// Function BPI_UETWidgets.BPI_UETWidgets_C.Destroy
// (Public, BlueprintCallable, BlueprintEvent)

void IBPI_UETWidgets_C::Destroy()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_UETWidgets_C", "Destroy");

	AsUObject()->ProcessEvent(Func, nullptr);
}


// Function BPI_UETWidgets.BPI_UETWidgets_C.InitTab
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMainEdit_C*                      MainEdit                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UActorComponent*                  Component                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UBPW_UETExpandableArea_C*         ExpandableArea                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void IBPI_UETWidgets_C::InitTab(class UMainEdit_C* MainEdit, class AActor* Actor, class UActorComponent* Component, class UBPW_UETExpandableArea_C* ExpandableArea)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_UETWidgets_C", "InitTab");

	Params::BPI_UETWidgets_C_InitTab Parms{};

	Parms.MainEdit = MainEdit;
	Parms.Actor = Actor;
	Parms.Component = Component;
	Parms.ExpandableArea = ExpandableArea;

	AsUObject()->ProcessEvent(Func, &Parms);
}


// Function BPI_UETWidgets.BPI_UETWidgets_C.Start
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          ParentWidget                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void IBPI_UETWidgets_C::Start(class UWidget* ParentWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_UETWidgets_C", "Start");

	Params::BPI_UETWidgets_C_Start Parms{};

	Parms.ParentWidget = ParentWidget;

	AsUObject()->ProcessEvent(Func, &Parms);
}

}

