#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_SaveItem

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPW_SaveItem.BPW_SaveItem_C
// 0x0078 (0x0358 - 0x02E0)
class UBPW_SaveItem_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Load;                                              // 0x02E8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Delete;                                            // 0x02F0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Fade;                                              // 0x02F8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Border;                                            // 0x0300(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                DeleteButton;                                      // 0x0308(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image;                                             // 0x0310(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_132;                                         // 0x0318(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                LoadButton;                                        // 0x0320(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             nmametxt;                                          // 0x0328(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Status;                                            // 0x0330(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Status_1;                                          // 0x0338(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FString                                 Name_0;                                            // 0x0340(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          Enabled;                                           // 0x0350(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BPW_ModWidget_MainButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__BPW_SaveItem_DeleteButton_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__BPW_SaveItem_DeleteButton_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__BPW_SaveItem_LoadButton_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__BPW_SaveItem_LoadButton_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__BPW_SaveItem_MainButton_1_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
	void Construct();
	void ExecuteUbergraph_BPW_SaveItem(int32 EntryPoint);
	void OnPressedButton_Event_0(bool bYesButton);
	void OnPressedPopupButton(bool bYesButton);
	void SetName();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPW_SaveItem_C">();
	}
	static class UBPW_SaveItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPW_SaveItem_C>();
	}
};
static_assert(alignof(UBPW_SaveItem_C) == 0x000008, "Wrong alignment on UBPW_SaveItem_C");
static_assert(sizeof(UBPW_SaveItem_C) == 0x000358, "Wrong size on UBPW_SaveItem_C");
static_assert(offsetof(UBPW_SaveItem_C, UberGraphFrame) == 0x0002E0, "Member 'UBPW_SaveItem_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBPW_SaveItem_C, Load) == 0x0002E8, "Member 'UBPW_SaveItem_C::Load' has a wrong offset!");
static_assert(offsetof(UBPW_SaveItem_C, Delete) == 0x0002F0, "Member 'UBPW_SaveItem_C::Delete' has a wrong offset!");
static_assert(offsetof(UBPW_SaveItem_C, Fade) == 0x0002F8, "Member 'UBPW_SaveItem_C::Fade' has a wrong offset!");
static_assert(offsetof(UBPW_SaveItem_C, Border) == 0x000300, "Member 'UBPW_SaveItem_C::Border' has a wrong offset!");
static_assert(offsetof(UBPW_SaveItem_C, DeleteButton) == 0x000308, "Member 'UBPW_SaveItem_C::DeleteButton' has a wrong offset!");
static_assert(offsetof(UBPW_SaveItem_C, Image) == 0x000310, "Member 'UBPW_SaveItem_C::Image' has a wrong offset!");
static_assert(offsetof(UBPW_SaveItem_C, Image_132) == 0x000318, "Member 'UBPW_SaveItem_C::Image_132' has a wrong offset!");
static_assert(offsetof(UBPW_SaveItem_C, LoadButton) == 0x000320, "Member 'UBPW_SaveItem_C::LoadButton' has a wrong offset!");
static_assert(offsetof(UBPW_SaveItem_C, nmametxt) == 0x000328, "Member 'UBPW_SaveItem_C::nmametxt' has a wrong offset!");
static_assert(offsetof(UBPW_SaveItem_C, Status) == 0x000330, "Member 'UBPW_SaveItem_C::Status' has a wrong offset!");
static_assert(offsetof(UBPW_SaveItem_C, Status_1) == 0x000338, "Member 'UBPW_SaveItem_C::Status_1' has a wrong offset!");
static_assert(offsetof(UBPW_SaveItem_C, Name_0) == 0x000340, "Member 'UBPW_SaveItem_C::Name_0' has a wrong offset!");
static_assert(offsetof(UBPW_SaveItem_C, Enabled) == 0x000350, "Member 'UBPW_SaveItem_C::Enabled' has a wrong offset!");

}

