#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_GizmoModeWidget

#include "Basic.hpp"

#include "GizmoMode_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPW_GizmoModeWidget.BPW_GizmoModeWidget_C
// 0x0088 (0x0368 - 0x02E0)
class UBPW_GizmoModeWidget_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCheckBox*                              CheckBox_150;                                      // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_362;                                         // 0x02F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMainEdit_C*                            Main;                                              // 0x02F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	EGizmoMode                                    GizmoMode;                                         // 0x0300(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_301[0x7];                                      // 0x0301(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<EGizmoMode, class UTexture2D*>           GizmoIcons;                                        // 0x0308(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMulticastInlineDelegate<void(class UBPW_GizmoModeWidget_C* Widget, EGizmoMode Mode)> OnGizmoSelect; // 0x0358(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void BndEvt__BPW_GizmoModeWidget_CheckBox_150_K2Node_ComponentBoundEvent_0_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked);
	void CanVisible(bool* bVisible);
	void Destroy();
	void ExecuteUbergraph_BPW_GizmoModeWidget(int32 EntryPoint);
	void InitTab(class UMainEdit_C* MainEdit, class AActor* Actor, class UActorComponent* Component, class UBPW_UETExpandableArea_C* ExpandableArea);
	void PreConstruct(bool IsDesignTime);
	void SetState(bool bOn);
	void Start(class UWidget* ParentWidget);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPW_GizmoModeWidget_C">();
	}
	static class UBPW_GizmoModeWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPW_GizmoModeWidget_C>();
	}
};
static_assert(alignof(UBPW_GizmoModeWidget_C) == 0x000008, "Wrong alignment on UBPW_GizmoModeWidget_C");
static_assert(sizeof(UBPW_GizmoModeWidget_C) == 0x000368, "Wrong size on UBPW_GizmoModeWidget_C");
static_assert(offsetof(UBPW_GizmoModeWidget_C, UberGraphFrame) == 0x0002E0, "Member 'UBPW_GizmoModeWidget_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBPW_GizmoModeWidget_C, CheckBox_150) == 0x0002E8, "Member 'UBPW_GizmoModeWidget_C::CheckBox_150' has a wrong offset!");
static_assert(offsetof(UBPW_GizmoModeWidget_C, Image_362) == 0x0002F0, "Member 'UBPW_GizmoModeWidget_C::Image_362' has a wrong offset!");
static_assert(offsetof(UBPW_GizmoModeWidget_C, Main) == 0x0002F8, "Member 'UBPW_GizmoModeWidget_C::Main' has a wrong offset!");
static_assert(offsetof(UBPW_GizmoModeWidget_C, GizmoMode) == 0x000300, "Member 'UBPW_GizmoModeWidget_C::GizmoMode' has a wrong offset!");
static_assert(offsetof(UBPW_GizmoModeWidget_C, GizmoIcons) == 0x000308, "Member 'UBPW_GizmoModeWidget_C::GizmoIcons' has a wrong offset!");
static_assert(offsetof(UBPW_GizmoModeWidget_C, OnGizmoSelect) == 0x000358, "Member 'UBPW_GizmoModeWidget_C::OnGizmoSelect' has a wrong offset!");

}

