#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_GameLoading

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPW_GameLoading.BPW_GameLoading_C
// 0x0028 (0x0230 - 0x0208)
class UBPW_GameLoading_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0208(0x0008)(Transient, DuplicateTransient)
	class UWidgetAnimation*                       clock;                                             // 0x0210(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ArrowHour;                                         // 0x0218(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ArrowMinute;                                       // 0x0220(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_64;                                          // 0x0228(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BPW_GameLoading(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPW_GameLoading_C">();
	}
	static class UBPW_GameLoading_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPW_GameLoading_C>();
	}
};
static_assert(alignof(UBPW_GameLoading_C) == 0x000008, "Wrong alignment on UBPW_GameLoading_C");
static_assert(sizeof(UBPW_GameLoading_C) == 0x000230, "Wrong size on UBPW_GameLoading_C");
static_assert(offsetof(UBPW_GameLoading_C, UberGraphFrame) == 0x000208, "Member 'UBPW_GameLoading_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBPW_GameLoading_C, clock) == 0x000210, "Member 'UBPW_GameLoading_C::clock' has a wrong offset!");
static_assert(offsetof(UBPW_GameLoading_C, ArrowHour) == 0x000218, "Member 'UBPW_GameLoading_C::ArrowHour' has a wrong offset!");
static_assert(offsetof(UBPW_GameLoading_C, ArrowMinute) == 0x000220, "Member 'UBPW_GameLoading_C::ArrowMinute' has a wrong offset!");
static_assert(offsetof(UBPW_GameLoading_C, Image_64) == 0x000228, "Member 'UBPW_GameLoading_C::Image_64' has a wrong offset!");

}

