#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_ExpandableAreaWrapper

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPW_ExpandableAreaWrapper.BPW_ExpandableAreaWrapper_C
// 0x0048 (0x0328 - 0x02E0)
class UBPW_ExpandableAreaWrapper_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBPW_UETExpandableArea_C*               ExpandableArea;                                    // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           ExpandableVerticalBox;                             // 0x02F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             HeaderText;                                        // 0x02F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   Text;                                              // 0x0300(0x0010)(Edit, BlueprintVisible, ExposeOnSpawn)
	class UClass*                                 BodyClass;                                         // 0x0310(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UUserWidget*                            Body;                                              // 0x0318(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsExpanded;                                       // 0x0320(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          bAlwaysVisible;                                    // 0x0321(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void InitExpandableBodyTab(class UMainEdit_C* MainEdit, class AActor* Actor, class UActorComponent* Component);
	void OnInitialized();
	void PreConstruct(bool IsDesignTime);
	void ExecuteUbergraph_BPW_ExpandableAreaWrapper(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPW_ExpandableAreaWrapper_C">();
	}
	static class UBPW_ExpandableAreaWrapper_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPW_ExpandableAreaWrapper_C>();
	}
};
static_assert(alignof(UBPW_ExpandableAreaWrapper_C) == 0x000008, "Wrong alignment on UBPW_ExpandableAreaWrapper_C");
static_assert(sizeof(UBPW_ExpandableAreaWrapper_C) == 0x000328, "Wrong size on UBPW_ExpandableAreaWrapper_C");
static_assert(offsetof(UBPW_ExpandableAreaWrapper_C, UberGraphFrame) == 0x0002E0, "Member 'UBPW_ExpandableAreaWrapper_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBPW_ExpandableAreaWrapper_C, ExpandableArea) == 0x0002E8, "Member 'UBPW_ExpandableAreaWrapper_C::ExpandableArea' has a wrong offset!");
static_assert(offsetof(UBPW_ExpandableAreaWrapper_C, ExpandableVerticalBox) == 0x0002F0, "Member 'UBPW_ExpandableAreaWrapper_C::ExpandableVerticalBox' has a wrong offset!");
static_assert(offsetof(UBPW_ExpandableAreaWrapper_C, HeaderText) == 0x0002F8, "Member 'UBPW_ExpandableAreaWrapper_C::HeaderText' has a wrong offset!");
static_assert(offsetof(UBPW_ExpandableAreaWrapper_C, Text) == 0x000300, "Member 'UBPW_ExpandableAreaWrapper_C::Text' has a wrong offset!");
static_assert(offsetof(UBPW_ExpandableAreaWrapper_C, BodyClass) == 0x000310, "Member 'UBPW_ExpandableAreaWrapper_C::BodyClass' has a wrong offset!");
static_assert(offsetof(UBPW_ExpandableAreaWrapper_C, Body) == 0x000318, "Member 'UBPW_ExpandableAreaWrapper_C::Body' has a wrong offset!");
static_assert(offsetof(UBPW_ExpandableAreaWrapper_C, bIsExpanded) == 0x000320, "Member 'UBPW_ExpandableAreaWrapper_C::bIsExpanded' has a wrong offset!");
static_assert(offsetof(UBPW_ExpandableAreaWrapper_C, bAlwaysVisible) == 0x000321, "Member 'UBPW_ExpandableAreaWrapper_C::bAlwaysVisible' has a wrong offset!");

}

