#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTDecorator_CheckDistToActor

#include "Basic.hpp"

#include "AIModule_structs.hpp"
#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BTDecorator_CheckDistToActor.BTDecorator_CheckDistToActor_C
// 0x0030 (0x00D0 - 0x00A0)
class UBTDecorator_CheckDistToActor_C final : public UBTDecorator_BlueprintBase
{
public:
	struct FBlackboardKeySelector                 Actor_InKey;                                       // 0x00A0(0x0028)(Edit, BlueprintVisible)
	float                                         MaxDistance;                                       // 0x00C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool PerformConditionCheckAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BTDecorator_CheckDistToActor_C">();
	}
	static class UBTDecorator_CheckDistToActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTDecorator_CheckDistToActor_C>();
	}
};
static_assert(alignof(UBTDecorator_CheckDistToActor_C) == 0x000008, "Wrong alignment on UBTDecorator_CheckDistToActor_C");
static_assert(sizeof(UBTDecorator_CheckDistToActor_C) == 0x0000D0, "Wrong size on UBTDecorator_CheckDistToActor_C");
static_assert(offsetof(UBTDecorator_CheckDistToActor_C, Actor_InKey) == 0x0000A0, "Member 'UBTDecorator_CheckDistToActor_C::Actor_InKey' has a wrong offset!");
static_assert(offsetof(UBTDecorator_CheckDistToActor_C, MaxDistance) == 0x0000C8, "Member 'UBTDecorator_CheckDistToActor_C::MaxDistance' has a wrong offset!");

}

