#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTDecorator_CheckDistBetweenActorAndVector

#include "Basic.hpp"

#include "AIModule_structs.hpp"
#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BTDecorator_CheckDistBetweenActorAndVector.BTDecorator_CheckDistBetweenActorAndVector_C
// 0x0058 (0x00F8 - 0x00A0)
class UBTDecorator_CheckDistBetweenActorAndVector_C final : public UBTDecorator_BlueprintBase
{
public:
	struct FBlackboardKeySelector                 Actor_InKey;                                       // 0x00A0(0x0028)(Edit, BlueprintVisible)
	struct FBlackboardKeySelector                 Vector_InKey;                                      // 0x00C8(0x0028)(Edit, BlueprintVisible)
	float                                         MaxDistance;                                       // 0x00F0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool PerformConditionCheckAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BTDecorator_CheckDistBetweenActorAndVector_C">();
	}
	static class UBTDecorator_CheckDistBetweenActorAndVector_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTDecorator_CheckDistBetweenActorAndVector_C>();
	}
};
static_assert(alignof(UBTDecorator_CheckDistBetweenActorAndVector_C) == 0x000008, "Wrong alignment on UBTDecorator_CheckDistBetweenActorAndVector_C");
static_assert(sizeof(UBTDecorator_CheckDistBetweenActorAndVector_C) == 0x0000F8, "Wrong size on UBTDecorator_CheckDistBetweenActorAndVector_C");
static_assert(offsetof(UBTDecorator_CheckDistBetweenActorAndVector_C, Actor_InKey) == 0x0000A0, "Member 'UBTDecorator_CheckDistBetweenActorAndVector_C::Actor_InKey' has a wrong offset!");
static_assert(offsetof(UBTDecorator_CheckDistBetweenActorAndVector_C, Vector_InKey) == 0x0000C8, "Member 'UBTDecorator_CheckDistBetweenActorAndVector_C::Vector_InKey' has a wrong offset!");
static_assert(offsetof(UBTDecorator_CheckDistBetweenActorAndVector_C, MaxDistance) == 0x0000F0, "Member 'UBTDecorator_CheckDistBetweenActorAndVector_C::MaxDistance' has a wrong offset!");

}

