#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTDecorator_AreActorKeysEqual

#include "Basic.hpp"

#include "AIModule_structs.hpp"
#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BTDecorator_AreActorKeysEqual.BTDecorator_AreActorKeysEqual_C
// 0x0078 (0x0118 - 0x00A0)
class UBTDecorator_AreActorKeysEqual_C final : public UBTDecorator_BlueprintBase
{
public:
	struct FBlackboardKeySelector                 First_InKey;                                       // 0x00A0(0x0028)(Edit, BlueprintVisible)
	struct FBlackboardKeySelector                 Second_OutKey;                                     // 0x00C8(0x0028)(Edit, BlueprintVisible)
	struct FBlackboardKeySelector                 NewVar_0;                                          // 0x00F0(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	bool PerformConditionCheck(class AActor* OwnerActor);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BTDecorator_AreActorKeysEqual_C">();
	}
	static class UBTDecorator_AreActorKeysEqual_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTDecorator_AreActorKeysEqual_C>();
	}
};
static_assert(alignof(UBTDecorator_AreActorKeysEqual_C) == 0x000008, "Wrong alignment on UBTDecorator_AreActorKeysEqual_C");
static_assert(sizeof(UBTDecorator_AreActorKeysEqual_C) == 0x000118, "Wrong size on UBTDecorator_AreActorKeysEqual_C");
static_assert(offsetof(UBTDecorator_AreActorKeysEqual_C, First_InKey) == 0x0000A0, "Member 'UBTDecorator_AreActorKeysEqual_C::First_InKey' has a wrong offset!");
static_assert(offsetof(UBTDecorator_AreActorKeysEqual_C, Second_OutKey) == 0x0000C8, "Member 'UBTDecorator_AreActorKeysEqual_C::Second_OutKey' has a wrong offset!");
static_assert(offsetof(UBTDecorator_AreActorKeysEqual_C, NewVar_0) == 0x0000F0, "Member 'UBTDecorator_AreActorKeysEqual_C::NewVar_0' has a wrong offset!");

}

