#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTService_UnselectCurrentItemOnDeactivate

#include "Basic.hpp"


namespace SDK::Params
{

// Function BTService_UnselectCurrentItemOnDeactivate.BTService_UnselectCurrentItemOnDeactivate_C.ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate
// 0x0048 (0x0048 - 0x0000)
struct BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AAIController*                          K2Node_Event_OwnerController;                      // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  K2Node_Event_ControlledPawn;                       // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABot*                                   K2Node_DynamicCast_AsBot;                          // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABaseActor*                             CallFunc_GetCurrentObject_ReturnValue;             // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_UnselectCurrentItem_ReturnValue;          // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0032(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_33[0x5];                                       // 0x0033(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                CallFunc_GetBlackboardValueAsObject_ReturnValue;   // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate) == 0x000008, "Wrong alignment on BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate");
static_assert(sizeof(BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate) == 0x000048, "Wrong size on BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate");
static_assert(offsetof(BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate, EntryPoint) == 0x000000, "Member 'BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate::EntryPoint' has a wrong offset!");
static_assert(offsetof(BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate, K2Node_Event_OwnerController) == 0x000008, "Member 'BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate::K2Node_Event_OwnerController' has a wrong offset!");
static_assert(offsetof(BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate, K2Node_Event_ControlledPawn) == 0x000010, "Member 'BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate::K2Node_Event_ControlledPawn' has a wrong offset!");
static_assert(offsetof(BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate, K2Node_DynamicCast_AsBot) == 0x000018, "Member 'BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate::K2Node_DynamicCast_AsBot' has a wrong offset!");
static_assert(offsetof(BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate, CallFunc_GetCurrentObject_ReturnValue) == 0x000028, "Member 'BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate::CallFunc_GetCurrentObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate, CallFunc_UnselectCurrentItem_ReturnValue) == 0x000030, "Member 'BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate::CallFunc_UnselectCurrentItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate, CallFunc_BooleanAND_ReturnValue) == 0x000031, "Member 'BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate, CallFunc_IsValid_ReturnValue) == 0x000032, "Member 'BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate, CallFunc_GetBlackboardValueAsObject_ReturnValue) == 0x000038, "Member 'BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate::CallFunc_GetBlackboardValueAsObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000040, "Member 'BTService_UnselectCurrentItemOnDeactivate_C_ExecuteUbergraph_BTService_UnselectCurrentItemOnDeactivate::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");

// Function BTService_UnselectCurrentItemOnDeactivate.BTService_UnselectCurrentItemOnDeactivate_C.ReceiveDeactivationAI
// 0x0010 (0x0010 - 0x0000)
struct BTService_UnselectCurrentItemOnDeactivate_C_ReceiveDeactivationAI final
{
public:
	class AAIController*                          OwnerController;                                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  ControlledPawn;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BTService_UnselectCurrentItemOnDeactivate_C_ReceiveDeactivationAI) == 0x000008, "Wrong alignment on BTService_UnselectCurrentItemOnDeactivate_C_ReceiveDeactivationAI");
static_assert(sizeof(BTService_UnselectCurrentItemOnDeactivate_C_ReceiveDeactivationAI) == 0x000010, "Wrong size on BTService_UnselectCurrentItemOnDeactivate_C_ReceiveDeactivationAI");
static_assert(offsetof(BTService_UnselectCurrentItemOnDeactivate_C_ReceiveDeactivationAI, OwnerController) == 0x000000, "Member 'BTService_UnselectCurrentItemOnDeactivate_C_ReceiveDeactivationAI::OwnerController' has a wrong offset!");
static_assert(offsetof(BTService_UnselectCurrentItemOnDeactivate_C_ReceiveDeactivationAI, ControlledPawn) == 0x000008, "Member 'BTService_UnselectCurrentItemOnDeactivate_C_ReceiveDeactivationAI::ControlledPawn' has a wrong offset!");

}

