#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTService_UpdateHeardData

#include "Basic.hpp"


namespace SDK::Params
{

// Function BTService_UpdateHeardData.BTService_UpdateHeardData_C.ExecuteUbergraph_BTService_UpdateHeardData
// 0x0040 (0x0040 - 0x0000)
struct BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_OwnerActor_2;                         // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_OwnerActor_1;                         // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                CallFunc_GetBlackboardValueAsObject_ReturnValue;   // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBotBehState_NoiseChecking*             K2Node_DynamicCast_AsBot_Beh_State_Noise_Checking; // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_32[0x6];                                       // 0x0032(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_OwnerActor;                           // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData) == 0x000008, "Wrong alignment on BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData");
static_assert(sizeof(BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData) == 0x000040, "Wrong size on BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData");
static_assert(offsetof(BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData, EntryPoint) == 0x000000, "Member 'BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData::EntryPoint' has a wrong offset!");
static_assert(offsetof(BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData, K2Node_Event_OwnerActor_2) == 0x000008, "Member 'BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData::K2Node_Event_OwnerActor_2' has a wrong offset!");
static_assert(offsetof(BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData, K2Node_Event_OwnerActor_1) == 0x000010, "Member 'BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData::K2Node_Event_OwnerActor_1' has a wrong offset!");
static_assert(offsetof(BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData, K2Node_Event_DeltaSeconds) == 0x000018, "Member 'BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData, CallFunc_GetBlackboardValueAsObject_ReturnValue) == 0x000020, "Member 'BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData::CallFunc_GetBlackboardValueAsObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData, K2Node_DynamicCast_AsBot_Beh_State_Noise_Checking) == 0x000028, "Member 'BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData::K2Node_DynamicCast_AsBot_Beh_State_Noise_Checking' has a wrong offset!");
static_assert(offsetof(BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData, K2Node_DynamicCast_bSuccess) == 0x000030, "Member 'BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData, CallFunc_NotEqual_ObjectObject_ReturnValue) == 0x000031, "Member 'BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData::CallFunc_NotEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData, K2Node_Event_OwnerActor) == 0x000038, "Member 'BTService_UpdateHeardData_C_ExecuteUbergraph_BTService_UpdateHeardData::K2Node_Event_OwnerActor' has a wrong offset!");

// Function BTService_UpdateHeardData.BTService_UpdateHeardData_C.ReceiveDeactivation
// 0x0008 (0x0008 - 0x0000)
struct BTService_UpdateHeardData_C_ReceiveDeactivation final
{
public:
	class AActor*                                 OwnerActor;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BTService_UpdateHeardData_C_ReceiveDeactivation) == 0x000008, "Wrong alignment on BTService_UpdateHeardData_C_ReceiveDeactivation");
static_assert(sizeof(BTService_UpdateHeardData_C_ReceiveDeactivation) == 0x000008, "Wrong size on BTService_UpdateHeardData_C_ReceiveDeactivation");
static_assert(offsetof(BTService_UpdateHeardData_C_ReceiveDeactivation, OwnerActor) == 0x000000, "Member 'BTService_UpdateHeardData_C_ReceiveDeactivation::OwnerActor' has a wrong offset!");

// Function BTService_UpdateHeardData.BTService_UpdateHeardData_C.ReceiveTick
// 0x0010 (0x0010 - 0x0000)
struct BTService_UpdateHeardData_C_ReceiveTick final
{
public:
	class AActor*                                 OwnerActor;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DeltaSeconds;                                      // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BTService_UpdateHeardData_C_ReceiveTick) == 0x000008, "Wrong alignment on BTService_UpdateHeardData_C_ReceiveTick");
static_assert(sizeof(BTService_UpdateHeardData_C_ReceiveTick) == 0x000010, "Wrong size on BTService_UpdateHeardData_C_ReceiveTick");
static_assert(offsetof(BTService_UpdateHeardData_C_ReceiveTick, OwnerActor) == 0x000000, "Member 'BTService_UpdateHeardData_C_ReceiveTick::OwnerActor' has a wrong offset!");
static_assert(offsetof(BTService_UpdateHeardData_C_ReceiveTick, DeltaSeconds) == 0x000008, "Member 'BTService_UpdateHeardData_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function BTService_UpdateHeardData.BTService_UpdateHeardData_C.ReceiveActivation
// 0x0008 (0x0008 - 0x0000)
struct BTService_UpdateHeardData_C_ReceiveActivation final
{
public:
	class AActor*                                 OwnerActor;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BTService_UpdateHeardData_C_ReceiveActivation) == 0x000008, "Wrong alignment on BTService_UpdateHeardData_C_ReceiveActivation");
static_assert(sizeof(BTService_UpdateHeardData_C_ReceiveActivation) == 0x000008, "Wrong size on BTService_UpdateHeardData_C_ReceiveActivation");
static_assert(offsetof(BTService_UpdateHeardData_C_ReceiveActivation, OwnerActor) == 0x000000, "Member 'BTService_UpdateHeardData_C_ReceiveActivation::OwnerActor' has a wrong offset!");

}

