#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTTask_RememberActorAsLost

#include "Basic.hpp"

#include "BTTask_RememberActorAsLost_classes.hpp"
#include "BTTask_RememberActorAsLost_parameters.hpp"


namespace SDK
{

// Function BTTask_RememberActorAsLost.BTTask_RememberActorAsLost_C.ExecuteUbergraph_BTTask_RememberActorAsLost
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBTTask_RememberActorAsLost_C::ExecuteUbergraph_BTTask_RememberActorAsLost(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTTask_RememberActorAsLost_C", "ExecuteUbergraph_BTTask_RememberActorAsLost");

	Params::BTTask_RememberActorAsLost_C_ExecuteUbergraph_BTTask_RememberActorAsLost Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BTTask_RememberActorAsLost.BTTask_RememberActorAsLost_C.ReceiveExecuteAI
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AAIController*                    OwnerController                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class APawn*                            ControlledPawn                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBTTask_RememberActorAsLost_C::ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTTask_RememberActorAsLost_C", "ReceiveExecuteAI");

	Params::BTTask_RememberActorAsLost_C_ReceiveExecuteAI Parms{};

	Parms.OwnerController = OwnerController;
	Parms.ControlledPawn = ControlledPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BTTask_RememberActorAsLost.BTTask_RememberActorAsLost_C.Do ExecuteAI
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            PawnAI                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBTTask_RememberActorAsLost_C::Do_ExecuteAI(class APawn* PawnAI)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTTask_RememberActorAsLost_C", "Do ExecuteAI");

	Params::BTTask_RememberActorAsLost_C_Do_ExecuteAI Parms{};

	Parms.PawnAI = PawnAI;

	UObject::ProcessEvent(Func, &Parms);
}

}

