#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTTask_SetAlert

#include "Basic.hpp"


namespace SDK::Params
{

// Function BTTask_SetAlert.BTTask_SetAlert_C.ExecuteUbergraph_BTTask_SetAlert
// 0x0028 (0x0028 - 0x0000)
struct BTTask_SetAlert_C_ExecuteUbergraph_BTTask_SetAlert final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AAIController*                          K2Node_Event_OwnerController;                      // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  K2Node_Event_ControlledPawn;                       // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABot*                                   K2Node_DynamicCast_AsBot;                          // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BTTask_SetAlert_C_ExecuteUbergraph_BTTask_SetAlert) == 0x000008, "Wrong alignment on BTTask_SetAlert_C_ExecuteUbergraph_BTTask_SetAlert");
static_assert(sizeof(BTTask_SetAlert_C_ExecuteUbergraph_BTTask_SetAlert) == 0x000028, "Wrong size on BTTask_SetAlert_C_ExecuteUbergraph_BTTask_SetAlert");
static_assert(offsetof(BTTask_SetAlert_C_ExecuteUbergraph_BTTask_SetAlert, EntryPoint) == 0x000000, "Member 'BTTask_SetAlert_C_ExecuteUbergraph_BTTask_SetAlert::EntryPoint' has a wrong offset!");
static_assert(offsetof(BTTask_SetAlert_C_ExecuteUbergraph_BTTask_SetAlert, K2Node_Event_OwnerController) == 0x000008, "Member 'BTTask_SetAlert_C_ExecuteUbergraph_BTTask_SetAlert::K2Node_Event_OwnerController' has a wrong offset!");
static_assert(offsetof(BTTask_SetAlert_C_ExecuteUbergraph_BTTask_SetAlert, K2Node_Event_ControlledPawn) == 0x000010, "Member 'BTTask_SetAlert_C_ExecuteUbergraph_BTTask_SetAlert::K2Node_Event_ControlledPawn' has a wrong offset!");
static_assert(offsetof(BTTask_SetAlert_C_ExecuteUbergraph_BTTask_SetAlert, K2Node_DynamicCast_AsBot) == 0x000018, "Member 'BTTask_SetAlert_C_ExecuteUbergraph_BTTask_SetAlert::K2Node_DynamicCast_AsBot' has a wrong offset!");
static_assert(offsetof(BTTask_SetAlert_C_ExecuteUbergraph_BTTask_SetAlert, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'BTTask_SetAlert_C_ExecuteUbergraph_BTTask_SetAlert::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function BTTask_SetAlert.BTTask_SetAlert_C.ReceiveExecuteAI
// 0x0010 (0x0010 - 0x0000)
struct BTTask_SetAlert_C_ReceiveExecuteAI final
{
public:
	class AAIController*                          OwnerController;                                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  ControlledPawn;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BTTask_SetAlert_C_ReceiveExecuteAI) == 0x000008, "Wrong alignment on BTTask_SetAlert_C_ReceiveExecuteAI");
static_assert(sizeof(BTTask_SetAlert_C_ReceiveExecuteAI) == 0x000010, "Wrong size on BTTask_SetAlert_C_ReceiveExecuteAI");
static_assert(offsetof(BTTask_SetAlert_C_ReceiveExecuteAI, OwnerController) == 0x000000, "Member 'BTTask_SetAlert_C_ReceiveExecuteAI::OwnerController' has a wrong offset!");
static_assert(offsetof(BTTask_SetAlert_C_ReceiveExecuteAI, ControlledPawn) == 0x000008, "Member 'BTTask_SetAlert_C_ReceiveExecuteAI::ControlledPawn' has a wrong offset!");

}

