#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTTask_SetBackupTask

#include "Basic.hpp"


namespace SDK::Params
{

// Function BTTask_SetBackupTask.BTTask_SetBackupTask_C.ExecuteUbergraph_BTTask_SetBackupTask
// 0x0040 (0x0040 - 0x0000)
struct BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AAIController*                          K2Node_Event_OwnerController;                      // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  K2Node_Event_ControlledPawn;                       // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                CallFunc_GetBlackboardValueAsObject_ReturnValue;   // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UInteractionWithItem_BotObjective*      K2Node_DynamicCast_AsInteraction_with_Item_Bot_Objective; // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2A[0x6];                                       // 0x002A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UBotObjective*                          CallFunc_SpawnObject_ReturnValue;                  // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValidClass_ReturnValue;                 // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask) == 0x000008, "Wrong alignment on BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask");
static_assert(sizeof(BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask) == 0x000040, "Wrong size on BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask");
static_assert(offsetof(BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask, EntryPoint) == 0x000000, "Member 'BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask::EntryPoint' has a wrong offset!");
static_assert(offsetof(BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask, K2Node_Event_OwnerController) == 0x000008, "Member 'BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask::K2Node_Event_OwnerController' has a wrong offset!");
static_assert(offsetof(BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask, K2Node_Event_ControlledPawn) == 0x000010, "Member 'BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask::K2Node_Event_ControlledPawn' has a wrong offset!");
static_assert(offsetof(BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask, CallFunc_GetBlackboardValueAsObject_ReturnValue) == 0x000018, "Member 'BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask::CallFunc_GetBlackboardValueAsObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask, K2Node_DynamicCast_AsInteraction_with_Item_Bot_Objective) == 0x000020, "Member 'BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask::K2Node_DynamicCast_AsInteraction_with_Item_Bot_Objective' has a wrong offset!");
static_assert(offsetof(BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask, CallFunc_IsValid_ReturnValue) == 0x000029, "Member 'BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask, CallFunc_SpawnObject_ReturnValue) == 0x000030, "Member 'BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask, CallFunc_IsValidClass_ReturnValue) == 0x000038, "Member 'BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask::CallFunc_IsValidClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask, CallFunc_IsValid_ReturnValue_1) == 0x000039, "Member 'BTTask_SetBackupTask_C_ExecuteUbergraph_BTTask_SetBackupTask::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");

// Function BTTask_SetBackupTask.BTTask_SetBackupTask_C.ReceiveExecuteAI
// 0x0010 (0x0010 - 0x0000)
struct BTTask_SetBackupTask_C_ReceiveExecuteAI final
{
public:
	class AAIController*                          OwnerController;                                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  ControlledPawn;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BTTask_SetBackupTask_C_ReceiveExecuteAI) == 0x000008, "Wrong alignment on BTTask_SetBackupTask_C_ReceiveExecuteAI");
static_assert(sizeof(BTTask_SetBackupTask_C_ReceiveExecuteAI) == 0x000010, "Wrong size on BTTask_SetBackupTask_C_ReceiveExecuteAI");
static_assert(offsetof(BTTask_SetBackupTask_C_ReceiveExecuteAI, OwnerController) == 0x000000, "Member 'BTTask_SetBackupTask_C_ReceiveExecuteAI::OwnerController' has a wrong offset!");
static_assert(offsetof(BTTask_SetBackupTask_C_ReceiveExecuteAI, ControlledPawn) == 0x000008, "Member 'BTTask_SetBackupTask_C_ReceiveExecuteAI::ControlledPawn' has a wrong offset!");

}

