#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTTask_InitGoalOfMoveToTask

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_structs.hpp"
#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BTTask_InitGoalOfMoveToTask.BTTask_InitGoalOfMoveToTask_C
// 0x0080 (0x0128 - 0x00A8)
class UBTTask_InitGoalOfMoveToTask_C final : public UBTTask_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FBlackboardKeySelector                 CurrentTask_InKey;                                 // 0x00B0(0x0028)(Edit, BlueprintVisible)
	struct FBlackboardKeySelector                 GoalLocation_OutKey;                               // 0x00D8(0x0028)(Edit, BlueprintVisible)
	struct FBlackboardKeySelector                 GoalActor_OutKey;                                  // 0x0100(0x0028)(Edit, BlueprintVisible)

public:
	void ExecuteUbergraph_BTTask_InitGoalOfMoveToTask(int32 EntryPoint);
	void ReceiveExecute(class AActor* OwnerActor);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BTTask_InitGoalOfMoveToTask_C">();
	}
	static class UBTTask_InitGoalOfMoveToTask_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTTask_InitGoalOfMoveToTask_C>();
	}
};
static_assert(alignof(UBTTask_InitGoalOfMoveToTask_C) == 0x000008, "Wrong alignment on UBTTask_InitGoalOfMoveToTask_C");
static_assert(sizeof(UBTTask_InitGoalOfMoveToTask_C) == 0x000128, "Wrong size on UBTTask_InitGoalOfMoveToTask_C");
static_assert(offsetof(UBTTask_InitGoalOfMoveToTask_C, UberGraphFrame) == 0x0000A8, "Member 'UBTTask_InitGoalOfMoveToTask_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBTTask_InitGoalOfMoveToTask_C, CurrentTask_InKey) == 0x0000B0, "Member 'UBTTask_InitGoalOfMoveToTask_C::CurrentTask_InKey' has a wrong offset!");
static_assert(offsetof(UBTTask_InitGoalOfMoveToTask_C, GoalLocation_OutKey) == 0x0000D8, "Member 'UBTTask_InitGoalOfMoveToTask_C::GoalLocation_OutKey' has a wrong offset!");
static_assert(offsetof(UBTTask_InitGoalOfMoveToTask_C, GoalActor_OutKey) == 0x000100, "Member 'UBTTask_InitGoalOfMoveToTask_C::GoalActor_OutKey' has a wrong offset!");

}

