#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTTask_CreateObjective_TakeItemFromStorage

#include "Basic.hpp"

#include "BTTask_CreateObjective_TakeItemFromStorage_classes.hpp"
#include "BTTask_CreateObjective_TakeItemFromStorage_parameters.hpp"


namespace SDK
{

// Function BTTask_CreateObjective_TakeItemFromStorage.BTTask_CreateObjective_TakeItemFromStorage_C.ExecuteUbergraph_BTTask_CreateObjective_TakeItemFromStorage
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBTTask_CreateObjective_TakeItemFromStorage_C::ExecuteUbergraph_BTTask_CreateObjective_TakeItemFromStorage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTTask_CreateObjective_TakeItemFromStorage_C", "ExecuteUbergraph_BTTask_CreateObjective_TakeItemFromStorage");

	Params::BTTask_CreateObjective_TakeItemFromStorage_C_ExecuteUbergraph_BTTask_CreateObjective_TakeItemFromStorage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BTTask_CreateObjective_TakeItemFromStorage.BTTask_CreateObjective_TakeItemFromStorage_C.ReceiveExecuteAI
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AAIController*                    OwnerController                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class APawn*                            ControlledPawn                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBTTask_CreateObjective_TakeItemFromStorage_C::ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTTask_CreateObjective_TakeItemFromStorage_C", "ReceiveExecuteAI");

	Params::BTTask_CreateObjective_TakeItemFromStorage_C_ReceiveExecuteAI Parms{};

	Parms.OwnerController = OwnerController;
	Parms.ControlledPawn = ControlledPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BTTask_CreateObjective_TakeItemFromStorage.BTTask_CreateObjective_TakeItemFromStorage_C.DoExecute
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AAIController*                    Controller                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   bSuccess                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBTTask_CreateObjective_TakeItemFromStorage_C::DoExecute(class AAIController* Controller, bool* bSuccess)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTTask_CreateObjective_TakeItemFromStorage_C", "DoExecute");

	Params::BTTask_CreateObjective_TakeItemFromStorage_C_DoExecute Parms{};

	Parms.Controller = Controller;

	UObject::ProcessEvent(Func, &Parms);

	if (bSuccess != nullptr)
		*bSuccess = Parms.bSuccess;
}

}

