#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EInputActions

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EInputActions.EInputActions
// NumValues: 0x0005
enum class EInputActions : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	EInputActions_MAX                        = 4,
};

}

