#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LiveLink

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// ScriptStruct LiveLink.AnimNode_LiveLinkPose
// 0x0028 (0x0058 - 0x0030)
struct FAnimNode_LiveLinkPose final : public FAnimNode_Base
{
public:
	class FName                                   SubjectName;                                       // 0x0030(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class ULiveLinkRetargetAsset>     RetargetAsset;                                     // 0x0038(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoClear, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class ULiveLinkRetargetAsset*                 CurrentRetargetAsset;                              // 0x0040(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_48[0x10];                                      // 0x0048(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FAnimNode_LiveLinkPose) == 0x000008, "Wrong alignment on FAnimNode_LiveLinkPose");
static_assert(sizeof(FAnimNode_LiveLinkPose) == 0x000058, "Wrong size on FAnimNode_LiveLinkPose");
static_assert(offsetof(FAnimNode_LiveLinkPose, SubjectName) == 0x000030, "Member 'FAnimNode_LiveLinkPose::SubjectName' has a wrong offset!");
static_assert(offsetof(FAnimNode_LiveLinkPose, RetargetAsset) == 0x000038, "Member 'FAnimNode_LiveLinkPose::RetargetAsset' has a wrong offset!");
static_assert(offsetof(FAnimNode_LiveLinkPose, CurrentRetargetAsset) == 0x000040, "Member 'FAnimNode_LiveLinkPose::CurrentRetargetAsset' has a wrong offset!");

// ScriptStruct LiveLink.LiveLinkInstanceProxy
// 0x0050 (0x0580 - 0x0530)
struct FLiveLinkInstanceProxy final : public FAnimInstanceProxy
{
public:
	uint8                                         Pad_530[0x50];                                     // 0x0530(0x0050)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FLiveLinkInstanceProxy) == 0x000010, "Wrong alignment on FLiveLinkInstanceProxy");
static_assert(sizeof(FLiveLinkInstanceProxy) == 0x000580, "Wrong size on FLiveLinkInstanceProxy");

// ScriptStruct LiveLink.LiveLinkRetargetAssetReference
// 0x0008 (0x0008 - 0x0000)
struct FLiveLinkRetargetAssetReference final
{
public:
	class ULiveLinkRetargetAsset*                 CurrentRetargetAsset;                              // 0x0000(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
};
static_assert(alignof(FLiveLinkRetargetAssetReference) == 0x000008, "Wrong alignment on FLiveLinkRetargetAssetReference");
static_assert(sizeof(FLiveLinkRetargetAssetReference) == 0x000008, "Wrong size on FLiveLinkRetargetAssetReference");
static_assert(offsetof(FLiveLinkRetargetAssetReference, CurrentRetargetAsset) == 0x000000, "Member 'FLiveLinkRetargetAssetReference::CurrentRetargetAsset' has a wrong offset!");

// ScriptStruct LiveLink.LiveLinkVirtualSubject
// 0x0060 (0x0060 - 0x0000)
struct FLiveLinkVirtualSubject final
{
public:
	TArray<class FName>                           Subjects;                                          // 0x0000(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_10[0x10];                                      // 0x0010(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGuid                                  Source;                                            // 0x0020(0x0010)(Edit, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_30[0x30];                                      // 0x0030(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FLiveLinkVirtualSubject) == 0x000008, "Wrong alignment on FLiveLinkVirtualSubject");
static_assert(sizeof(FLiveLinkVirtualSubject) == 0x000060, "Wrong size on FLiveLinkVirtualSubject");
static_assert(offsetof(FLiveLinkVirtualSubject, Subjects) == 0x000000, "Member 'FLiveLinkVirtualSubject::Subjects' has a wrong offset!");
static_assert(offsetof(FLiveLinkVirtualSubject, Source) == 0x000020, "Member 'FLiveLinkVirtualSubject::Source' has a wrong offset!");

}

