#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SaveGameMod

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "ActorSaveStructure_structs.hpp"
#include "RemoveFoliageSaveStructure_structs.hpp"
#include "FoliageSaveStructure_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SaveGameMod.SaveGameMod_C
// 0x0098 (0x00C0 - 0x0028)
class USaveGameMod_C final : public USaveGame
{
public:
	TArray<struct FActorSaveStructure>            Actors;                                            // 0x0028(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FString                                 Name_0;                                            // 0x0038(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	struct FDateTime                              Date;                                              // 0x0048(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	int32                                         Seconds;                                           // 0x0050(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Minutes;                                           // 0x0054(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Hours;                                             // 0x0058(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Rate;                                              // 0x005C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Paused;                                            // 0x0060(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFoliageSaveStructure>          Foliages;                                          // 0x0068(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, SaveGame, ContainsInstancedReference)
	TArray<struct FRemoveFoliageSaveStructure>    ToRemoveFoliage;                                   // 0x0078(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	struct FLinearColor                           Color;                                             // 0x0088(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        EditorMusic;                                       // 0x0098(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Speed;                                             // 0x00A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        FOV;                                               // 0x00A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          SplineRead;                                        // 0x00B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B1[0x3];                                       // 0x00B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         AssetIDs;                                          // 0x00B4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Welcome;                                           // 0x00B8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SaveGameMod_C">();
	}
	static class USaveGameMod_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USaveGameMod_C>();
	}
};
static_assert(alignof(USaveGameMod_C) == 0x000008, "Wrong alignment on USaveGameMod_C");
static_assert(sizeof(USaveGameMod_C) == 0x0000C0, "Wrong size on USaveGameMod_C");
static_assert(offsetof(USaveGameMod_C, Actors) == 0x000028, "Member 'USaveGameMod_C::Actors' has a wrong offset!");
static_assert(offsetof(USaveGameMod_C, Name_0) == 0x000038, "Member 'USaveGameMod_C::Name_0' has a wrong offset!");
static_assert(offsetof(USaveGameMod_C, Date) == 0x000048, "Member 'USaveGameMod_C::Date' has a wrong offset!");
static_assert(offsetof(USaveGameMod_C, Seconds) == 0x000050, "Member 'USaveGameMod_C::Seconds' has a wrong offset!");
static_assert(offsetof(USaveGameMod_C, Minutes) == 0x000054, "Member 'USaveGameMod_C::Minutes' has a wrong offset!");
static_assert(offsetof(USaveGameMod_C, Hours) == 0x000058, "Member 'USaveGameMod_C::Hours' has a wrong offset!");
static_assert(offsetof(USaveGameMod_C, Rate) == 0x00005C, "Member 'USaveGameMod_C::Rate' has a wrong offset!");
static_assert(offsetof(USaveGameMod_C, Paused) == 0x000060, "Member 'USaveGameMod_C::Paused' has a wrong offset!");
static_assert(offsetof(USaveGameMod_C, Foliages) == 0x000068, "Member 'USaveGameMod_C::Foliages' has a wrong offset!");
static_assert(offsetof(USaveGameMod_C, ToRemoveFoliage) == 0x000078, "Member 'USaveGameMod_C::ToRemoveFoliage' has a wrong offset!");
static_assert(offsetof(USaveGameMod_C, Color) == 0x000088, "Member 'USaveGameMod_C::Color' has a wrong offset!");
static_assert(offsetof(USaveGameMod_C, EditorMusic) == 0x000098, "Member 'USaveGameMod_C::EditorMusic' has a wrong offset!");
static_assert(offsetof(USaveGameMod_C, Speed) == 0x0000A0, "Member 'USaveGameMod_C::Speed' has a wrong offset!");
static_assert(offsetof(USaveGameMod_C, FOV) == 0x0000A8, "Member 'USaveGameMod_C::FOV' has a wrong offset!");
static_assert(offsetof(USaveGameMod_C, SplineRead) == 0x0000B0, "Member 'USaveGameMod_C::SplineRead' has a wrong offset!");
static_assert(offsetof(USaveGameMod_C, AssetIDs) == 0x0000B4, "Member 'USaveGameMod_C::AssetIDs' has a wrong offset!");
static_assert(offsetof(USaveGameMod_C, Welcome) == 0x0000B8, "Member 'USaveGameMod_C::Welcome' has a wrong offset!");

}

