#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Start

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Start.Start_C
// 0x0010 (0x03A0 - 0x0390)
class AStart_C final : public ALevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0390(0x0008)(Transient, DuplicateTransient)
	class UBP_WidgetStartMenu_C*                  WidgetStartMenu;                                   // 0x0398(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Start(int32 EntryPoint);
	void ReceiveDestroyed();
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Start_C">();
	}
	static class AStart_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AStart_C>();
	}
};
static_assert(alignof(AStart_C) == 0x000008, "Wrong alignment on AStart_C");
static_assert(sizeof(AStart_C) == 0x0003A0, "Wrong size on AStart_C");
static_assert(offsetof(AStart_C, UberGraphFrame) == 0x000390, "Member 'AStart_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AStart_C, WidgetStartMenu) == 0x000398, "Member 'AStart_C::WidgetStartMenu' has a wrong offset!");

}

