#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_FakeExpandableButton

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_FakeExpandableButton.WBP_FakeExpandableButton_C.ExecuteUbergraph_WBP_FakeExpandableButton
// 0x001C (0x001C - 0x0000)
struct WBP_FakeExpandableButton_C_ExecuteUbergraph_WBP_FakeExpandableButton final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Temp_real_Variable;                                // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_real_Variable_1;                              // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Select_Default;                             // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_bState;                         // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_FakeExpandableButton_C_ExecuteUbergraph_WBP_FakeExpandableButton) == 0x000004, "Wrong alignment on WBP_FakeExpandableButton_C_ExecuteUbergraph_WBP_FakeExpandableButton");
static_assert(sizeof(WBP_FakeExpandableButton_C_ExecuteUbergraph_WBP_FakeExpandableButton) == 0x00001C, "Wrong size on WBP_FakeExpandableButton_C_ExecuteUbergraph_WBP_FakeExpandableButton");
static_assert(offsetof(WBP_FakeExpandableButton_C_ExecuteUbergraph_WBP_FakeExpandableButton, EntryPoint) == 0x000000, "Member 'WBP_FakeExpandableButton_C_ExecuteUbergraph_WBP_FakeExpandableButton::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_FakeExpandableButton_C_ExecuteUbergraph_WBP_FakeExpandableButton, Temp_bool_Variable) == 0x000004, "Member 'WBP_FakeExpandableButton_C_ExecuteUbergraph_WBP_FakeExpandableButton::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_FakeExpandableButton_C_ExecuteUbergraph_WBP_FakeExpandableButton, Temp_real_Variable) == 0x000008, "Member 'WBP_FakeExpandableButton_C_ExecuteUbergraph_WBP_FakeExpandableButton::Temp_real_Variable' has a wrong offset!");
static_assert(offsetof(WBP_FakeExpandableButton_C_ExecuteUbergraph_WBP_FakeExpandableButton, Temp_real_Variable_1) == 0x00000C, "Member 'WBP_FakeExpandableButton_C_ExecuteUbergraph_WBP_FakeExpandableButton::Temp_real_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_FakeExpandableButton_C_ExecuteUbergraph_WBP_FakeExpandableButton, K2Node_Event_IsDesignTime) == 0x000010, "Member 'WBP_FakeExpandableButton_C_ExecuteUbergraph_WBP_FakeExpandableButton::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(WBP_FakeExpandableButton_C_ExecuteUbergraph_WBP_FakeExpandableButton, K2Node_Select_Default) == 0x000014, "Member 'WBP_FakeExpandableButton_C_ExecuteUbergraph_WBP_FakeExpandableButton::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WBP_FakeExpandableButton_C_ExecuteUbergraph_WBP_FakeExpandableButton, CallFunc_Not_PreBool_ReturnValue) == 0x000018, "Member 'WBP_FakeExpandableButton_C_ExecuteUbergraph_WBP_FakeExpandableButton::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_FakeExpandableButton_C_ExecuteUbergraph_WBP_FakeExpandableButton, K2Node_CustomEvent_bState) == 0x000019, "Member 'WBP_FakeExpandableButton_C_ExecuteUbergraph_WBP_FakeExpandableButton::K2Node_CustomEvent_bState' has a wrong offset!");

// Function WBP_FakeExpandableButton.WBP_FakeExpandableButton_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_FakeExpandableButton_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_FakeExpandableButton_C_PreConstruct) == 0x000001, "Wrong alignment on WBP_FakeExpandableButton_C_PreConstruct");
static_assert(sizeof(WBP_FakeExpandableButton_C_PreConstruct) == 0x000001, "Wrong size on WBP_FakeExpandableButton_C_PreConstruct");
static_assert(offsetof(WBP_FakeExpandableButton_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WBP_FakeExpandableButton_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WBP_FakeExpandableButton.WBP_FakeExpandableButton_C.SetState
// 0x0001 (0x0001 - 0x0000)
struct WBP_FakeExpandableButton_C_SetState final
{
public:
	bool                                          bState_0;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_FakeExpandableButton_C_SetState) == 0x000001, "Wrong alignment on WBP_FakeExpandableButton_C_SetState");
static_assert(sizeof(WBP_FakeExpandableButton_C_SetState) == 0x000001, "Wrong size on WBP_FakeExpandableButton_C_SetState");
static_assert(offsetof(WBP_FakeExpandableButton_C_SetState, bState_0) == 0x000000, "Member 'WBP_FakeExpandableButton_C_SetState::bState_0' has a wrong offset!");

}

