#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_QuickAccessCategory

#include "Basic.hpp"

#include "HelloNeighbor3_structs.hpp"


namespace SDK::Params
{

// Function WBP_QuickAccessCategory.WBP_QuickAccessCategory_C.ConstructSlots
// 0x0004 (0x0004 - 0x0000)
struct WBP_QuickAccessCategory_C_ConstructSlots final
{
public:
	int32                                         NumSlots;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuickAccessCategory_C_ConstructSlots) == 0x000004, "Wrong alignment on WBP_QuickAccessCategory_C_ConstructSlots");
static_assert(sizeof(WBP_QuickAccessCategory_C_ConstructSlots) == 0x000004, "Wrong size on WBP_QuickAccessCategory_C_ConstructSlots");
static_assert(offsetof(WBP_QuickAccessCategory_C_ConstructSlots, NumSlots) == 0x000000, "Member 'WBP_QuickAccessCategory_C_ConstructSlots::NumSlots' has a wrong offset!");

// Function WBP_QuickAccessCategory.WBP_QuickAccessCategory_C.ExecuteUbergraph_WBP_QuickAccessCategory
// 0x0208 (0x0208 - 0x0000)
struct WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_CustomEvent_User_Specified_Scale;           // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_ItemSlotInventory_C*               CallFunc_SpawnObject_ReturnValue;                  // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x0020(0x0010)()
	int32                                         K2Node_Event_NumSlots;                             // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable_1;                              // 0x0040(0x0010)()
	struct FInstanceSlotPosition                  K2Node_MakeStruct_InstanceSlotPosition;            // 0x0050(0x001C)(NoDestructor)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x006C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6D[0x3];                                       // 0x006D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_74[0x4];                                       // 0x0074(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable_2;                              // 0x0078(0x0010)()
	int32                                         CallFunc_Percent_IntInt_ReturnValue;               // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8C[0x4];                                       // 0x008C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable_3;                              // 0x0090(0x0010)()
	class FText                                   Temp_text_Variable_4;                              // 0x00A0(0x0010)()
	int32                                         CallFunc_Divide_IntInt_ReturnValue;                // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_Index_1;                              // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FInventoryItemInfo                     K2Node_Event_ItemInfo;                             // 0x00B8(0x0038)()
	class UUniformGridSlot*                       CallFunc_AddChildToUniformGrid_ReturnValue;        // 0x00F0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPlayerInventoryManagerComponent*       K2Node_Event_InventoryManager;                     // 0x00F8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FInventoryCategory                     K2Node_Event_CategoryConfig;                       // 0x0100(0x0030)()
	class UWBP_Inventory_C*                       K2Node_Event_Inventory;                            // 0x0130(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                CallFunc_GetChildAt_ReturnValue;                   // 0x0138(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_ItemSlotInventory_C*               K2Node_DynamicCast_AsWBP_Item_Slot_Inventory;      // 0x0140(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_149[0x7];                                      // 0x0149(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue;               // 0x0150(0x0010)(ReferenceParm, ContainsInstancedReference)
	struct FInstanceSlotPosition                  K2Node_MakeStruct_InstanceSlotPosition_1;          // 0x0160(0x001C)(NoDestructor)
	uint8                                         Pad_17C[0x4];                                      // 0x017C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item;                           // 0x0180(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0188(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_18C[0x4];                                      // 0x018C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_ItemSlotInventory_C*               K2Node_DynamicCast_AsWBP_Item_Slot_Inventory_1;    // 0x0190(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0198(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0199(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19A[0x6];                                      // 0x019A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable_5;                              // 0x01A0(0x0010)()
	EPlayerInventoryState                         Temp_byte_Variable;                                // 0x01B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1B1[0x3];                                      // 0x01B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_Event_Index;                                // 0x01B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPlayerInventoryState                         K2Node_Event_NewState;                             // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1B9[0x7];                                      // 0x01B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetChildAt_ReturnValue_1;                 // 0x01C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_ItemSlotInventory_C*               K2Node_DynamicCast_AsWBP_Item_Slot_Inventory_2;    // 0x01C8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x01D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D1[0x7];                                      // 0x01D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Select_Default;                             // 0x01D8(0x0010)()
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x01E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetChildrenCount_ReturnValue;             // 0x01EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_1;            // 0x01F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_2;            // 0x01F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Clamp_ReturnValue;                        // 0x01F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetChildrenCount_ReturnValue_1;           // 0x01FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_3;            // 0x0200(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Clamp_ReturnValue_1;                      // 0x0204(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory) == 0x000008, "Wrong alignment on WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory");
static_assert(sizeof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory) == 0x000208, "Wrong size on WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, EntryPoint) == 0x000000, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, K2Node_CustomEvent_User_Specified_Scale) == 0x000004, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::K2Node_CustomEvent_User_Specified_Scale' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, CallFunc_SpawnObject_ReturnValue) == 0x000008, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, Temp_int_Loop_Counter_Variable) == 0x000010, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, CallFunc_Add_IntInt_ReturnValue) == 0x000014, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, Temp_int_Array_Index_Variable) == 0x000018, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, Temp_text_Variable) == 0x000020, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, K2Node_Event_NumSlots) == 0x000030, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::K2Node_Event_NumSlots' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, CallFunc_Subtract_IntInt_ReturnValue) == 0x000034, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, Temp_int_Variable) == 0x000038, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, Temp_text_Variable_1) == 0x000040, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::Temp_text_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, K2Node_MakeStruct_InstanceSlotPosition) == 0x000050, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::K2Node_MakeStruct_InstanceSlotPosition' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, CallFunc_LessEqual_IntInt_ReturnValue) == 0x00006C, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, CallFunc_Add_IntInt_ReturnValue_1) == 0x000070, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, Temp_text_Variable_2) == 0x000078, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::Temp_text_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, CallFunc_Percent_IntInt_ReturnValue) == 0x000088, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::CallFunc_Percent_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, Temp_text_Variable_3) == 0x000090, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::Temp_text_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, Temp_text_Variable_4) == 0x0000A0, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::Temp_text_Variable_4' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, CallFunc_Divide_IntInt_ReturnValue) == 0x0000B0, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::CallFunc_Divide_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, K2Node_Event_Index_1) == 0x0000B4, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::K2Node_Event_Index_1' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, K2Node_Event_ItemInfo) == 0x0000B8, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::K2Node_Event_ItemInfo' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, CallFunc_AddChildToUniformGrid_ReturnValue) == 0x0000F0, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::CallFunc_AddChildToUniformGrid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, K2Node_Event_InventoryManager) == 0x0000F8, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::K2Node_Event_InventoryManager' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, K2Node_Event_CategoryConfig) == 0x000100, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::K2Node_Event_CategoryConfig' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, K2Node_Event_Inventory) == 0x000130, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::K2Node_Event_Inventory' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, CallFunc_GetChildAt_ReturnValue) == 0x000138, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::CallFunc_GetChildAt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, K2Node_DynamicCast_AsWBP_Item_Slot_Inventory) == 0x000140, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::K2Node_DynamicCast_AsWBP_Item_Slot_Inventory' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, K2Node_DynamicCast_bSuccess) == 0x000148, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, CallFunc_GetAllChildren_ReturnValue) == 0x000150, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::CallFunc_GetAllChildren_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, K2Node_MakeStruct_InstanceSlotPosition_1) == 0x000160, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::K2Node_MakeStruct_InstanceSlotPosition_1' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, CallFunc_Array_Get_Item) == 0x000180, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, CallFunc_Array_Length_ReturnValue) == 0x000188, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, K2Node_DynamicCast_AsWBP_Item_Slot_Inventory_1) == 0x000190, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::K2Node_DynamicCast_AsWBP_Item_Slot_Inventory_1' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, K2Node_DynamicCast_bSuccess_1) == 0x000198, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, CallFunc_Less_IntInt_ReturnValue) == 0x000199, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, Temp_text_Variable_5) == 0x0001A0, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::Temp_text_Variable_5' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, Temp_byte_Variable) == 0x0001B0, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, K2Node_Event_Index) == 0x0001B4, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::K2Node_Event_Index' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, K2Node_Event_NewState) == 0x0001B8, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::K2Node_Event_NewState' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, CallFunc_GetChildAt_ReturnValue_1) == 0x0001C0, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::CallFunc_GetChildAt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, K2Node_DynamicCast_AsWBP_Item_Slot_Inventory_2) == 0x0001C8, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::K2Node_DynamicCast_AsWBP_Item_Slot_Inventory_2' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, K2Node_DynamicCast_bSuccess_2) == 0x0001D0, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, K2Node_Select_Default) == 0x0001D8, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, CallFunc_Add_IntInt_ReturnValue_2) == 0x0001E8, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, CallFunc_GetChildrenCount_ReturnValue) == 0x0001EC, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::CallFunc_GetChildrenCount_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, CallFunc_Subtract_IntInt_ReturnValue_1) == 0x0001F0, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::CallFunc_Subtract_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, CallFunc_Subtract_IntInt_ReturnValue_2) == 0x0001F4, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::CallFunc_Subtract_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, CallFunc_Clamp_ReturnValue) == 0x0001F8, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::CallFunc_Clamp_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, CallFunc_GetChildrenCount_ReturnValue_1) == 0x0001FC, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::CallFunc_GetChildrenCount_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, CallFunc_Subtract_IntInt_ReturnValue_3) == 0x000200, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::CallFunc_Subtract_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory, CallFunc_Clamp_ReturnValue_1) == 0x000204, "Member 'WBP_QuickAccessCategory_C_ExecuteUbergraph_WBP_QuickAccessCategory::CallFunc_Clamp_ReturnValue_1' has a wrong offset!");

// Function WBP_QuickAccessCategory.WBP_QuickAccessCategory_C.GetAllSlots
// 0x0068 (0x0068 - 0x0000)
struct WBP_QuickAccessCategory_C_GetAllSlots final
{
public:
	TArray<class UWBP_ItemSlotInventory_C*>       OutSlots;                                          // 0x0000(0x0010)(Parm, OutParm, ContainsInstancedReference)
	TArray<class UWBP_ItemSlotInventory_C*>       OutArray;                                          // 0x0010(0x0010)(Edit, BlueprintVisible, ContainsInstancedReference)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue;               // 0x0030(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item;                           // 0x0048(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_ItemSlotInventory_C*               K2Node_DynamicCast_AsWBP_Item_Slot_Inventory;      // 0x0058(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_61[0x3];                                       // 0x0061(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_AddUnique_ReturnValue;              // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuickAccessCategory_C_GetAllSlots) == 0x000008, "Wrong alignment on WBP_QuickAccessCategory_C_GetAllSlots");
static_assert(sizeof(WBP_QuickAccessCategory_C_GetAllSlots) == 0x000068, "Wrong size on WBP_QuickAccessCategory_C_GetAllSlots");
static_assert(offsetof(WBP_QuickAccessCategory_C_GetAllSlots, OutSlots) == 0x000000, "Member 'WBP_QuickAccessCategory_C_GetAllSlots::OutSlots' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_GetAllSlots, OutArray) == 0x000010, "Member 'WBP_QuickAccessCategory_C_GetAllSlots::OutArray' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_GetAllSlots, Temp_int_Array_Index_Variable) == 0x000020, "Member 'WBP_QuickAccessCategory_C_GetAllSlots::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_GetAllSlots, Temp_int_Loop_Counter_Variable) == 0x000024, "Member 'WBP_QuickAccessCategory_C_GetAllSlots::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_GetAllSlots, CallFunc_Add_IntInt_ReturnValue) == 0x000028, "Member 'WBP_QuickAccessCategory_C_GetAllSlots::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_GetAllSlots, CallFunc_GetAllChildren_ReturnValue) == 0x000030, "Member 'WBP_QuickAccessCategory_C_GetAllSlots::CallFunc_GetAllChildren_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_GetAllSlots, CallFunc_Array_Length_ReturnValue) == 0x000040, "Member 'WBP_QuickAccessCategory_C_GetAllSlots::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_GetAllSlots, CallFunc_Array_Get_Item) == 0x000048, "Member 'WBP_QuickAccessCategory_C_GetAllSlots::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_GetAllSlots, CallFunc_Less_IntInt_ReturnValue) == 0x000050, "Member 'WBP_QuickAccessCategory_C_GetAllSlots::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_GetAllSlots, K2Node_DynamicCast_AsWBP_Item_Slot_Inventory) == 0x000058, "Member 'WBP_QuickAccessCategory_C_GetAllSlots::K2Node_DynamicCast_AsWBP_Item_Slot_Inventory' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_GetAllSlots, K2Node_DynamicCast_bSuccess) == 0x000060, "Member 'WBP_QuickAccessCategory_C_GetAllSlots::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_GetAllSlots, CallFunc_Array_AddUnique_ReturnValue) == 0x000064, "Member 'WBP_QuickAccessCategory_C_GetAllSlots::CallFunc_Array_AddUnique_ReturnValue' has a wrong offset!");

// Function WBP_QuickAccessCategory.WBP_QuickAccessCategory_C.GetChild
// 0x0028 (0x0028 - 0x0000)
struct WBP_QuickAccessCategory_C_GetChild final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_ItemSlotInventory_C*               Slot_0;                                            // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                CallFunc_GetChildAt_ReturnValue;                   // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_ItemSlotInventory_C*               K2Node_DynamicCast_AsWBP_Item_Slot_Inventory;      // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuickAccessCategory_C_GetChild) == 0x000008, "Wrong alignment on WBP_QuickAccessCategory_C_GetChild");
static_assert(sizeof(WBP_QuickAccessCategory_C_GetChild) == 0x000028, "Wrong size on WBP_QuickAccessCategory_C_GetChild");
static_assert(offsetof(WBP_QuickAccessCategory_C_GetChild, Index_0) == 0x000000, "Member 'WBP_QuickAccessCategory_C_GetChild::Index_0' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_GetChild, Slot_0) == 0x000008, "Member 'WBP_QuickAccessCategory_C_GetChild::Slot_0' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_GetChild, CallFunc_GetChildAt_ReturnValue) == 0x000010, "Member 'WBP_QuickAccessCategory_C_GetChild::CallFunc_GetChildAt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_GetChild, K2Node_DynamicCast_AsWBP_Item_Slot_Inventory) == 0x000018, "Member 'WBP_QuickAccessCategory_C_GetChild::K2Node_DynamicCast_AsWBP_Item_Slot_Inventory' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_GetChild, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'WBP_QuickAccessCategory_C_GetChild::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function WBP_QuickAccessCategory.WBP_QuickAccessCategory_C.Init
// 0x0040 (0x0040 - 0x0000)
struct WBP_QuickAccessCategory_C_Init final
{
public:
	class UPlayerInventoryManagerComponent*       InventoryManager;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FInventoryCategory                     CategoryConfig;                                    // 0x0008(0x0030)(BlueprintVisible, BlueprintReadOnly, Parm)
	class UWBP_Inventory_C*                       Inventory;                                         // 0x0038(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuickAccessCategory_C_Init) == 0x000008, "Wrong alignment on WBP_QuickAccessCategory_C_Init");
static_assert(sizeof(WBP_QuickAccessCategory_C_Init) == 0x000040, "Wrong size on WBP_QuickAccessCategory_C_Init");
static_assert(offsetof(WBP_QuickAccessCategory_C_Init, InventoryManager) == 0x000000, "Member 'WBP_QuickAccessCategory_C_Init::InventoryManager' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_Init, CategoryConfig) == 0x000008, "Member 'WBP_QuickAccessCategory_C_Init::CategoryConfig' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_Init, Inventory) == 0x000038, "Member 'WBP_QuickAccessCategory_C_Init::Inventory' has a wrong offset!");

// Function WBP_QuickAccessCategory.WBP_QuickAccessCategory_C.RemoveItem
// 0x0004 (0x0004 - 0x0000)
struct WBP_QuickAccessCategory_C_RemoveItem final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuickAccessCategory_C_RemoveItem) == 0x000004, "Wrong alignment on WBP_QuickAccessCategory_C_RemoveItem");
static_assert(sizeof(WBP_QuickAccessCategory_C_RemoveItem) == 0x000004, "Wrong size on WBP_QuickAccessCategory_C_RemoveItem");
static_assert(offsetof(WBP_QuickAccessCategory_C_RemoveItem, Index_0) == 0x000000, "Member 'WBP_QuickAccessCategory_C_RemoveItem::Index_0' has a wrong offset!");

// Function WBP_QuickAccessCategory.WBP_QuickAccessCategory_C.SetItem
// 0x0040 (0x0040 - 0x0000)
struct WBP_QuickAccessCategory_C_SetItem final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FInventoryItemInfo                     ItemInfo;                                          // 0x0008(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(WBP_QuickAccessCategory_C_SetItem) == 0x000008, "Wrong alignment on WBP_QuickAccessCategory_C_SetItem");
static_assert(sizeof(WBP_QuickAccessCategory_C_SetItem) == 0x000040, "Wrong size on WBP_QuickAccessCategory_C_SetItem");
static_assert(offsetof(WBP_QuickAccessCategory_C_SetItem, Index_0) == 0x000000, "Member 'WBP_QuickAccessCategory_C_SetItem::Index_0' has a wrong offset!");
static_assert(offsetof(WBP_QuickAccessCategory_C_SetItem, ItemInfo) == 0x000008, "Member 'WBP_QuickAccessCategory_C_SetItem::ItemInfo' has a wrong offset!");

// Function WBP_QuickAccessCategory.WBP_QuickAccessCategory_C.SetQuickAccessScale
// 0x0004 (0x0004 - 0x0000)
struct WBP_QuickAccessCategory_C_SetQuickAccessScale final
{
public:
	float                                         User_Specified_Scale;                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuickAccessCategory_C_SetQuickAccessScale) == 0x000004, "Wrong alignment on WBP_QuickAccessCategory_C_SetQuickAccessScale");
static_assert(sizeof(WBP_QuickAccessCategory_C_SetQuickAccessScale) == 0x000004, "Wrong size on WBP_QuickAccessCategory_C_SetQuickAccessScale");
static_assert(offsetof(WBP_QuickAccessCategory_C_SetQuickAccessScale, User_Specified_Scale) == 0x000000, "Member 'WBP_QuickAccessCategory_C_SetQuickAccessScale::User_Specified_Scale' has a wrong offset!");

// Function WBP_QuickAccessCategory.WBP_QuickAccessCategory_C.SetState
// 0x0001 (0x0001 - 0x0000)
struct WBP_QuickAccessCategory_C_SetState final
{
public:
	EPlayerInventoryState                         NewState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuickAccessCategory_C_SetState) == 0x000001, "Wrong alignment on WBP_QuickAccessCategory_C_SetState");
static_assert(sizeof(WBP_QuickAccessCategory_C_SetState) == 0x000001, "Wrong size on WBP_QuickAccessCategory_C_SetState");
static_assert(offsetof(WBP_QuickAccessCategory_C_SetState, NewState) == 0x000000, "Member 'WBP_QuickAccessCategory_C_SetState::NewState' has a wrong offset!");

}

