#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MenuSelectButon

#include "Basic.hpp"

#include "AkAudio_structs.hpp"
#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "HelloNeighbor2_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MenuSelectButon.WBP_MenuSelectButon_C
// 0x00D0 (0x03D8 - 0x0308)
class UWBP_MenuSelectButon_C final : public UBaseMenuElement
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0308(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                Border_0;                                          // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 imgLeft;                                           // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 imgRight;                                          // 0x0320(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULocalizationText*                      ltOptionName;                                      // 0x0328(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             txtOptionValue;                                    // 0x0330(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   Option_name;                                       // 0x0338(0x0018)(Edit, BlueprintVisible)
	TArray<class FText>                           Values;                                            // 0x0350(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                         ActiveIndex;                                       // 0x0360(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_364[0x4];                                      // 0x0364(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(class FText Value, int32 IndexValue)> OnChangedValue;              // 0x0368(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	int32                                         TextSize;                                          // 0x0378(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   LocalizedRow;                                      // 0x037C(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	float                                         In_Brush_Margin_Left;                              // 0x0384(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            HoverTextColor;                                    // 0x0388(0x0028)(Edit, BlueprintVisible)
	struct FSlateColor                            UnHoverTextColor;                                  // 0x03B0(0x0028)(Edit, BlueprintVisible)

public:
	void ExecuteUbergraph_WBP_MenuSelectButon(int32 EntryPoint);
	void OnUnselected();
	void OnSelected();
	void PreConstruct(bool IsDesignTime);
	void Construct();
	void MakeStep(bool Forward_);
	void InputForward();
	void InputBackward();
	void SetNewValue(const class FText& NewValue, bool CallUpdate);
	struct FEventReply OnLeftPressed(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	struct FEventReply OnRightPressed(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	void SetNewValueNumber(int32 NewValueNumber);
	void IniSelect(const TDelegate<void(class FText Value, int32 IndexValue)>& OnChangeDelegate, int32 Value, const TArray<class FText>& SourceArray);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MenuSelectButon_C">();
	}
	static class UWBP_MenuSelectButon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MenuSelectButon_C>();
	}
};
static_assert(alignof(UWBP_MenuSelectButon_C) == 0x000008, "Wrong alignment on UWBP_MenuSelectButon_C");
static_assert(sizeof(UWBP_MenuSelectButon_C) == 0x0003D8, "Wrong size on UWBP_MenuSelectButon_C");
static_assert(offsetof(UWBP_MenuSelectButon_C, UberGraphFrame) == 0x000308, "Member 'UWBP_MenuSelectButon_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_MenuSelectButon_C, Border_0) == 0x000310, "Member 'UWBP_MenuSelectButon_C::Border_0' has a wrong offset!");
static_assert(offsetof(UWBP_MenuSelectButon_C, imgLeft) == 0x000318, "Member 'UWBP_MenuSelectButon_C::imgLeft' has a wrong offset!");
static_assert(offsetof(UWBP_MenuSelectButon_C, imgRight) == 0x000320, "Member 'UWBP_MenuSelectButon_C::imgRight' has a wrong offset!");
static_assert(offsetof(UWBP_MenuSelectButon_C, ltOptionName) == 0x000328, "Member 'UWBP_MenuSelectButon_C::ltOptionName' has a wrong offset!");
static_assert(offsetof(UWBP_MenuSelectButon_C, txtOptionValue) == 0x000330, "Member 'UWBP_MenuSelectButon_C::txtOptionValue' has a wrong offset!");
static_assert(offsetof(UWBP_MenuSelectButon_C, Option_name) == 0x000338, "Member 'UWBP_MenuSelectButon_C::Option_name' has a wrong offset!");
static_assert(offsetof(UWBP_MenuSelectButon_C, Values) == 0x000350, "Member 'UWBP_MenuSelectButon_C::Values' has a wrong offset!");
static_assert(offsetof(UWBP_MenuSelectButon_C, ActiveIndex) == 0x000360, "Member 'UWBP_MenuSelectButon_C::ActiveIndex' has a wrong offset!");
static_assert(offsetof(UWBP_MenuSelectButon_C, OnChangedValue) == 0x000368, "Member 'UWBP_MenuSelectButon_C::OnChangedValue' has a wrong offset!");
static_assert(offsetof(UWBP_MenuSelectButon_C, TextSize) == 0x000378, "Member 'UWBP_MenuSelectButon_C::TextSize' has a wrong offset!");
static_assert(offsetof(UWBP_MenuSelectButon_C, LocalizedRow) == 0x00037C, "Member 'UWBP_MenuSelectButon_C::LocalizedRow' has a wrong offset!");
static_assert(offsetof(UWBP_MenuSelectButon_C, In_Brush_Margin_Left) == 0x000384, "Member 'UWBP_MenuSelectButon_C::In_Brush_Margin_Left' has a wrong offset!");
static_assert(offsetof(UWBP_MenuSelectButon_C, HoverTextColor) == 0x000388, "Member 'UWBP_MenuSelectButon_C::HoverTextColor' has a wrong offset!");
static_assert(offsetof(UWBP_MenuSelectButon_C, UnHoverTextColor) == 0x0003B0, "Member 'UWBP_MenuSelectButon_C::UnHoverTextColor' has a wrong offset!");

}

