#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MenuSelectButon

#include "Basic.hpp"

#include "WBP_MenuSelectButon_classes.hpp"
#include "WBP_MenuSelectButon_parameters.hpp"


namespace SDK
{

// Function WBP_MenuSelectButon.WBP_MenuSelectButon_C.ExecuteUbergraph_WBP_MenuSelectButon
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MenuSelectButon_C::ExecuteUbergraph_WBP_MenuSelectButon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MenuSelectButon_C", "ExecuteUbergraph_WBP_MenuSelectButon");

	Params::WBP_MenuSelectButon_C_ExecuteUbergraph_WBP_MenuSelectButon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MenuSelectButon.WBP_MenuSelectButon_C.OnUnselected
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UWBP_MenuSelectButon_C::OnUnselected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MenuSelectButon_C", "OnUnselected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MenuSelectButon.WBP_MenuSelectButon_C.OnSelected
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UWBP_MenuSelectButon_C::OnSelected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MenuSelectButon_C", "OnSelected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MenuSelectButon.WBP_MenuSelectButon_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_MenuSelectButon_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MenuSelectButon_C", "PreConstruct");

	Params::WBP_MenuSelectButon_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MenuSelectButon.WBP_MenuSelectButon_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_MenuSelectButon_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MenuSelectButon_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MenuSelectButon.WBP_MenuSelectButon_C.MakeStep
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Forward_                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_MenuSelectButon_C::MakeStep(bool Forward_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MenuSelectButon_C", "MakeStep");

	Params::WBP_MenuSelectButon_C_MakeStep Parms{};

	Parms.Forward_ = Forward_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MenuSelectButon.WBP_MenuSelectButon_C.InputForward
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_MenuSelectButon_C::InputForward()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MenuSelectButon_C", "InputForward");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MenuSelectButon.WBP_MenuSelectButon_C.InputBackward
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_MenuSelectButon_C::InputBackward()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MenuSelectButon_C", "InputBackward");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MenuSelectButon.WBP_MenuSelectButon_C.SetNewValue
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      NewValue                                               (BlueprintVisible, BlueprintReadOnly, Parm)
// bool                                    CallUpdate                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_MenuSelectButon_C::SetNewValue(const class FText& NewValue, bool CallUpdate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MenuSelectButon_C", "SetNewValue");

	Params::WBP_MenuSelectButon_C_SetNewValue Parms{};

	Parms.NewValue = std::move(NewValue);
	Parms.CallUpdate = CallUpdate;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MenuSelectButon.WBP_MenuSelectButon_C.OnLeftPressed
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_MenuSelectButon_C::OnLeftPressed(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MenuSelectButon_C", "OnLeftPressed");

	Params::WBP_MenuSelectButon_C_OnLeftPressed Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MenuSelectButon.WBP_MenuSelectButon_C.OnRightPressed
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_MenuSelectButon_C::OnRightPressed(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MenuSelectButon_C", "OnRightPressed");

	Params::WBP_MenuSelectButon_C_OnRightPressed Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_MenuSelectButon.WBP_MenuSelectButon_C.SetNewValueNumber
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   NewValueNumber                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MenuSelectButon_C::SetNewValueNumber(int32 NewValueNumber)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MenuSelectButon_C", "SetNewValueNumber");

	Params::WBP_MenuSelectButon_C_SetNewValueNumber Parms{};

	Parms.NewValueNumber = NewValueNumber;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MenuSelectButon.WBP_MenuSelectButon_C.IniSelect
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TDelegate<void(class FText Value, int32 IndexValue)>&OnChangeDelegate                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor)
// int32                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const TArray<class FText>&              SourceArray                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_MenuSelectButon_C::IniSelect(const TDelegate<void(class FText Value, int32 IndexValue)>& OnChangeDelegate, int32 Value, const TArray<class FText>& SourceArray)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MenuSelectButon_C", "IniSelect");

	Params::WBP_MenuSelectButon_C_IniSelect Parms{};

	Parms.OnChangeDelegate = OnChangeDelegate;
	Parms.Value = Value;
	Parms.SourceArray = std::move(SourceArray);

	UObject::ProcessEvent(Func, &Parms);
}

}

