#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MenuImageButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "HelloNeighbor2_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MenuImageButton.WBP_MenuImageButton_C
// 0x00C0 (0x03C8 - 0x0308)
class UWBP_MenuImageButton_C final : public UBaseMenuElement
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0308(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_196;                                         // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int32                                         TextSize;                                          // 0x0318(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31C[0x4];                                      // 0x031C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 LocalizedRow;                                      // 0x0320(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	float                                         In_Brush_Margin_Left;                              // 0x0330(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_334[0x4];                                      // 0x0334(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            ImageBrush;                                        // 0x0338(0x0088)(Edit, BlueprintVisible)
	bool                                          ZoomOnHover;                                       // 0x03C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3C1[0x3];                                      // 0x03C1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         ZoomValue;                                         // 0x03C4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_MenuImageButton(int32 EntryPoint);
	void Construct();
	void OnSelected();
	void PreConstruct(bool IsDesignTime);
	void OnUnselected();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MenuImageButton_C">();
	}
	static class UWBP_MenuImageButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MenuImageButton_C>();
	}
};
static_assert(alignof(UWBP_MenuImageButton_C) == 0x000008, "Wrong alignment on UWBP_MenuImageButton_C");
static_assert(sizeof(UWBP_MenuImageButton_C) == 0x0003C8, "Wrong size on UWBP_MenuImageButton_C");
static_assert(offsetof(UWBP_MenuImageButton_C, UberGraphFrame) == 0x000308, "Member 'UWBP_MenuImageButton_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_MenuImageButton_C, Image_196) == 0x000310, "Member 'UWBP_MenuImageButton_C::Image_196' has a wrong offset!");
static_assert(offsetof(UWBP_MenuImageButton_C, TextSize) == 0x000318, "Member 'UWBP_MenuImageButton_C::TextSize' has a wrong offset!");
static_assert(offsetof(UWBP_MenuImageButton_C, LocalizedRow) == 0x000320, "Member 'UWBP_MenuImageButton_C::LocalizedRow' has a wrong offset!");
static_assert(offsetof(UWBP_MenuImageButton_C, In_Brush_Margin_Left) == 0x000330, "Member 'UWBP_MenuImageButton_C::In_Brush_Margin_Left' has a wrong offset!");
static_assert(offsetof(UWBP_MenuImageButton_C, ImageBrush) == 0x000338, "Member 'UWBP_MenuImageButton_C::ImageBrush' has a wrong offset!");
static_assert(offsetof(UWBP_MenuImageButton_C, ZoomOnHover) == 0x0003C0, "Member 'UWBP_MenuImageButton_C::ZoomOnHover' has a wrong offset!");
static_assert(offsetof(UWBP_MenuImageButton_C, ZoomValue) == 0x0003C4, "Member 'UWBP_MenuImageButton_C::ZoomValue' has a wrong offset!");

}

