#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_YesNoWidget

#include "Basic.hpp"

#include "AkAudio_structs.hpp"
#include "Engine_structs.hpp"
#include "HelloNeighbor2_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_YesNoWidget.WBP_YesNoWidget_C
// 0x0060 (0x0360 - 0x0300)
class UWBP_YesNoWidget_C final : public UBaseNavigableWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0300(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_1;                                           // 0x0308(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULocalizationText*                      ltQuestion;                                        // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULocalizationText*                      ltTitle;                                           // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MenuTextButton_C*                  WBP_MenuTextButton_No;                             // 0x0320(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_MenuTextButton_C*                  WBP_MenuTextButton_Yes;                            // 0x0328(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FString                                 LocalizedRowTitle;                                 // 0x0330(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	class FString                                 LocalizedRowQuestion;                              // 0x0340(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UAkAudioEvent*                          YesPressedSound;                                   // 0x0350(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAkAudioEvent*                          NoPressedSound;                                    // 0x0358(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_YesNoWidget(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void Construct();
	void BndEvt__WBP_YesNoWidget_WBP_MenuTextButton_No_K2Node_ComponentBoundEvent_1_OnInputEnter__DelegateSignature(class UBaseMenuElement* EnteredMenuElement);
	void Back();
	void BndEvt__WBP_YesNoWidget_WBP_MenuTextButton_Yes_K2Node_ComponentBoundEvent_0_OnInputEnter__DelegateSignature(class UBaseMenuElement* EnteredMenuElement);
	void FillMenuElementsArray(TArray<class UBaseMenuElement*>* MenuElementsToFill);
	void Init(class FName Title, class FName Question);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_YesNoWidget_C">();
	}
	static class UWBP_YesNoWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_YesNoWidget_C>();
	}
};
static_assert(alignof(UWBP_YesNoWidget_C) == 0x000008, "Wrong alignment on UWBP_YesNoWidget_C");
static_assert(sizeof(UWBP_YesNoWidget_C) == 0x000360, "Wrong size on UWBP_YesNoWidget_C");
static_assert(offsetof(UWBP_YesNoWidget_C, UberGraphFrame) == 0x000300, "Member 'UWBP_YesNoWidget_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_YesNoWidget_C, Image_1) == 0x000308, "Member 'UWBP_YesNoWidget_C::Image_1' has a wrong offset!");
static_assert(offsetof(UWBP_YesNoWidget_C, ltQuestion) == 0x000310, "Member 'UWBP_YesNoWidget_C::ltQuestion' has a wrong offset!");
static_assert(offsetof(UWBP_YesNoWidget_C, ltTitle) == 0x000318, "Member 'UWBP_YesNoWidget_C::ltTitle' has a wrong offset!");
static_assert(offsetof(UWBP_YesNoWidget_C, WBP_MenuTextButton_No) == 0x000320, "Member 'UWBP_YesNoWidget_C::WBP_MenuTextButton_No' has a wrong offset!");
static_assert(offsetof(UWBP_YesNoWidget_C, WBP_MenuTextButton_Yes) == 0x000328, "Member 'UWBP_YesNoWidget_C::WBP_MenuTextButton_Yes' has a wrong offset!");
static_assert(offsetof(UWBP_YesNoWidget_C, LocalizedRowTitle) == 0x000330, "Member 'UWBP_YesNoWidget_C::LocalizedRowTitle' has a wrong offset!");
static_assert(offsetof(UWBP_YesNoWidget_C, LocalizedRowQuestion) == 0x000340, "Member 'UWBP_YesNoWidget_C::LocalizedRowQuestion' has a wrong offset!");
static_assert(offsetof(UWBP_YesNoWidget_C, YesPressedSound) == 0x000350, "Member 'UWBP_YesNoWidget_C::YesPressedSound' has a wrong offset!");
static_assert(offsetof(UWBP_YesNoWidget_C, NoPressedSound) == 0x000358, "Member 'UWBP_YesNoWidget_C::NoPressedSound' has a wrong offset!");

}

