#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GameResultsEndTime

#include "Basic.hpp"

#include "WBP_GameResultsEndTime_classes.hpp"
#include "WBP_GameResultsEndTime_parameters.hpp"


namespace SDK
{

// Function WBP_GameResultsEndTime.WBP_GameResultsEndTime_C.BndEvt__WBP_GameResultsEndTime_Close_1_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_GameResultsEndTime_C::BndEvt__WBP_GameResultsEndTime_Close_1_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameResultsEndTime_C", "BndEvt__WBP_GameResultsEndTime_Close_1_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GameResultsEndTime.WBP_GameResultsEndTime_C.ExecuteUbergraph_WBP_GameResultsEndTime
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GameResultsEndTime_C::ExecuteUbergraph_WBP_GameResultsEndTime(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameResultsEndTime_C", "ExecuteUbergraph_WBP_GameResultsEndTime");

	Params::WBP_GameResultsEndTime_C_ExecuteUbergraph_WBP_GameResultsEndTime Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GameResultsEndTime.WBP_GameResultsEndTime_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_GameResultsEndTime_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GameResultsEndTime_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}

}

