#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CheatMenu

#include "Basic.hpp"

#include "WBP_CheatMenu_classes.hpp"
#include "WBP_CheatMenu_parameters.hpp"


namespace SDK
{

// Function WBP_CheatMenu.WBP_CheatMenu_C.ExecuteUbergraph_WBP_CheatMenu
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CheatMenu_C::ExecuteUbergraph_WBP_CheatMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CheatMenu_C", "ExecuteUbergraph_WBP_CheatMenu");

	Params::WBP_CheatMenu_C_ExecuteUbergraph_WBP_CheatMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CheatMenu.WBP_CheatMenu_C.BndEvt__WBP_CheatMenu_BT_ActivityDisplay_K2Node_ComponentBoundEvent_10_OnInputEnter__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBaseMenuElement*                 EnteredMenuElement                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CheatMenu_C::BndEvt__WBP_CheatMenu_BT_ActivityDisplay_K2Node_ComponentBoundEvent_10_OnInputEnter__DelegateSignature(class UBaseMenuElement* EnteredMenuElement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CheatMenu_C", "BndEvt__WBP_CheatMenu_BT_ActivityDisplay_K2Node_ComponentBoundEvent_10_OnInputEnter__DelegateSignature");

	Params::WBP_CheatMenu_C_BndEvt__WBP_CheatMenu_BT_ActivityDisplay_K2Node_ComponentBoundEvent_10_OnInputEnter__DelegateSignature Parms{};

	Parms.EnteredMenuElement = EnteredMenuElement;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CheatMenu.WBP_CheatMenu_C.BndEvt__WBP_CheatMenu_WBP_MenuButton_5_K2Node_ComponentBoundEvent_9_OnInputEnter__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBaseMenuElement*                 EnteredMenuElement                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CheatMenu_C::BndEvt__WBP_CheatMenu_WBP_MenuButton_5_K2Node_ComponentBoundEvent_9_OnInputEnter__DelegateSignature(class UBaseMenuElement* EnteredMenuElement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CheatMenu_C", "BndEvt__WBP_CheatMenu_WBP_MenuButton_5_K2Node_ComponentBoundEvent_9_OnInputEnter__DelegateSignature");

	Params::WBP_CheatMenu_C_BndEvt__WBP_CheatMenu_WBP_MenuButton_5_K2Node_ComponentBoundEvent_9_OnInputEnter__DelegateSignature Parms{};

	Parms.EnteredMenuElement = EnteredMenuElement;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CheatMenu.WBP_CheatMenu_C.BndEvt__WBP_CheatMenu_BT_AddQuestItem_K2Node_ComponentBoundEvent_8_OnInputEnter__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBaseMenuElement*                 EnteredMenuElement                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CheatMenu_C::BndEvt__WBP_CheatMenu_BT_AddQuestItem_K2Node_ComponentBoundEvent_8_OnInputEnter__DelegateSignature(class UBaseMenuElement* EnteredMenuElement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CheatMenu_C", "BndEvt__WBP_CheatMenu_BT_AddQuestItem_K2Node_ComponentBoundEvent_8_OnInputEnter__DelegateSignature");

	Params::WBP_CheatMenu_C_BndEvt__WBP_CheatMenu_BT_AddQuestItem_K2Node_ComponentBoundEvent_8_OnInputEnter__DelegateSignature Parms{};

	Parms.EnteredMenuElement = EnteredMenuElement;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CheatMenu.WBP_CheatMenu_C.BndEvt__WBP_CheatMenu_BT_LoadTable_K2Node_ComponentBoundEvent_7_OnInputEnter__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBaseMenuElement*                 EnteredMenuElement                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CheatMenu_C::BndEvt__WBP_CheatMenu_BT_LoadTable_K2Node_ComponentBoundEvent_7_OnInputEnter__DelegateSignature(class UBaseMenuElement* EnteredMenuElement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CheatMenu_C", "BndEvt__WBP_CheatMenu_BT_LoadTable_K2Node_ComponentBoundEvent_7_OnInputEnter__DelegateSignature");

	Params::WBP_CheatMenu_C_BndEvt__WBP_CheatMenu_BT_LoadTable_K2Node_ComponentBoundEvent_7_OnInputEnter__DelegateSignature Parms{};

	Parms.EnteredMenuElement = EnteredMenuElement;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CheatMenu.WBP_CheatMenu_C.BndEvt__WBP_CheatMenu_BT_GhostWalk_K2Node_ComponentBoundEvent_6_OnInputEnter__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBaseMenuElement*                 EnteredMenuElement                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CheatMenu_C::BndEvt__WBP_CheatMenu_BT_GhostWalk_K2Node_ComponentBoundEvent_6_OnInputEnter__DelegateSignature(class UBaseMenuElement* EnteredMenuElement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CheatMenu_C", "BndEvt__WBP_CheatMenu_BT_GhostWalk_K2Node_ComponentBoundEvent_6_OnInputEnter__DelegateSignature");

	Params::WBP_CheatMenu_C_BndEvt__WBP_CheatMenu_BT_GhostWalk_K2Node_ComponentBoundEvent_6_OnInputEnter__DelegateSignature Parms{};

	Parms.EnteredMenuElement = EnteredMenuElement;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CheatMenu.WBP_CheatMenu_C.BndEvt__WBP_CheatMenu_BT_TeleportPlayer_K2Node_ComponentBoundEvent_5_OnInputEnter__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBaseMenuElement*                 EnteredMenuElement                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CheatMenu_C::BndEvt__WBP_CheatMenu_BT_TeleportPlayer_K2Node_ComponentBoundEvent_5_OnInputEnter__DelegateSignature(class UBaseMenuElement* EnteredMenuElement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CheatMenu_C", "BndEvt__WBP_CheatMenu_BT_TeleportPlayer_K2Node_ComponentBoundEvent_5_OnInputEnter__DelegateSignature");

	Params::WBP_CheatMenu_C_BndEvt__WBP_CheatMenu_BT_TeleportPlayer_K2Node_ComponentBoundEvent_5_OnInputEnter__DelegateSignature Parms{};

	Parms.EnteredMenuElement = EnteredMenuElement;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CheatMenu.WBP_CheatMenu_C.BndEvt__WBP_CheatMenu_BT_Exit_K2Node_ComponentBoundEvent_4_OnInputEnter__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBaseMenuElement*                 EnteredMenuElement                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CheatMenu_C::BndEvt__WBP_CheatMenu_BT_Exit_K2Node_ComponentBoundEvent_4_OnInputEnter__DelegateSignature(class UBaseMenuElement* EnteredMenuElement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CheatMenu_C", "BndEvt__WBP_CheatMenu_BT_Exit_K2Node_ComponentBoundEvent_4_OnInputEnter__DelegateSignature");

	Params::WBP_CheatMenu_C_BndEvt__WBP_CheatMenu_BT_Exit_K2Node_ComponentBoundEvent_4_OnInputEnter__DelegateSignature Parms{};

	Parms.EnteredMenuElement = EnteredMenuElement;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CheatMenu.WBP_CheatMenu_C.BndEvt__WBP_CheatMenu_BT_SubMenuQuests_K2Node_ComponentBoundEvent_3_OnInputEnter__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBaseMenuElement*                 EnteredMenuElement                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CheatMenu_C::BndEvt__WBP_CheatMenu_BT_SubMenuQuests_K2Node_ComponentBoundEvent_3_OnInputEnter__DelegateSignature(class UBaseMenuElement* EnteredMenuElement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CheatMenu_C", "BndEvt__WBP_CheatMenu_BT_SubMenuQuests_K2Node_ComponentBoundEvent_3_OnInputEnter__DelegateSignature");

	Params::WBP_CheatMenu_C_BndEvt__WBP_CheatMenu_BT_SubMenuQuests_K2Node_ComponentBoundEvent_3_OnInputEnter__DelegateSignature Parms{};

	Parms.EnteredMenuElement = EnteredMenuElement;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CheatMenu.WBP_CheatMenu_C.BndEvt__WBP_CheatMenu_BT_GameTimeDilition_K2Node_ComponentBoundEvent_2_OnInputEnter__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBaseMenuElement*                 EnteredMenuElement                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CheatMenu_C::BndEvt__WBP_CheatMenu_BT_GameTimeDilition_K2Node_ComponentBoundEvent_2_OnInputEnter__DelegateSignature(class UBaseMenuElement* EnteredMenuElement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CheatMenu_C", "BndEvt__WBP_CheatMenu_BT_GameTimeDilition_K2Node_ComponentBoundEvent_2_OnInputEnter__DelegateSignature");

	Params::WBP_CheatMenu_C_BndEvt__WBP_CheatMenu_BT_GameTimeDilition_K2Node_ComponentBoundEvent_2_OnInputEnter__DelegateSignature Parms{};

	Parms.EnteredMenuElement = EnteredMenuElement;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CheatMenu.WBP_CheatMenu_C.BndEvt__WBP_CheatMenu_BT_DisableAISeeing_K2Node_ComponentBoundEvent_1_OnInputEnter__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBaseMenuElement*                 EnteredMenuElement                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CheatMenu_C::BndEvt__WBP_CheatMenu_BT_DisableAISeeing_K2Node_ComponentBoundEvent_1_OnInputEnter__DelegateSignature(class UBaseMenuElement* EnteredMenuElement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CheatMenu_C", "BndEvt__WBP_CheatMenu_BT_DisableAISeeing_K2Node_ComponentBoundEvent_1_OnInputEnter__DelegateSignature");

	Params::WBP_CheatMenu_C_BndEvt__WBP_CheatMenu_BT_DisableAISeeing_K2Node_ComponentBoundEvent_1_OnInputEnter__DelegateSignature Parms{};

	Parms.EnteredMenuElement = EnteredMenuElement;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CheatMenu.WBP_CheatMenu_C.OnSubWidgetClose
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBaseUserWidget*                  WidgetToHide                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CheatMenu_C::OnSubWidgetClose(class UBaseUserWidget* WidgetToHide)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CheatMenu_C", "OnSubWidgetClose");

	Params::WBP_CheatMenu_C_OnSubWidgetClose Parms{};

	Parms.WidgetToHide = WidgetToHide;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CheatMenu.WBP_CheatMenu_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_CheatMenu_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CheatMenu_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CheatMenu.WBP_CheatMenu_C.BndEvt__WBP_NewCheatMenu_BT_SubMenuStatuses_K2Node_ComponentBoundEvent_0_OnInputEnter__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBaseMenuElement*                 EnteredMenuElement                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CheatMenu_C::BndEvt__WBP_NewCheatMenu_BT_SubMenuStatuses_K2Node_ComponentBoundEvent_0_OnInputEnter__DelegateSignature(class UBaseMenuElement* EnteredMenuElement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CheatMenu_C", "BndEvt__WBP_NewCheatMenu_BT_SubMenuStatuses_K2Node_ComponentBoundEvent_0_OnInputEnter__DelegateSignature");

	Params::WBP_CheatMenu_C_BndEvt__WBP_NewCheatMenu_BT_SubMenuStatuses_K2Node_ComponentBoundEvent_0_OnInputEnter__DelegateSignature Parms{};

	Parms.EnteredMenuElement = EnteredMenuElement;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CheatMenu.WBP_CheatMenu_C.Leave
// (BlueprintEvent)

void UWBP_CheatMenu_C::Leave()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CheatMenu_C", "Leave");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CheatMenu.WBP_CheatMenu_C.FillMenuElementsArray
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UBaseMenuElement*>*        MenuElementsToFill                                     (Parm, OutParm, ContainsInstancedReference)

void UWBP_CheatMenu_C::FillMenuElementsArray(TArray<class UBaseMenuElement*>* MenuElementsToFill)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CheatMenu_C", "FillMenuElementsArray");

	Params::WBP_CheatMenu_C_FillMenuElementsArray Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (MenuElementsToFill != nullptr)
		*MenuElementsToFill = std::move(Parms.MenuElementsToFill);
}


// Function WBP_CheatMenu.WBP_CheatMenu_C.CreateSubMenu
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           Widget_Class                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CheatMenu_C::CreateSubMenu(class UClass* Widget_Class)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CheatMenu_C", "CreateSubMenu");

	Params::WBP_CheatMenu_C_CreateSubMenu Parms{};

	Parms.Widget_Class = Widget_Class;

	UObject::ProcessEvent(Func, &Parms);
}

}

