#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace BPW_MenuPause
{
	class UPLACEHOLDER_CLASS__BPW_Loading_C_2;
	class UPLACEHOLDER_CLASS__BPW_BtnSave_C_0;
}

namespace BPW_HS_MenuPause
{
	class UPLACEHOLDER_CLASS__BPW_Loading_C_2;
	class UPLACEHOLDER_CLASS__BPW_BtnSave_C_0;
}
